package base;

import com.microsoft.playwright.Page;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.FileReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.opencsv.CSVReader;

/**
 * BasePage — Base class for all page classes
 * Provides test data loading and credential management
 * Generated by: Qentrix Framework
 * Framework: Playwright Java (Hybrid)
 */
public class BasePage {

    protected Page page;
    protected Map<String, Object> testData;
    protected List<Map<String, String>> loginData;

    public BasePage(Page page) {
        this.page = page;
        loadTestData();
        loadCredentials();
    }

    /**
     * Load static test data from utils/testdata.json
     */
    private void loadTestData() {
        try {
            String testdataPath = "src/main/resources/testdata.json";
            if (Files.exists(Paths.get(testdataPath))) {
                ObjectMapper mapper = new ObjectMapper();
                testData = mapper.readValue(new File(testdataPath), Map.class);
            } else {
                testData = new HashMap<>();
            }
        } catch (Exception e) {
            System.err.println("Failed to load testdata.json: " + e.getMessage());
            testData = new HashMap<>();
        }
    }

    /**
     * Load credentials from test-data/credentials.csv
     */
    private void loadCredentials() {
        try {
            String credPath = "src/test/resources/credentials.csv";
            if (Files.exists(Paths.get(credPath))) {
                CSVReader reader = new CSVReader(new FileReader(credPath));
                loginData = new java.util.ArrayList<>();
                List<String[]> rows = reader.readAll();
                if (rows.size() > 0) {
                    String[] headers = rows.get(0);
                    for (int i = 1; i < rows.size(); i++) {
                        Map<String, String> row = new HashMap<>();
                        for (int j = 0; j < headers.length; j++) {
                            row.put(headers[j].trim(), rows.get(i)[j].trim());
                        }
                        loginData.add(row);
                    }
                }
                reader.close();
            } else {
                loginData = new java.util.ArrayList<>();
            }
        } catch (Exception e) {
            System.err.println("Failed to load credentials.csv: " + e.getMessage());
            loginData = new java.util.ArrayList<>();
        }
    }

    /**
     * Get credentials for a given role
     * @param roleName must match RoleName column in credentials.csv
     * @return Map containing Username, Password, FullName
     */
    protected Map<String, String> getLoginDataByRole(String roleName) {
        for (Map<String, String> row : loginData) {
            if (row.get("RoleName").equals(roleName)) {
                return row;
            }
        }
        throw new RuntimeException("No credentials found for role: " + roleName + ". Check credentials.csv");
    }
}
