package tests;

import base.BaseTest;
import io.qameta.allure.*;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.LoginPage;

import java.util.Map;

/**
 * LoginTest.java
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java TestNG
 * Purpose: Test orchestration for Login feature
 * Test cases: TC-562, TC-22, TC-24, TC-25, TC-21, TC-23, TC-561, TC-563, TC-560, TC-564
 * Tags: @smoke, @regression
 */
@Epic("Authentication")
@Feature("Login")
public class LoginTest extends BaseTest {

    private LoginPage loginPage;

    @BeforeMethod
    public void setUp() {
        super.setUp();
        loginPage = new LoginPage(driver);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-560: Verify that login works with valid credentials
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 1, groups = {"smoke", "regression"})
    @Severity(SeverityLevel.CRITICAL)
    @Description("TC-560: Verify that login works with valid credentials")
    @Story("Valid Login")
    public void tc560_verifyLoginWithValidCredentials() {
        step("Send POST request to /login endpoint", () -> {
            loginPage.navigateToLoginPage();
        });

        step("Include valid username in request body", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterUsername(creds.get("username"));
        });

        step("Include valid password in request body", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterPassword(creds.get("password"));
        });

        step("Submit authentication request", () -> {
            loginPage.clickLoginButton();
        });

        step("Validate response returns 200 status code", () -> {
            loginPage.verifyLoginSuccessful();
        });

        step("Validate response contains authentication token", () -> {
            loginPage.verifyAuthenticationTokenPresent();
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-21: Verify that login works with valid credentials
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 2, groups = {"smoke", "regression"})
    @Severity(SeverityLevel.CRITICAL)
    @Description("TC-21: Verify that login works with valid credentials")
    @Story("Valid Login")
    public void tc21_verifyLoginWithValidCredentials() {
        step("Open login page", () -> {
            loginPage.navigateToLoginPage();
            loginPage.verifyLoginPageLoaded();
        });

        step("Enter valid username", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterUsername(creds.get("username"));
        });

        step("Enter valid password", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterPassword(creds.get("password"));
        });

        step("Click login button", () -> {
            loginPage.clickLoginButton();
        });

        step("User should login successfully", () -> {
            loginPage.verifyLoginSuccessful();
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-561: Verify that login fails with invalid username
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 3, groups = {"regression"})
    @Severity(SeverityLevel.NORMAL)
    @Description("TC-561: Verify that login fails with invalid username")
    @Story("Invalid Username")
    public void tc561_verifyLoginFailsWithInvalidUsername() {
        step("Send POST request to /login endpoint", () -> {
            loginPage.navigateToLoginPage();
        });

        step("Include invalid username in request body", () -> {
            loginPage.enterUsername("invalidUser123");
        });

        step("Include valid password in request body", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterPassword(creds.get("password"));
        });

        step("Submit authentication request", () -> {
            loginPage.clickLoginButton();
        });

        step("Validate response returns 401 status code", () -> {
            loginPage.verifyInvalidCredentialsError();
        });

        step("Validate error message indicates invalid credentials", () -> {
            loginPage.verifyErrorMessageContains("invalid");
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-562: Verify that login fails with invalid password
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 4, groups = {"regression"})
    @Severity(SeverityLevel.NORMAL)
    @Description("TC-562: Verify that login fails with invalid password")
    @Story("Invalid Password")
    public void tc562_verifyLoginFailsWithInvalidPassword() {
        step("Send POST request to /login endpoint", () -> {
            loginPage.navigateToLoginPage();
        });

        step("Include valid username in request body", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterUsername(creds.get("username"));
        });

        step("Include invalid password in request body", () -> {
            loginPage.enterPassword("wrongPassword999");
        });

        step("Submit authentication request", () -> {
            loginPage.clickLoginButton();
        });

        step("Validate response returns 401 status code", () -> {
            loginPage.verifyInvalidCredentialsError();
        });

        step("Validate error message indicates invalid credentials", () -> {
            loginPage.verifyErrorMessageContains("invalid");
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-563: Verify that login fails with empty username
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 5, groups = {"regression"})
    @Severity(SeverityLevel.NORMAL)
    @Description("TC-563: Verify that login fails with empty username")
    @Story("Empty Username")
    public void tc563_verifyLoginFailsWithEmptyUsername() {
        step("Send POST request to /login endpoint", () -> {
            loginPage.navigateToLoginPage();
        });

        step("Include empty username field in request body", () -> {
            loginPage.enterUsername("");
        });

        step("Include valid password in request body", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterPassword(creds.get("password"));
        });

        step("Submit authentication request", () -> {
            loginPage.clickLoginButton();
        });

        step("Validate response returns 400 status code", () -> {
            loginPage.verifyMissingUsernameError();
        });

        step("Validate error message indicates missing username", () -> {
            loginPage.verifyErrorMessageContains("required");
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-564: Verify that login fails with empty password
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 6, groups = {"regression"})
    @Severity(SeverityLevel.NORMAL)
    @Description("TC-564: Verify that login fails with empty password")
    @Story("Empty Password")
    public void tc564_verifyLoginFailsWithEmptyPassword() {
        step("Send POST request to /login endpoint", () -> {
            loginPage.navigateToLoginPage();
        });

        step("Include valid username in request body", () -> {
            Map<String, String> creds = loginPage.getCredentialsByRole("Admin");
            loginPage.enterUsername(creds.get("username"));
        });

        step("Include empty password field in request body", () -> {
            loginPage.enterPassword("");
        });

        step("Submit authentication request", () -> {
            loginPage.clickLoginButton();
        });

        step("Validate response returns 400 status code", () -> {
            loginPage.verifyMissingPasswordError();
        });

        step("Validate error message indicates missing password", () -> {
            loginPage.verifyErrorMessageContains("required");
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-22: To Test Login Form with Invalid Data
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 7, groups = {"regression"})
    @Severity(SeverityLevel.NORMAL)
    @Description("TC-22: To Test Login Form with Invalid Data")
    @Story("Invalid Login Data")
    public void tc22_testLoginFormWithInvalidData() {
        step("Navigate to 192.168.10.124:4001", () -> {
            loginPage.navigateToLoginPage();
        });

        step("System should display Login Page with fields", () -> {
            loginPage.verifyLoginPageLoaded();
            loginPage.verifyRegisterLinkVisible();
        });

        step("Enter username and password", () -> {
            loginPage.enterUsername("invalidUser");
            loginPage.enterPassword("invalidPass");
        });

        step("System should accept the username and password", () -> {
            loginPage.clickLoginButton();
            loginPage.verifyInvalidCredentialsError();
        });
    }

    // ──────────────────────────────────────────────────────────────────────────
    // TC-23, TC-24, TC-25: Placeholder tests with minimal steps
    // ──────────────────────────────────────────────────────────────────────────

    @Test(priority = 8, groups = {"regression"})
    @Severity(SeverityLevel.MINOR)
    @Description("TC-23: To Test Login Form with Invalid Data")
    @Story("Invalid Login Data")
    public void tc23_testLoginFormWithInvalidData() {
        step("Navigate to login page", () -> {
            loginPage.navigateToLoginPage();
            loginPage.verifyLoginPageLoaded();
        });
        // Additional steps not provided in test case - implement based on requirements
    }

    @Test(priority = 9, groups = {"regression"})
    @Severity(SeverityLevel.MINOR)
    @Description("TC-24: To Test Login Form with Invalid Data")
    @Story("Invalid Login Data")
    public void tc24_testLoginFormWithInvalidData() {
        step("Navigate to login page", () -> {
            loginPage.navigateToLoginPage();
            loginPage.verifyLoginPageLoaded();
        });
        // Additional steps not provided in test case - implement based on requirements
    }

    @Test(priority = 10, groups = {"regression"})
    @Severity(SeverityLevel.TRIVIAL)
    @Description("TC-25: test import 01")
    @Story("Import Test")
    public void tc25_testImport01() {
        step("Navigate to login page", () -> {
            loginPage.navigateToLoginPage();
            loginPage.verifyLoginPageLoaded();
        });
        // Additional steps not provided in test case - implement based on requirements
    }

    // ── Helper method for readable test steps ─────────────────────────────────

    private void step(String description, Runnable action) {
        Allure.step(description, action::run);
    }
}