package pageObjects;

/**
 * LoginPage - Locator constants only
 * Generated by: Qentrix ScriptGenerationAgent
 * No logic, no methods, no imports beyond basic Java
 */
public class LoginPage {

    // ── Form inputs ───────────────────────────────────────────────────────────
    public static final String EMAIL_INPUT = "input[name='email']";
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String PASSWORD_INPUT = "input[type='password']";

    // ── Buttons ───────────────────────────────────────────────────────────────
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String SUBMIT_BUTTON = "//button[contains(., 'Login')]";

    // ── Navigation ────────────────────────────────────────────────────────────
    public static final String REGISTER_LINK = "a:has-text('Register')";

    // ── Validation / error messages ───────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String AUTH_ERROR_MESSAGE = "//*[contains(text(), 'Invalid credentials')]";
    public static final String MISSING_USERNAME_ERROR = "//*[contains(text(), 'missing username')]";
    public static final String MISSING_PASSWORD_ERROR = "//*[contains(text(), 'missing password')]";

    // ── Page verification ─────────────────────────────────────────────────────
    public static final String PAGE_HEADING = "h1";
    public static final String LOGIN_PAGE_INDICATOR = "//*[contains(text(), 'Login')]";

    // ── Success indicators ────────────────────────────────────────────────────
    public static final String AUTH_TOKEN_FIELD = "//input[@name='authToken']";
    public static final String SUCCESS_MESSAGE = ".success-message";

    // TODO: verify selectors against live app at 192.168.10.124:4001
}
