package pageObjects;

/**
 * LoginPage.java
 * ─────────────────────────────────────────────────────────────────────────────
 * Page Object: Locator constants only | Zero logic | Zero methods
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java Hybrid
 * ─────────────────────────────────────────────────────────────────────────────
 */
public class LoginPage {

    // ── Page URL fragment ─────────────────────────────────────────────────────
    public static final String LOGIN_URL_FRAGMENT = "/login";

    // ── Form inputs ───────────────────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String EMAIL_INPUT = "input[name='email']";
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String PASSWORD_INPUT = "input[type='password']";

    // ── Buttons ───────────────────────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String REGISTER_LINK = "a:has-text('Register')";

    // ── Validation messages ───────────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String INVALID_CREDENTIALS_MESSAGE = "//text()[contains(.,'Invalid credentials')]";
    public static final String MISSING_USERNAME_MESSAGE = "//text()[contains(.,'missing username')]";
    public static final String MISSING_PASSWORD_MESSAGE = "//text()[contains(.,'missing password')]";

    // ── Page heading ──────────────────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String PAGE_HEADING = "h1";

}
