package pageObjects;

/**
 * LoginPageObjects.java
 * Generated by: ScriptGenerationAgent
 * Framework: Selenium Java Hybrid
 * Description: Locator constants only. Zero logic. Zero methods.
 */
public class LoginPageObjects {

    // ── Page URL fragments ────────────────────────────────────────────────────
    public static final String LOGIN_URL_FRAGMENT = "/login";

    // ── Form inputs ───────────────────────────────────────────────────────────
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String EMAIL_INPUT = "input[type='email']";
    public static final String PASSWORD_INPUT = "input[type='password']";

    // ── Buttons ───────────────────────────────────────────────────────────────
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String REGISTER_LINK = "a:contains('Register')";

    // ── Validation messages ───────────────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String USERNAME_REQUIRED_ERROR = "//span[contains(text(),'Username') or contains(text(),'required')]";
    public static final String PASSWORD_REQUIRED_ERROR = "//span[contains(text(),'Password') or contains(text(),'required')]";
    public static final String INVALID_CREDENTIALS_ERROR = "//span[contains(text(),'Invalid') or contains(text(),'credentials')]";
    public static final String ACCOUNT_LOCKED_MESSAGE = "//span[contains(text(),'locked') or contains(text(),'deactivated')]";
    public static final String PASSWORD_LENGTH_ERROR = "//span[contains(text(),'length') or contains(text(),'minimum')]";

    // ── Post-login elements ───────────────────────────────────────────────────
    public static final String DASHBOARD_HEADING = "h1";
    public static final String USER_PROFILE_ICON = "[aria-label='User profile']";

    // ── Session/security elements ─────────────────────────────────────────────
    public static final String SESSION_EXPIRED_MESSAGE = "//span[contains(text(),'expired') or contains(text(),'timeout')]";

    // ── HTTPS indicator ───────────────────────────────────────────────────────
    // Verified via WebDriver URL check in test

    // ── Notes ─────────────────────────────────────────────────────────────────
    // All selectors inferred from test case steps and common stable UI patterns.
    // Update after exploration if actual app selectors differ.
}
