// Authentication Page Object - Locators Only
// Generated by Qentrix for AG-Helix

// Login Section
export const usernameInput = '#username'; // TODO: verify selector against live app
export const passwordInput = '#password'; // TODO: verify selector against live app
export const loginButton = 'button[type="submit"]'; // TODO: verify selector against live app
export const loginErrorMessage = '.error-message'; // TODO: verify selector against live app
export const validationError = '.validation-error'; // TODO: verify selector against live app

// Registration Section
export const registrationForm = '#registration-form'; // TODO: verify selector against live app
export const regUsernameInput = '#reg-username'; // TODO: verify selector against live app
export const regEmailInput = '#reg-email'; // TODO: verify selector against live app
export const regPasswordInput = '#reg-password'; // TODO: verify selector against live app
export const regPasswordConfirmInput = '#reg-password-confirm'; // TODO: verify selector against live app
export const registerButton = 'button[type="submit"]'; // TODO: verify selector against live app
export const registrationErrorMessage = '.registration-error'; // TODO: verify selector against live app
export const registrationSuccessMessage = '.success-message'; // TODO: verify selector against live app

// Forgot Password Section
export const forgotPasswordLink = 'a[href*="forgot-password"]'; // TODO: verify selector against live app
export const forgotPasswordEmailInput = '#forgot-email'; // TODO: verify selector against live app
export const sendResetLinkButton = 'button[type="submit"]'; // TODO: verify selector against live app
export const resetPasswordErrorMessage = '.reset-error'; // TODO: verify selector against live app
export const resetPasswordSuccessMessage = '.reset-success'; // TODO: verify selector against live app

// Dashboard Section
export const dashboardHeader = 'h1'; // TODO: verify selector against live app
export const dashboardContainer = '.dashboard-container'; // TODO: verify selector against live app
export const userMenuButton = '#user-menu'; // TODO: verify selector against live app
export const logoutOption = 'a[href*="logout"]'; // TODO: verify selector against live app

