// Login Page Object - Locators Only
// Generated by Qentrix

export const LOGIN_PAGE = {
  // Login Form Elements
  usernameInput: 'input[name="username"]',
  passwordInput: 'input[name="password"]',
  loginButton: 'button[type="submit"]',
  
  // Login Page Identifiers
  loginForm: 'form',
  loginLogo: '.orangehrm-login-logo',
  
  // Error Messages
  errorMessage: '.oxd-alert-content-text',
  
  // Post-Login Verification
  dashboardHeader: 'h6.oxd-topbar-header-breadcrumb-module',
  userDropdown: '.oxd-userdropdown-tab'
};

