// Login Page Object - Locators Only
// Generated by Qentrix for AG-Helix project

// Login Form Elements
export const usernameInput = '#username'; // TODO: verify selector against live app
export const emailInput = 'input[type="email"], input[name="email"], input[placeholder*="Email" i]';
export const passwordInput = '#password, input[type="password"], input[name="password"]';
export const loginButton = 'button[type="submit"], button:has-text("Login"), #login-button';
export const registerLink = 'a:has-text("Register")';

// Error Messages
export const errorMessage = '.error-message, [role="alert"], .alert-danger, .validation-error';
export const usernameRequiredError = '.username-error, [data-field="username"] + .error';
export const passwordRequiredError = '.password-error, [data-field="password"] + .error';
export const accountDisabledError = '.account-disabled-error, [data-error-type="account_disabled"]';
export const invalidCredentialsError = '.invalid-credentials-error, .auth-error';

// Page Elements
export const pageTitle = 'h1, .page-title, .login-title';
export const brandingLogo = '.logo, .brand-logo, img[alt*="logo" i]';
export const loadingSpinner = '.spinner, .loading, [role="progressbar"]';

// Security Elements
export const secureConnectionIndicator = '.secure-badge, .https-indicator';
export const sslCertificateIcon = '.ssl-icon';

// Form Validation
export const fieldValidationError = '.field-error, .validation-message';
export const invalidFieldHighlight = '.is-invalid, .error-border, input.error';

// Placeholders (for verification)
export const usernamePlaceholder = 'input[placeholder]'; // Will verify placeholder text in page class
export const passwordPlaceholder = 'input[type="password"][placeholder]';

