// Login Page Object - Locators Only
// Generated by Qentrix for AG-Helix

export const loginPageLocators = {
  // Form Fields
  emailInput: '#email', // TODO: verify selector against live app
  usernameInput: '#username', // TODO: verify selector against live app
  passwordInput: '#password', // TODO: verify selector against live app
  
  // Buttons
  loginButton: "button[type='submit']", // TODO: verify selector against live app
  registerLink: "a:has-text('Register')", // TODO: verify selector against live app
  
  // Messages and Validation
  errorMessage: '.error-message', // TODO: verify selector against live app
  validationError: '.validation-error', // TODO: verify selector against live app
  accountDisabledMessage: "//div[contains(text(), 'account') and contains(text(), 'disabled')]",
  usernameRequiredError: "//span[contains(text(), 'username') or contains(text(), 'required')]",
  passwordRequiredError: "//span[contains(text(), 'password') or contains(text(), 'required')]",
  
  // Page Elements
  pageTitle: 'h1', // TODO: verify selector against live app
  brandingLogo: '.logo', // TODO: verify selector against live app
  loginForm: 'form', // TODO: verify selector against live app
  
  // Security and Protocol
  secureIcon: '.secure-connection', // TODO: verify selector against live app
  
  // Placeholders (for verification)
  usernamePlaceholder: "input[placeholder*='username' i]",
  passwordPlaceholder: "input[placeholder*='password' i]"
};

