// Profile Page Object - Locators Only
// Generated by Qentrix for AG-Helix

// Profile Information Section
export const profileContainer = '.profile-container'; // TODO: verify selector against live app
export const firstNameInput = '#first-name'; // TODO: verify selector against live app
export const lastNameInput = '#last-name'; // TODO: verify selector against live app
export const emailInput = '#email'; // TODO: verify selector against live app
export const saveChangesButton = 'button[type="submit"]'; // TODO: verify selector against live app
export const successMessage = '.success-message'; // TODO: verify selector against live app
export const errorMessage = '.error-message'; // TODO: verify selector against live app

// Password Change Section
export const changePasswordLink = 'a[href*="change-password"]'; // TODO: verify selector against live app
export const currentPasswordInput = '#current-password'; // TODO: verify selector against live app
export const newPasswordInput = '#new-password'; // TODO: verify selector against live app
export const confirmPasswordInput = '#confirm-password'; // TODO: verify selector against live app
export const savePasswordButton = 'button[type="submit"]'; // TODO: verify selector against live app
export const passwordErrorMessage = '.password-error'; // TODO: verify selector against live app
export const passwordSuccessMessage = '.password-success'; // TODO: verify selector against live app

// Account Information Section
export const accountInfoSection = '.account-info'; // TODO: verify selector against live app
export const usernameDisplay = '.username-display'; // TODO: verify selector against live app
export const emailDisplay = '.email-display'; // TODO: verify selector against live app
export const accountCreationDate = '.creation-date'; // TODO: verify selector against live app

// Account Activity Section
export const activityHistorySection = '.activity-history'; // TODO: verify selector against live app
export const loginHistoryList = '.login-history'; // TODO: verify selector against live app
export const activityTimestamp = '.activity-timestamp'; // TODO: verify selector against live app
export const activityDetails = '.activity-details'; // TODO: verify selector against live app

