// Registration Page Object - Locators Only
// Auto-generated by Qentrix - DO NOT MANUALLY EDIT

// Login Section
export const usernameInput = 'input[name="username"], input[placeholder*="Username"], #username';
export const passwordInput = 'input[name="password"], input[type="password"], #password';
export const loginButton = 'button[type="submit"], button:has-text("Login"), //button[contains(., "Login")]';

// Registration Section
export const emailInput = 'input[name="email"], input[type="email"], input[placeholder*="Email"], #email';
export const registerPasswordInput = 'input[name="password"], input[type="password"], #register-password, //label[contains(., "Password")]/following::input[type="password"][1]';
export const registerButton = 'button[type="submit"]:has-text("Register"), button:has-text("Register"), //button[contains(., "Register")]';

// Validation Messages
export const validationError = '.error-message, .validation-error, [role="alert"], .alert-danger, //div[contains(@class, "error")]';
export const emailRequiredError = '//text()[contains(., "email") and contains(., "required")]/ancestor::*[1], [data-testid="email-error"]';
export const passwordRequiredError = '//text()[contains(., "password") and contains(., "required")]/ancestor::*[1], [data-testid="password-error"]';
export const emailInvalidError = '//text()[contains(., "email") and (contains(., "invalid") or contains(., "format"))]/ancestor::*[1]';
export const emailExistsError = '//text()[contains(., "email") and (contains(., "exists") or contains(., "registered"))]/ancestor::*[1]';
export const passwordLengthError = '//text()[contains(., "password") and (contains(., "length") or contains(., "characters"))]/ancestor::*[1]';

// Success Messages
export const successMessage = '.success-message, .alert-success, [role="status"], //div[contains(@class, "success")]';
export const confirmationMessage = '//text()[contains(., "confirmation") or contains(., "created") or contains(., "successful")]/ancestor::*[1]';

// TODO: verify selectors against live app - these are inferred from test steps and common UI patterns

