package pageObjects;

/**
 * LoginPage - Locator constants only
 * Generated by Qentrix ScriptGenerationAgent
 * RULES: No imports | No logic | No methods | Stable selectors only
 */
public class LoginPage {

    // ── Login form elements ───────────────────────────────────────────────────
    public static final String EMAIL_INPUT = "input[name='email']";
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String PASSWORD_INPUT = "input[type='password']";
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String LOGIN_BUTTON_TEXT = "//button[contains(text(),'Login')]";
    
    // ── Page elements ─────────────────────────────────────────────────────────
    public static final String PAGE_HEADING = "h1";
    public static final String REGISTER_LINK = "//a[contains(text(),'Register')]";
    
    // ── Validation messages ───────────────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String ERROR_MESSAGE_TEXT = "//*[contains(@class,'error') or contains(@class,'alert')]";
    public static final String VALIDATION_MESSAGE = ".validation-message";
    public static final String FIELD_REQUIRED_ERROR = "//*[contains(text(),'required')]";
    public static final String INVALID_CREDENTIALS_ERROR = "//*[contains(text(),'Invalid') or contains(text(),'invalid') or contains(text(),'credentials')]";
    
    // ── Post-login elements ───────────────────────────────────────────────────
    public static final String DASHBOARD_INDICATOR = "//h1[contains(text(),'Dashboard')]";
    public static final String USER_PROFILE = "[data-testid='user-profile']";
    public static final String LOGOUT_BUTTON = "//button[contains(text(),'Logout')]";
    
    // TODO: verify selector against live app at 192.168.10.124:4001
}