package runners;

import org.junit.platform.suite.api.*;

/**
 * RegressionRunner - Regression test suite
 * Generated by: ScriptGenerationAgent
 * Framework: Selenium Java BDD
 */
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = "cucumber.filter.tags", value = "@regression")
@ConfigurationParameter(key = "cucumber.plugin", value = "pretty, html:target/cucumber-reports/regression.html, json:target/cucumber-reports/regression.json, junit:target/cucumber-reports/regression.xml")
@ConfigurationParameter(key = "cucumber.glue", value = "stepDefinitions")
public class RegressionRunner {
}
