package runners;

import org.junit.platform.suite.api.*;

/**
 * TestRunner - Full test suite
 * Generated by: ScriptGenerationAgent
 * Framework: Selenium Java BDD
 */
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = "cucumber.plugin", value = "pretty, html:target/cucumber-reports/cucumber.html, json:target/cucumber-reports/cucumber.json, junit:target/cucumber-reports/cucumber.xml")
@ConfigurationParameter(key = "cucumber.glue", value = "stepDefinitions")
public class TestRunner {
}
