package stepDefinitions;

import base.BaseTest;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import pages.LoginPage;

/**
 * LoginSteps - Step definitions for login feature
 * Generated by: ScriptGenerationAgent
 * Framework: Selenium Java BDD
 */
public class LoginSteps extends BaseTest {

    private LoginPage loginPage;

    public LoginSteps() {
        this.loginPage = new LoginPage(driver);
    }

    // ── Navigation steps ──────────────────────────────────────────────────────

    @Given("user navigates to the login page")
    public void userNavigatesToLoginPage() {
        loginPage.navigateToLoginPage();
    }

    @Given("user is on the login page")
    public void userIsOnLoginPage() {
        loginPage.navigateToLoginPage();
        loginPage.verifyLoginPageDisplayed();
    }

    @Given("the login page is displayed")
    public void loginPageIsDisplayed() {
        loginPage.verifyLoginPageDisplayed();
    }

    // ── Input steps ───────────────────────────────────────────────────────────

    @When("user enters valid username {string}")
    public void userEntersValidUsername(String username) {
        loginPage.enterUsername(username);
    }

    @When("user enters invalid username {string}")
    public void userEntersInvalidUsername(String username) {
        loginPage.enterUsername(username);
    }

    @When("user enters valid password {string}")
    public void userEntersValidPassword(String password) {
        loginPage.enterPassword(password);
    }

    @When("user enters invalid password {string}")
    public void userEntersInvalidPassword(String password) {
        loginPage.enterPassword(password);
    }

    @When("user enters empty username")
    public void userEntersEmptyUsername() {
        loginPage.enterUsername("");
    }

    @When("user enters empty password")
    public void userEntersEmptyPassword() {
        loginPage.enterPassword("");
    }

    @When("user enters username and password")
    public void userEntersUsernameAndPassword() {
        String[] creds = loginPage.getLoginDataByRole("User");
        loginPage.enterUsername(creds[0]);
        loginPage.enterPassword(creds[1]);
    }

    // ── Action steps ──────────────────────────────────────────────────────────

    @When("user clicks the login button")
    public void userClicksLoginButton() {
        loginPage.clickLoginButton();
    }

    @When("user submits the login form")
    public void userSubmitsLoginForm() {
        loginPage.submitLoginForm();
    }

    @When("user submits authentication request")
    public void userSubmitsAuthenticationRequest() {
        loginPage.submitLoginForm();
    }

    @When("user logs in as {string}")
    public void userLogsInAs(String roleName) {
        loginPage.loginAs(roleName);
    }

    @When("user logs in with valid credentials")
    public void userLogsInWithValidCredentials() {
        loginPage.loginAs("User");
    }

    // ── Verification steps ────────────────────────────────────────────────────

    @Then("login page should display all UI elements")
    public void loginPageShouldDisplayAllElements() {
        loginPage.verifyLoginPageElements();
    }

    @Then("user should login successfully")
    public void userShouldLoginSuccessfully() {
        loginPage.verifyLoginSuccessful();
    }

    @Then("authentication token should be present in response")
    public void authTokenShouldBePresent() {
        loginPage.verifyAuthenticationTokenPresent();
    }

    @Then("response should return status code {int}")
    public void responseShouldReturnStatusCode(int statusCode) {
        loginPage.verifyResponseStatusCode(statusCode);
    }

    @Then("error message should indicate invalid credentials")
    public void errorMessageShouldIndicateInvalidCredentials() {
        loginPage.verifyLoginFailsWithInvalidCredentials();
    }

    @Then("error message should indicate missing username")
    public void errorMessageShouldIndicateMissingUsername() {
        loginPage.verifyMissingUsernameError();
    }

    @Then("error message should indicate missing password")
    public void errorMessageShouldIndicateMissingPassword() {
        loginPage.verifyMissingPasswordError();
    }

    @Then("appropriate error message should be displayed")
    public void appropriateErrorMessageShouldBeDisplayed() {
        loginPage.verifyErrorMessageDisplayed("error");
    }

    @Then("system should accept the username and password")
    public void systemShouldAcceptCredentials() {
        // Implicit - no validation error means accepted
        loginPage.waitForPageLoad();
    }
}
