from pages.basePage import BasePage
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class LoginPage(BasePage):
    """
    Login Page Object - AG-Helix Application
    Generated by Qentrix ScriptGenerationAgent
    Framework: Selenium + Python + Hybrid
    """

    # ── Locators ──────────────────────────────────────────────────────────────
    EMAIL_INPUT = (By.ID, "email")  # TODO: verify selector against live app
    PASSWORD_INPUT = (By.ID, "password")  # TODO: verify selector against live app
    LOGIN_BUTTON = (By.XPATH, "//button[contains(., 'Login')]")  # TODO: verify selector against live app
    REGISTER_LINK = (By.XPATH, "//a[contains(., 'Register')]")  # TODO: verify selector against live app
    ERROR_MESSAGE = (By.CSS_SELECTOR, ".error-message")  # TODO: verify selector against live app
    VALIDATION_MESSAGE = (By.CSS_SELECTOR, ".validation-error")  # TODO: verify selector against live app

    def __init__(self, driver):
        super().__init__(driver)
        self.base_url = "http://192.168.10.124:4001"

    # ── Navigation ────────────────────────────────────────────────────────────

    def navigate_to_login(self):
        """Navigate to the login page."""
        self.driver.get(self.base_url)
        self.wait_for_page_load()

    # ── Actions ───────────────────────────────────────────────────────────────

    def enter_email(self, email):
        """Enter email/username into the email field."""
        self.wait_and_fill(self.EMAIL_INPUT, email)

    def enter_password(self, password):
        """Enter password into the password field."""
        self.wait_and_fill(self.PASSWORD_INPUT, password)

    def click_login_button(self):
        """Click the Login button."""
        self.wait_and_click(self.LOGIN_BUTTON)

    def login_with_credentials(self, email, password):
        """
        Complete login flow with given credentials.
        
        Args:
            email (str): User email/username
            password (str): User password
        """
        self.enter_email(email)
        self.enter_password(password)
        self.click_login_button()
        self.wait_for_page_load()

    def login_as_role(self, role_name):
        """
        Login using credentials from credentials.csv by role name.
        
        Args:
            role_name (str): Role name from credentials CSV (e.g., 'Admin', 'User')
        """
        creds = self.get_login_data_by_role(role_name)
        self.login_with_credentials(creds['username'], creds['password'])

    # ── Assertions ────────────────────────────────────────────────────────────

    def verify_login_page_displayed(self):
        """Verify login page is displayed with all required elements."""
        self.wait_for_element_visible(self.EMAIL_INPUT)
        self.wait_for_element_visible(self.PASSWORD_INPUT)
        self.wait_for_element_visible(self.LOGIN_BUTTON)
        self.wait_for_element_visible(self.REGISTER_LINK)

    def verify_email_field_visible(self):
        """Verify email input field is visible."""
        return self.is_element_visible(self.EMAIL_INPUT)

    def verify_password_field_visible(self):
        """Verify password input field is visible."""
        return self.is_element_visible(self.PASSWORD_INPUT)

    def verify_login_button_visible(self):
        """Verify login button is visible."""
        return self.is_element_visible(self.LOGIN_BUTTON)

    def verify_register_link_visible(self):
        """Verify register hyperlink is visible."""
        return self.is_element_visible(self.REGISTER_LINK)

    def verify_error_message_displayed(self):
        """Verify error message is displayed for invalid credentials."""
        return self.is_element_visible(self.ERROR_MESSAGE)

    def verify_validation_message_displayed(self):
        """Verify validation message is displayed for missing fields."""
        return self.is_element_visible(self.VALIDATION_MESSAGE)

    def get_error_message_text(self):
        """Get the text of the error message."""
        return self.get_element_text(self.ERROR_MESSAGE)

    def verify_login_successful(self):
        """Verify successful login by checking URL change or dashboard element."""
        WebDriverWait(self.driver, 10).until(
            lambda d: "login" not in d.current_url.lower()
        )
        return "login" not in self.driver.current_url.lower()

    def verify_login_failed(self):
        """Verify login failed by checking error message or staying on login page."""
        return self.verify_error_message_displayed() or "login" in self.driver.current_url.lower()
