package pages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * FeedbackPage — Page class for Feedback feature
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java Hybrid
 * Behavioral source: Test inventory cases 1599-1629
 */
public class FeedbackPage extends BasePage {

    // ── Page elements ────────────────────────────────────────────────────────

    @FindBy(css = "input[name='feedback']")
    private WebElement feedbackTextField;

    @FindBy(css = "button[type='submit']")
    private WebElement submitButton;

    @FindBy(css = "button:contains('Cancel')")
    private WebElement cancelButton;

    @FindBy(css = ".success-message")
    private WebElement successMessage;

    @FindBy(css = ".error-message")
    private WebElement errorMessage;

    @FindBy(css = ".validation-error")
    private WebElement validationError;

    @FindBy(css = "label[for='feedback']")
    private WebElement feedbackLabel;

    @FindBy(css = ".required-indicator")
    private WebElement requiredIndicator;

    @FindBy(css = "input[placeholder]")
    private WebElement placeholderField;

    // ── Constructor ──────────────────────────────────────────────────────────

    public FeedbackPage(WebDriver driver) {
        super(driver);
        PageFactory.initElements(driver, this);
    }

    // ── Navigation ───────────────────────────────────────────────────────────

    public void navigateToFeedbackPage() {
        String baseUrl = System.getProperty("BASE_URL", "https://www.saucedemo.com/");
        driver.get(baseUrl);
        waitForPageLoad();
    }

    // ── Actions ──────────────────────────────────────────────────────────────

    public void fillFeedbackField(String feedback) {
        waitAndType(feedbackTextField, feedback);
    }

    public void clickSubmit() {
        waitAndClick(submitButton);
        waitForPageLoad();
    }

    public void clickCancel() {
        waitAndClick(cancelButton);
        waitForPageLoad();
    }

    public void submitFeedbackWithAllRequiredFields(String feedback) {
        fillFeedbackField(feedback);
        clickSubmit();
    }

    public void submitEmptyFeedback() {
        clickSubmit();
    }

    public void fillFeedbackWithMaxLength() {
        String maxLengthText = generateRandomString(255);
        fillFeedbackField(maxLengthText);
    }

    public void fillFeedbackWithExceedingMaxLength() {
        String exceedingText = generateRandomString(300);
        fillFeedbackField(exceedingText);
    }

    public void fillFeedbackWithSpecialCharacters() {
        fillFeedbackField("!@#$%^&*()_+-=[]{}|;':,./<>?");
    }

    public void fillFeedbackWithWhitespaceOnly() {
        fillFeedbackField("     ");
    }

    public void loginAsStandardUser() {
        WebElement usernameField = driver.findElement(org.openqa.selenium.By.cssSelector("input[name='user-name']"));
        WebElement passwordField = driver.findElement(org.openqa.selenium.By.cssSelector("input[name='password']"));
        WebElement loginButton = driver.findElement(org.openqa.selenium.By.cssSelector("button[type='submit']"));
        
        waitAndType(usernameField, "standard_user");
        waitAndType(passwordField, "secret_sauce");
        waitAndClick(loginButton);
        waitForPageLoad();
    }

    // ── Assertions ───────────────────────────────────────────────────────────

    public void verifySuccessMessageDisplayed() {
        waitForVisibility(successMessage);
        assertThat(isElementDisplayed(successMessage))
            .as("Success message should be displayed")
            .isTrue();
    }

    public void verifyValidationErrorDisplayed() {
        waitForVisibility(validationError);
        assertThat(isElementDisplayed(validationError))
            .as("Validation error should be displayed")
            .isTrue();
    }

    public void verifyErrorMessageDisplayed() {
        waitForVisibility(errorMessage);
        assertThat(isElementDisplayed(errorMessage))
            .as("Error message should be displayed")
            .isTrue();
    }

    public void verifyErrorMessageContainsText(String expectedText) {
        waitForVisibility(errorMessage);
        assertThat(getElementText(errorMessage))
            .as("Error message should contain expected text")
            .contains(expectedText);
    }

    public void verifyFeedbackLabelDisplayed() {
        assertThat(isElementDisplayed(feedbackLabel))
            .as("Feedback label should be displayed")
            .isTrue();
    }

    public void verifyRequiredIndicatorDisplayed() {
        assertThat(isElementDisplayed(requiredIndicator))
            .as("Required field indicator should be displayed")
            .isTrue();
    }

    public void verifyPlaceholderPresent() {
        assertThat(placeholderField.getAttribute("placeholder"))
            .as("Placeholder should be present")
            .isNotEmpty();
    }

    public void verifyPageLoaded() {
        waitForPageLoad();
        assertThat(driver.getCurrentUrl())
            .as("Page URL should contain expected fragment")
            .contains("saucedemo.com");
    }

    // ── Helper methods ───────────────────────────────────────────────────────

    private String generateRandomString(int length) {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < length; i++) {
            sb.append(chars.charAt((int) (Math.random() * chars.length())));
        }
        return sb.toString();
    }
}
