package pages;

import base.BasePage;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import static org.assertj.core.api.Assertions.assertThat;
import static pageObjects.LoginPage.*;

/**
 * LoginPage - Actions and assertions
 * Generated by: Qentrix ScriptGenerationAgent
 * Extends BasePage for WebActions helpers
 */
public class LoginPage extends BasePage {

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String baseUrl = System.getenv("BASE_URL") != null 
            ? System.getenv("BASE_URL") 
            : "http://192.168.10.124:4001";
        open(baseUrl);
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterUsername(String username) {
        // Try USERNAME_INPUT first, fallback to EMAIL_INPUT
        if (isElementPresent(By.cssSelector(USERNAME_INPUT))) {
            waitAndFill(By.cssSelector(USERNAME_INPUT), username);
        } else {
            waitAndFill(By.cssSelector(EMAIL_INPUT), username);
        }
    }

    public void enterPassword(String password) {
        waitAndFill(By.cssSelector(PASSWORD_INPUT), password);
    }

    public void clickLoginButton() {
        if (isElementPresent(By.cssSelector(LOGIN_BUTTON))) {
            waitAndClick(By.cssSelector(LOGIN_BUTTON));
        } else {
            waitAndClick(By.xpath(SUBMIT_BUTTON));
        }
        waitForPageLoad();
    }

    public void loginWith(String username, String password) {
        enterUsername(username);
        enterPassword(password);
        clickLoginButton();
    }

    public void submitEmptyForm() {
        clickLoginButton();
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyLoginPageDisplayed() {
        wait(2);
        assertThat(isElementVisible(By.cssSelector(EMAIL_INPUT)))
            .as("Email input should be visible")
            .isTrue();
        assertThat(isElementVisible(By.cssSelector(PASSWORD_INPUT)))
            .as("Password input should be visible")
            .isTrue();
        assertThat(isElementVisible(By.cssSelector(LOGIN_BUTTON)))
            .as("Login button should be visible")
            .isTrue();
    }

    public void verifyLoginSuccess() {
        wait(2);
        String currentUrl = getCurrentUrl();
        assertThat(currentUrl)
            .as("Should navigate away from login page after successful login")
            .doesNotContain("/login");
    }

    public void verifyAuthTokenPresent() {
        wait(2);
        // For API/backend test cases - verify response contains token
        // This assumes token is stored in a hidden field or localStorage
        // Adjust selector based on actual implementation
        assertThat(isElementPresent(By.xpath(AUTH_TOKEN_FIELD)))
            .as("Authentication token should be present")
            .isTrue();
    }

    public void verifyInvalidCredentialsError() {
        wait(2);
        assertThat(isElementVisible(By.xpath(AUTH_ERROR_MESSAGE)))
            .as("Invalid credentials error should be displayed")
            .isTrue();
    }

    public void verifyErrorMessageContains(String expectedText) {
        wait(2);
        String errorText = getElementText(By.cssSelector(ERROR_MESSAGE));
        assertThat(errorText.toLowerCase())
            .as("Error message should contain expected text")
            .contains(expectedText.toLowerCase());
    }

    public void verifyMissingUsernameError() {
        wait(2);
        assertThat(isElementVisible(By.xpath(MISSING_USERNAME_ERROR)))
            .as("Missing username error should be displayed")
            .isTrue();
    }

    public void verifyMissingPasswordError() {
        wait(2);
        assertThat(isElementVisible(By.xpath(MISSING_PASSWORD_ERROR)))
            .as("Missing password error should be displayed")
            .isTrue();
    }

    public void verify401StatusCode() {
        // For API test cases - this would be handled by RestAssured or HTTP client
        // Placeholder for UI equivalent: verify error state indicates 401
        verifyInvalidCredentialsError();
    }

    public void verify400StatusCode() {
        // For API test cases - verify bad request state
        // UI equivalent: verify validation error is shown
        wait(2);
        assertThat(isElementVisible(By.cssSelector(ERROR_MESSAGE)))
            .as("Validation error should be displayed for bad request")
            .isTrue();
    }

    public void verify200StatusCode() {
        // For API test cases - verify success
        // UI equivalent: verify successful navigation
        verifyLoginSuccess();
    }
}
