package pages;

import base.BasePage;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import static org.assertj.core.api.Assertions.assertThat;
import static pageObjects.LoginPage.*;

/**
 * LoginPage.java
 * ─────────────────────────────────────────────────────────────────────────────
 * Page Class: Actions and Assertions | Extends BasePage
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java Hybrid
 * ─────────────────────────────────────────────────────────────────────────────
 */
public class LoginPage extends BasePage {

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigateToLoginPage() {
        String baseUrl = getConfigProperty("base.url", "http://192.168.10.124:4001");
        open(baseUrl + LOGIN_URL_FRAGMENT);
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterUsername(String username) {
        // Try USERNAME_INPUT first, fallback to EMAIL_INPUT
        if (isElementPresent(USERNAME_INPUT)) {
            waitAndFill(USERNAME_INPUT, username);
        } else {
            waitAndFill(EMAIL_INPUT, username);
        }
    }

    public void enterPassword(String password) {
        waitAndFill(PASSWORD_INPUT, password);
    }

    public void clickLoginButton() {
        waitAndClick(LOGIN_BUTTON);
        waitForPageLoad();
    }

    public void loginWithCredentials(String username, String password) {
        enterUsername(username);
        enterPassword(password);
        clickLoginButton();
    }

    /**
     * Login using role from test-data/credentials.csv
     */
    public void loginAs(String roleName) {
        String username = getCredentialByRole(roleName, "Username");
        String password = getCredentialByRole(roleName, "Password");
        loginWithCredentials(username, password);
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyLoginPageLoaded() {
        waitForElementVisible(PAGE_HEADING);
        String currentUrl = getCurrentUrl();
        assertThat(currentUrl).contains(LOGIN_URL_FRAGMENT);
    }

    public void verifyLoginSuccess() {
        waitForPageLoad();
        String currentUrl = getCurrentUrl();
        // After successful login, user should NOT be on login page
        assertThat(currentUrl).doesNotContain(LOGIN_URL_FRAGMENT);
    }

    public void verifyErrorMessageDisplayed() {
        waitForElementVisible(ERROR_MESSAGE);
        assertThat(isElementVisible(ERROR_MESSAGE)).isTrue();
    }

    public void verifyInvalidCredentialsError() {
        verifyErrorMessageDisplayed();
        String errorText = getElementText(ERROR_MESSAGE);
        assertThat(errorText.toLowerCase()).contains("invalid");
    }

    public void verifyMissingUsernameError() {
        verifyErrorMessageDisplayed();
        String errorText = getElementText(ERROR_MESSAGE);
        assertThat(errorText.toLowerCase()).containsAnyOf("username", "required", "missing");
    }

    public void verifyMissingPasswordError() {
        verifyErrorMessageDisplayed();
        String errorText = getElementText(ERROR_MESSAGE);
        assertThat(errorText.toLowerCase()).containsAnyOf("password", "required", "missing");
    }

    public void verifyLoginElementsPresent() {
        waitForElementVisible(PAGE_HEADING);
        assertThat(isElementVisible(EMAIL_INPUT) || isElementVisible(USERNAME_INPUT))
            .as("Email or Username input should be visible")
            .isTrue();
        assertThat(isElementVisible(PASSWORD_INPUT))
            .as("Password input should be visible")
            .isTrue();
        assertThat(isElementVisible(LOGIN_BUTTON))
            .as("Login button should be visible")
            .isTrue();
        assertThat(isElementVisible(REGISTER_LINK))
            .as("Register link should be visible")
            .isTrue();
    }

    public void verifyStaysOnLoginPage() {
        waitForPageLoad();
        String currentUrl = getCurrentUrl();
        assertThat(currentUrl).contains(LOGIN_URL_FRAGMENT);
    }
}
