package pages;

import base.BasePage;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import pageObjects.LoginPageObjects;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * LoginPage - Actions and assertions for login functionality
 * Generated by: ScriptGenerationAgent
 * Framework: Selenium Java BDD
 * Extends: BasePage
 */
public class LoginPage extends BasePage {

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigateToLoginPage() {
        String baseUrl = getConfig("BASE_URL", "http://192.168.10.124:4001");
        open(baseUrl + LoginPageObjects.LOGIN_URL);
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterUsername(String username) {
        waitAndType(By.cssSelector(LoginPageObjects.USERNAME_INPUT), username);
    }

    public void enterEmail(String email) {
        waitAndType(By.cssSelector(LoginPageObjects.EMAIL_INPUT), email);
    }

    public void enterPassword(String password) {
        waitAndType(By.cssSelector(LoginPageObjects.PASSWORD_INPUT), password);
    }

    public void clickLoginButton() {
        waitAndClick(By.cssSelector(LoginPageObjects.LOGIN_BUTTON));
        waitForPageLoad();
    }

    public void submitLoginForm() {
        clickLoginButton();
    }

    public void loginWithCredentials(String username, String password) {
        enterUsername(username);
        enterPassword(password);
        clickLoginButton();
    }

    public void loginAs(String roleName) {
        String[] creds = getLoginDataByRole(roleName);
        loginWithCredentials(creds[0], creds[1]);
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyLoginPageDisplayed() {
        waitForVisibility(By.cssSelector(LoginPageObjects.PAGE_HEADING));
        assertThat(isElementVisible(By.cssSelector(LoginPageObjects.EMAIL_INPUT)))
            .as("Email input should be visible")
            .isTrue();
        assertThat(isElementVisible(By.cssSelector(LoginPageObjects.PASSWORD_INPUT)))
            .as("Password input should be visible")
            .isTrue();
        assertThat(isElementVisible(By.cssSelector(LoginPageObjects.LOGIN_BUTTON)))
            .as("Login button should be visible")
            .isTrue();
    }

    public void verifyLoginPageElements() {
        verifyLoginPageDisplayed();
        assertThat(isElementVisible(By.cssSelector(LoginPageObjects.REGISTER_LINK)))
            .as("Register link should be visible")
            .isTrue();
    }

    public void verifyLoginSuccessful() {
        waitForPageLoad();
        String currentUrl = getCurrentUrl();
        assertThat(currentUrl)
            .as("User should be redirected after successful login")
            .containsAnyOf(LoginPageObjects.DASHBOARD_URL_FRAGMENT, LoginPageObjects.HOME_URL_FRAGMENT);
    }

    public void verifyAuthenticationTokenPresent() {
        waitForPageLoad();
        // Token may be in response body, localStorage, or cookie - checking URL redirect as proxy
        String currentUrl = getCurrentUrl();
        assertThat(currentUrl)
            .as("Authentication should succeed and redirect")
            .doesNotContain(LoginPageObjects.LOGIN_URL);
    }

    public void verifyLoginFailsWithInvalidCredentials() {
        waitForVisibility(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        String errorText = getElementText(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        assertThat(errorText.toLowerCase())
            .as("Error message should indicate invalid credentials")
            .containsAnyOf("invalid", "credentials", "incorrect", "failed");
    }

    public void verifyErrorMessageDisplayed(String expectedMessage) {
        waitForVisibility(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        String errorText = getElementText(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        assertThat(errorText)
            .as("Error message should be displayed")
            .containsIgnoringCase(expectedMessage);
    }

    public void verifyMissingUsernameError() {
        waitForVisibility(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        String errorText = getElementText(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        assertThat(errorText.toLowerCase())
            .as("Error should indicate missing username")
            .containsAnyOf("username", "required", "empty", "missing");
    }

    public void verifyMissingPasswordError() {
        waitForVisibility(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        String errorText = getElementText(By.cssSelector(LoginPageObjects.ERROR_MESSAGE));
        assertThat(errorText.toLowerCase())
            .as("Error should indicate missing password")
            .containsAnyOf("password", "required", "empty", "missing");
    }

    public void verifyResponseStatusCode(int expectedStatusCode) {
        // Note: Selenium cannot directly check HTTP status codes from UI
        // This verification is placeholder for API-level validation
        // Actual status code validation should use RestAssured or network intercept
        waitForPageLoad();
        if (expectedStatusCode == 401 || expectedStatusCode == 400) {
            assertThat(isElementVisible(By.cssSelector(LoginPageObjects.ERROR_MESSAGE)))
                .as("Error message should be visible for status " + expectedStatusCode)
                .isTrue();
        } else if (expectedStatusCode == 200) {
            verifyLoginSuccessful();
        }
    }
}
