package tests;

import base.BaseTest;
import org.junit.jupiter.api.*;
import pages.ForgotPasswordPage;
import io.qameta.allure.*;

/**
 * ForgotPasswordTests.java
 * Generated test cases for Forgot Password feature
 * Framework: selenium-java-hybrid | Generated by: ScriptGenerationAgent
 */
@Epic("Authentication")
@Feature("Forgot Password")
public class ForgotPasswordTests extends BaseTest {

    private ForgotPasswordPage forgotPasswordPage;

    @BeforeEach
    public void setup() {
        super.setup();
        forgotPasswordPage = new ForgotPasswordPage(driver);
    }

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-601")
    @Story("TC-601: Verify that user can reset password successfully")
    @Description("Navigate to forgot password page, enter registered email address, click send reset link button, check email for reset link, click reset link and set new password, verify password is updated")
    @Severity(SeverityLevel.CRITICAL)
    public void TC_601_VerifyUserCanResetPasswordSuccessfully() {
        Allure.step("Navigate to forgot password page", () -> {
            forgotPasswordPage.navigate();
            forgotPasswordPage.verifyForgotPasswordPageLoaded();
        });

        Allure.step("Enter registered email address", () -> {
            String[] creds = forgotPasswordPage.getLoginDataByRole("Admin");
            forgotPasswordPage.enterEmail("admin@test.com");
        });

        Allure.step("Click send reset link button", () -> {
            forgotPasswordPage.clickSendResetLink();
        });

        Allure.step("Verify reset request is submitted", () -> {
            forgotPasswordPage.verifySuccessMessageDisplayed();
        });

        Allure.step("Check email for reset link (simulated)", () -> {
            // Email check would be external verification
        });

        Allure.step("Click reset link and set new password (simulated)", () -> {
            // Reset link navigation would be external flow
        });
    }

    @Test
    @Tag("regression")
    @Tag("TC-602")
    @Story("TC-602: Verify that password reset fails for unregistered email")
    @Description("Navigate to forgot password page, enter unregistered email address, click send reset link button, verify error message appears indicating email not found, verify no reset email is sent")
    @Severity(SeverityLevel.NORMAL)
    public void TC_602_VerifyPasswordResetFailsForUnregisteredEmail() {
        Allure.step("Navigate to forgot password page", () -> {
            forgotPasswordPage.navigate();
            forgotPasswordPage.verifyForgotPasswordPageLoaded();
        });

        Allure.step("Enter unregistered email address", () -> {
            forgotPasswordPage.enterEmail("unregistered" + System.currentTimeMillis() + "@test.com");
        });

        Allure.step("Click send reset link button", () -> {
            forgotPasswordPage.clickSendResetLink();
        });

        Allure.step("Verify error message appears", () -> {
            forgotPasswordPage.verifyEmailNotFoundError();
        });

        Allure.step("Verify error indicates email not found", () -> {
            forgotPasswordPage.verifyEmailNotFoundError();
        });

        Allure.step("Verify no reset email is sent (simulated)", () -> {
            // Email non-receipt would be external verification
        });
    }
}
