package tests;

import base.BaseTest;
import org.junit.jupiter.api.*;
import pages.LoginPage;
import pages.DashboardPage;
import io.qameta.allure.*;

/**
 * LoginTests.java
 * Generated test cases for Login feature
 * Framework: selenium-java-hybrid | Generated by: ScriptGenerationAgent
 */
@Epic("Authentication")
@Feature("Login")
public class LoginTests extends BaseTest {

    private LoginPage loginPage;
    private DashboardPage dashboardPage;

    @BeforeEach
    public void setup() {
        super.setup();
        loginPage = new LoginPage(driver);
        dashboardPage = new DashboardPage(driver);
    }

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-590")
    @Story("TC-590: Verify that user can login with valid credentials")
    @Description("Open login page, enter valid username and password, click login button, verify user logs in successfully and dashboard loads")
    @Severity(SeverityLevel.BLOCKER)
    public void TC_590_VerifyUserCanLoginWithValidCredentials() {
        Allure.step("Open login page", () -> {
            loginPage.navigate();
            loginPage.verifyLoginPageLoaded();
        });

        Allure.step("Enter valid username", () -> {
            String[] creds = loginPage.getLoginDataByRole("Admin");
            loginPage.enterUsername(creds[0]);
        });

        Allure.step("Enter valid password", () -> {
            String[] creds = loginPage.getLoginDataByRole("Admin");
            loginPage.enterPassword(creds[1]);
        });

        Allure.step("Click login button", () -> {
            loginPage.clickLoginButton();
        });

        Allure.step("Verify user logs in successfully and dashboard loads", () -> {
            loginPage.verifyDashboardLoaded();
        });
    }

    @Test
    @Tag("regression")
    @Tag("TC-591")
    @Story("TC-591: Verify that login fails with invalid password")
    @Description("Open login page, enter valid username, enter invalid password, click login button, verify error message displays and user remains on login page")
    @Severity(SeverityLevel.CRITICAL)
    public void TC_591_VerifyLoginFailsWithInvalidPassword() {
        Allure.step("Open login page", () -> {
            loginPage.navigate();
            loginPage.verifyLoginPageLoaded();
        });

        Allure.step("Enter valid username", () -> {
            String[] creds = loginPage.getLoginDataByRole("Admin");
            loginPage.enterUsername(creds[0]);
        });

        Allure.step("Enter invalid password", () -> {
            loginPage.enterPassword("InvalidPassword123!");
        });

        Allure.step("Click login button", () -> {
            loginPage.clickLoginButton();
        });

        Allure.step("Verify error message displays", () -> {
            loginPage.verifyErrorMessageDisplayed();
        });

        Allure.step("Verify user remains on login page", () -> {
            loginPage.verifyUserRemainsOnLoginPage();
        });
    }

    @Test
    @Tag("regression")
    @Tag("TC-592")
    @Story("TC-592: Verify that login handles empty username field")
    @Description("Open login page, leave username field empty, enter valid password, click login button, verify validation error appears with error message indicating username is required")
    @Severity(SeverityLevel.NORMAL)
    public void TC_592_VerifyLoginHandlesEmptyUsernameField() {
        Allure.step("Open login page", () -> {
            loginPage.navigate();
            loginPage.verifyLoginPageLoaded();
        });

        Allure.step("Leave username field empty", () -> {
            // Username field remains blank
        });

        Allure.step("Enter valid password", () -> {
            String[] creds = loginPage.getLoginDataByRole("Admin");
            loginPage.enterPassword(creds[1]);
        });

        Allure.step("Click login button", () -> {
            loginPage.clickLoginButton();
        });

        Allure.step("Verify validation error appears", () -> {
            loginPage.verifyRequiredFieldError();
        });

        Allure.step("Verify error message indicates username is required", () -> {
            loginPage.verifyErrorMessageContains("Required");
        });
    }

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-593")
    @Story("TC-593: Verify that user can logout successfully")
    @Description("Login with valid credentials, navigate to user menu, click logout option, confirm logout action, verify user is logged out and redirected to login page")
    @Severity(SeverityLevel.CRITICAL)
    public void TC_593_VerifyUserCanLogoutSuccessfully() {
        Allure.step("Login with valid credentials", () -> {
            loginPage.navigate();
            loginPage.loginAsRole("Admin");
        });

        Allure.step("Navigate to user menu", () -> {
            dashboardPage.verifyDashboardLoaded();
        });

        Allure.step("Click logout option", () -> {
            dashboardPage.clickLogout();
        });

        Allure.step("Confirm logout action", () -> {
            // Logout confirmation handled by click action
        });

        Allure.step("Verify user is logged out and redirected to login page", () -> {
            loginPage.verifyLoginPageLoaded();
        });
    }

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-614")
    @Story("TC-614: Verify that user can access dashboard after successful login")
    @Description("Navigate to login page, enter valid credentials, click login button, verify redirect to dashboard, verify dashboard elements are visible")
    @Severity(SeverityLevel.BLOCKER)
    public void TC_614_VerifyUserCanAccessDashboardAfterSuccessfulLogin() {
        Allure.step("Navigate to login page", () -> {
            loginPage.navigate();
            loginPage.verifyLoginPageLoaded();
        });

        Allure.step("Enter valid credentials", () -> {
            String[] creds = loginPage.getLoginDataByRole("Admin");
            loginPage.enterUsername(creds[0]);
            loginPage.enterPassword(creds[1]);
        });

        Allure.step("Click login button", () -> {
            loginPage.clickLoginButton();
        });

        Allure.step("Verify redirect to dashboard", () -> {
            dashboardPage.verifyDashboardLoaded();
        });

        Allure.step("Verify dashboard elements are visible", () -> {
            dashboardPage.verifyDashboardElementsVisible();
        });
    }
}
