package pages;

import base.BasePage;
import org.openqa.selenium.WebDriver;
import static org.assertj.core.api.Assertions.*;
import static pageObjects.DashboardPage.*;

/**
 * DashboardPage.java
 * Page actions and assertions for Dashboard feature
 * Generated by: ScriptGenerationAgent | Framework: selenium-java-hybrid
 */
public class DashboardPage extends BasePage {

    public DashboardPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String url = getConfigProperty("BASE_URL", "http://localhost:3000");
        driver.get(url + "/dashboard");
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void clickProfileLink() {
        waitAndClick(USER_PROFILE_LINK);
        waitForPageLoad();
    }

    public void clickLogout() {
        waitAndClick(LOGOUT_BUTTON);
        waitForPageLoad();
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyDashboardLoaded() {
        wait(2);
        assertThat(isElementVisible(PAGE_HEADING))
            .as("Dashboard page heading should be visible")
            .isTrue();
        assertThat(driver.getCurrentUrl())
            .as("URL should contain /dashboard")
            .contains("/dashboard");
    }

    public void verifyDashboardElementsVisible() {
        wait(2);
        assertThat(isElementVisible(DASHBOARD_CONTAINER))
            .as("Dashboard container should be visible")
            .isTrue();
        assertThat(isElementVisible(WELCOME_MESSAGE))
            .as("Welcome message should be visible")
            .isTrue();
    }

    public void verifyWelcomeMessage() {
        wait(2);
        assertThat(isElementVisible(WELCOME_MESSAGE))
            .as("Welcome message should be visible")
            .isTrue();
    }
}
