package pages;

import base.BasePage;
import org.openqa.selenium.WebDriver;
import static org.assertj.core.api.Assertions.*;
import static pageObjects.ForgotPasswordPage.*;

/**
 * ForgotPasswordPage.java
 * Page actions and assertions for Forgot Password feature
 * Generated by: ScriptGenerationAgent | Framework: selenium-java-hybrid
 */
public class ForgotPasswordPage extends BasePage {

    public ForgotPasswordPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String url = getConfigProperty("BASE_URL", "http://localhost:3000");
        driver.get(url + "/forgot-password");
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterEmail(String email) {
        waitAndSendKeys(EMAIL_INPUT, email);
    }

    public void clickSendResetLink() {
        waitAndClick(SEND_RESET_LINK_BUTTON);
        waitForPageLoad();
    }

    public void requestPasswordReset(String email) {
        enterEmail(email);
        clickSendResetLink();
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyForgotPasswordPageLoaded() {
        wait(2);
        assertThat(isElementVisible(PAGE_HEADING))
            .as("Forgot password page heading should be visible")
            .isTrue();
        assertThat(isElementVisible(FORGOT_PASSWORD_FORM))
            .as("Forgot password form should be visible")
            .isTrue();
    }

    public void verifySuccessMessageDisplayed() {
        wait(2);
        assertThat(isElementVisible(SUCCESS_MESSAGE))
            .as("Success message should be visible")
            .isTrue();
    }

    public void verifyErrorMessageDisplayed() {
        wait(2);
        assertThat(isElementVisible(ERROR_MESSAGE))
            .as("Error message should be visible")
            .isTrue();
    }

    public void verifyEmailNotFoundError() {
        wait(2);
        assertThat(isElementVisible(EMAIL_NOT_FOUND_ERROR))
            .as("Email not found error should be visible")
            .isTrue();
    }
}
