package pages;

import base.BasePage;
import org.openqa.selenium.WebDriver;
import static org.assertj.core.api.Assertions.*;
import static pageObjects.LoginPage.*;

/**
 * LoginPage.java
 * Page actions and assertions for Login feature
 * Generated by: ScriptGenerationAgent | Framework: selenium-java-hybrid
 */
public class LoginPage extends BasePage {

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String url = getConfigProperty("BASE_URL", "http://localhost:3000");
        driver.get(url + "/login");
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterUsername(String username) {
        waitAndSendKeys(USERNAME_INPUT, username);
    }

    public void enterEmail(String email) {
        waitAndSendKeys(EMAIL_INPUT, email);
    }

    public void enterPassword(String password) {
        waitAndSendKeys(PASSWORD_INPUT, password);
    }

    public void clickLoginButton() {
        waitAndClick(LOGIN_BUTTON);
        waitForPageLoad();
    }

    public void clickRegisterButton() {
        waitAndClick(REGISTER_BUTTON);
        waitForPageLoad();
    }

    public void clickForgotPasswordLink() {
        waitAndClick(FORGOT_PASSWORD_LINK);
        waitForPageLoad();
    }

    public void loginWithCredentials(String username, String password) {
        enterUsername(username);
        enterPassword(password);
        clickLoginButton();
    }

    public void loginAsRole(String roleName) {
        String[] creds = getLoginDataByRole(roleName);
        loginWithCredentials(creds[0], creds[1]);
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyLoginPageLoaded() {
        wait(2);
        assertThat(isElementVisible(PAGE_HEADING))
            .as("Login page heading should be visible")
            .isTrue();
        assertThat(driver.getCurrentUrl())
            .as("URL should contain /login")
            .contains("/login");
    }

    public void verifyErrorMessageDisplayed() {
        wait(2);
        assertThat(isElementVisible(ERROR_MESSAGE))
            .as("Error message should be visible")
            .isTrue();
    }

    public void verifyErrorMessageContains(String expectedText) {
        wait(2);
        assertThat(getElementText(ERROR_MESSAGE))
            .as("Error message should contain expected text")
            .contains(expectedText);
    }

    public void verifyInvalidCredentialsError() {
        wait(2);
        assertThat(isElementVisible(INVALID_CREDENTIALS_ERROR))
            .as("Invalid credentials error should be visible")
            .isTrue();
    }

    public void verifyRequiredFieldError() {
        wait(2);
        assertThat(isElementVisible(REQUIRED_ERROR))
            .as("Required field error should be visible")
            .isTrue();
    }

    public void verifyDashboardLoaded() {
        wait(2);
        assertThat(isElementVisible(DASHBOARD_INDICATOR))
            .as("Dashboard indicator should be visible after login")
            .isTrue();
        assertThat(driver.getCurrentUrl())
            .as("URL should contain /dashboard")
            .contains("/dashboard");
    }

    public void verifyUserRemainsOnLoginPage() {
        wait(2);
        assertThat(driver.getCurrentUrl())
            .as("User should remain on login page")
            .contains("/login");
        assertThat(isElementVisible(LOGIN_FORM))
            .as("Login form should still be visible")
            .isTrue();
    }
}
