package pages;

import base.BasePage;
import org.openqa.selenium.WebDriver;
import static org.assertj.core.api.Assertions.*;
import static pageObjects.ProfilePage.*;

/**
 * ProfilePage.java
 * Page actions and assertions for Profile feature
 * Generated by: ScriptGenerationAgent | Framework: selenium-java-hybrid
 */
public class ProfilePage extends BasePage {

    public ProfilePage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String url = getConfigProperty("BASE_URL", "http://localhost:3000");
        driver.get(url + "/profile");
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void updateFirstName(String firstName) {
        clearAndSendKeys(FIRST_NAME_INPUT, firstName);
    }

    public void updateEmail(String email) {
        clearAndSendKeys(EMAIL_INPUT, email);
    }

    public void clickSaveChanges() {
        waitAndClick(SAVE_CHANGES_BUTTON);
        waitForPageLoad();
    }

    public void clickChangePassword() {
        waitAndClick(CHANGE_PASSWORD_BUTTON);
        waitForPageLoad();
    }

    public void enterCurrentPassword(String password) {
        waitAndSendKeys(CURRENT_PASSWORD_INPUT, password);
    }

    public void enterNewPassword(String password) {
        waitAndSendKeys(NEW_PASSWORD_INPUT, password);
    }

    public void enterConfirmPassword(String password) {
        waitAndSendKeys(CONFIRM_PASSWORD_INPUT, password);
    }

    public void changePassword(String currentPassword, String newPassword) {
        enterCurrentPassword(currentPassword);
        enterNewPassword(newPassword);
        enterConfirmPassword(newPassword);
        clickSaveChanges();
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyProfilePageLoaded() {
        wait(2);
        assertThat(isElementVisible(PAGE_HEADING))
            .as("Profile page heading should be visible")
            .isTrue();
        assertThat(driver.getCurrentUrl())
            .as("URL should contain /profile")
            .contains("/profile");
    }

    public void verifySuccessMessageDisplayed() {
        wait(2);
        assertThat(isElementVisible(SUCCESS_MESSAGE))
            .as("Success message should be visible")
            .isTrue();
    }

    public void verifyErrorMessageDisplayed() {
        wait(2);
        assertThat(isElementVisible(ERROR_MESSAGE))
            .as("Error message should be visible")
            .isTrue();
    }

    public void verifyInvalidEmailError() {
        wait(2);
        assertThat(isElementVisible(INVALID_EMAIL_ERROR))
            .as("Invalid email error should be visible")
            .isTrue();
    }

    public void verifyIncorrectPasswordError() {
        wait(2);
        assertThat(isElementVisible(INCORRECT_PASSWORD_ERROR))
            .as("Incorrect password error should be visible")
            .isTrue();
    }

    public void verifyUsernameDisplayed(String expectedUsername) {
        wait(2);
        assertThat(getElementText(USERNAME_DISPLAY))
            .as("Username should be displayed")
            .contains(expectedUsername);
    }

    public void verifyEmailDisplayed(String expectedEmail) {
        wait(2);
        assertThat(getElementText(EMAIL_DISPLAY))
            .as("Email should be displayed")
            .contains(expectedEmail);
    }

    public void verifyCreationDateDisplayed() {
        wait(2);
        assertThat(isElementVisible(CREATION_DATE_DISPLAY))
            .as("Account creation date should be visible")
            .isTrue();
    }
}
