// cypress/support/page-objects/loginPage.js
// Auto-generated by Qentrix ScriptGenerationAgent
// Project: AG-Helix | Framework: Cypress + BDD Cucumber
// Purpose: Login page locators - NO logic, NO methods
// ─────────────────────────────────────────────────────────────────────────────

export const loginPageSelectors = {
  // Page structure
  loginPage: '[data-testid="login-page"]', // TODO: verify selector against live app
  emailField: 'input[name="email"]', // TODO: verify selector against live app
  passwordField: 'input[name="password"]', // TODO: verify selector against live app
  loginButton: 'button[type="submit"]', // TODO: verify selector against live app
  registerLink: 'a[href*="register"]', // TODO: verify selector against live app

  // Alternative selectors for different UI implementations
  usernameInput: 'input[placeholder*="Username"]', // TODO: verify selector against live app
  emailInput: 'input[type="email"]', // TODO: verify selector against live app
  passwordInput: 'input[type="password"]', // TODO: verify selector against live app
  submitBtn: 'button:contains("Login")', // TODO: verify selector against live app

  // Feedback messages
  errorMessage: '[role="alert"]', // TODO: verify selector against live app
  authErrorMsg: '.error-message', // TODO: verify selector against live app
  validationError: '.validation-error', // TODO: verify selector against live app
  successMessage: '.success-message', // TODO: verify selector against live app

  // Post-login elements
  dashboardIndicator: '[data-testid="dashboard"]', // TODO: verify selector against live app
  homePageHeading: 'h1:contains("Dashboard")', // TODO: verify selector against live app
  userProfile: '[data-testid="user-profile"]', // TODO: verify selector against live app

  // API endpoints (for reference, not DOM selectors)
  loginEndpoint: '/login'
};

