package pageObjects;

/**
 * LoginPageObjects — Locators for Login feature
 * Generated by Qentrix ScriptGenerationAgent
 * Rules: No imports | No logic | Constants only
 */
public class LoginPageObjects {

    // ── Form inputs ───────────────────────────────────────────────────────────
    public static final String EMAIL_INPUT = "input[type='email']";
    public static final String PASSWORD_INPUT = "input[type='password']";
    public static final String USERNAME_INPUT = "input[name='username']";

    // ── Buttons ───────────────────────────────────────────────────────────────
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String FORGOT_PASSWORD_LINK = "a:has-text('Forgot your password?')";

    // ── Error/Success Messages ────────────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String VALIDATION_ERROR = ".field-error";
    public static final String REQUIRED_FIELD_ERROR = "span:has-text('Required')";
    public static final String INVALID_CREDENTIALS_ERROR = "[role='alert']:has-text('Invalid credentials')";

    // ── Page Elements ─────────────────────────────────────────────────────────
    public static final String LOGIN_PAGE_HEADING = "h1";
    public static final String DASHBOARD_HEADING = "h1:has-text('Dashboard')";

    // ── Session/Token Elements ────────────────────────────────────────────────
    public static final String PROTECTED_RESOURCE = "[data-protected='true']";

    // TODO: verify selector against live app when exploration data is unavailable
    public static final String SESSION_TIMEOUT_REDIRECT = "/login";
}