// cypress/pages/loginPage.ts
// ─────────────────────────────────────────────────────────────────────────────
// Login Page - Actions and Assertions
// Generated by: Qentrix ScriptGenerationAgent | Framework: Cypress TypeScript
// ─────────────────────────────────────────────────────────────────────────────
import {
    loginPageHeading,
    emailInput,
    usernameInput,
    passwordInput,
    loginButton,
    registerLink,
    errorMessage,
    validationMessage,
    authErrorMessage,
    dashboardIndicator,
    userProfileIcon
} from '../pageObjects/loginPage';

class LoginPage {
    // ── Navigation ────────────────────────────────────────────────────────────
    navigate() {
        const baseUrl = Cypress.env('BASE_URL') || 'http://192.168.10.124:4001';
        cy.visit(baseUrl);
        cy.wait(500);
    }

    // ── Actions ───────────────────────────────────────────────────────────────
    fillEmail(email: string) {
        cy.get(emailInput).clear().type(email);
    }

    fillUsername(username: string) {
        cy.get(usernameInput).clear().type(username);
    }

    fillPassword(password: string) {
        cy.get(passwordInput).clear().type(password);
    }

    fillCredentials(username: string, password: string) {
        this.fillUsername(username);
        this.fillPassword(password);
    }

    clickLogin() {
        cy.get(loginButton).click();
        cy.wait(1000);
    }

    clickRegisterLink() {
        cy.get(registerLink).click();
    }

    login(username: string, password: string) {
        this.fillCredentials(username, password);
        this.clickLogin();
    }

    // ── Assertions ────────────────────────────────────────────────────────────
    verifyLoginPageDisplayed() {
        cy.get(emailInput).should('be.visible');
        cy.get(passwordInput).should('be.visible');
        cy.get(loginButton).should('be.visible');
        cy.get(registerLink).should('be.visible');
    }

    verifyLoginPageElements() {
        cy.get(emailInput).should('exist');
        cy.get(passwordInput).should('exist');
        cy.get(loginButton).should('exist');
        cy.get(registerLink).should('exist');
    }

    verifyLoginSuccessful() {
        cy.url().should('include', '/dashboard');
        // Alternative: verify dashboard element or user profile icon
        // cy.get(dashboardIndicator).should('be.visible');
    }

    verifyLoginFailed() {
        cy.get(errorMessage).should('be.visible');
    }

    verifyErrorMessage(expectedMessage: string) {
        cy.get(errorMessage).should('contain.text', expectedMessage);
    }

    verifyAuthErrorMessage() {
        cy.get(authErrorMessage).should('be.visible');
    }

    verifyValidationMessage(expectedMessage: string) {
        cy.get(validationMessage).should('contain.text', expectedMessage);
    }

    verifyInvalidCredentialsError() {
        cy.get(errorMessage).should('be.visible');
        cy.get(errorMessage).should('contain.text', 'invalid');
    }

    verifyEmptyFieldError() {
        cy.get(validationMessage).should('be.visible');
    }

    verifyUsernameAccepted() {
        cy.get(usernameInput).should('have.value');
    }

    verifyPasswordAccepted() {
        cy.get(passwordInput).should('have.value');
    }
}

export default LoginPage;
