package tests;

import base.BaseTest;
import io.qameta.allure.*;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.LoginPage;

/**
 * LoginTest.java
 * Generated by: ScriptGenerationAgent
 * Framework: Selenium Java Hybrid
 * Test Suite: Login functionality
 * Source: Test inventory cases [2, 4, 33, 34, 35, 36, 37, 648-675]
 */
@Epic("Authentication")
@Feature("Login")
public class LoginTest extends BaseTest {

    private LoginPage loginPage;

    @BeforeMethod
    public void setupLoginTest() {
        loginPage = new LoginPage(driver);
    }

    // ══════════════════════════════════════════════════════════════════════════
    // @smoke — Critical path tests
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 1, groups = {"smoke", "regression"})
    @Story("TC-2: Verify that login works with valid credentials")
    @Severity(SeverityLevel.BLOCKER)
    @Description("User should be able to login successfully with valid username and password")
    public void TC_2_VerifyLoginWorksWithValidCredentials() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.loginWithRole("Admin");

        stepLog("Verify user logged in successfully");
        loginPage.verifyLoginSuccessful();
    }

    @Test(priority = 2, groups = {"smoke", "regression"})
    @Story("TC-33: To Test Login Form with Valid Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("System should accept valid username and password and login successfully")
    public void TC_33_TestLoginFormWithValidData() {
        stepLog("Navigate to 192.168.10.124:4001");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter username and password");
        loginPage.loginWithRole("Admin");

        stepLog("System should accept credentials and login");
        loginPage.verifyLoginSuccessful();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // @regression — Negative validation tests
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 3, groups = {"regression"})
    @Story("TC-4: Verify that login fails with invalid password")
    @Severity(SeverityLevel.CRITICAL)
    @Description("User should remain on login page when invalid password is entered")
    public void TC_4_VerifyLoginFailsWithInvalidPassword() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.enterUsername("admin");

        stepLog("Enter invalid password");
        loginPage.enterPassword("wrongPassword123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify error validation displayed and user remains on login page");
        loginPage.verifyInvalidCredentialsError();
        loginPage.verifyUserRemainsOnLoginPage();
    }

    @Test(priority = 4, groups = {"regression"})
    @Story("TC-34/35/36: To Test Login Form with Invalid Data")
    @Severity(SeverityLevel.NORMAL)
    @Description("Login should fail gracefully with invalid credentials")
    public void TC_34_35_36_TestLoginFormWithInvalidData() {
        stepLog("Navigate to login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter invalid username and password");
        loginPage.enterUsername("invalidUser");
        loginPage.enterPassword("invalidPass");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("System should display error and reject login");
        loginPage.verifyInvalidCredentialsError();
        loginPage.verifyUserRemainsOnLoginPage();
    }

    @Test(priority = 5, groups = {"regression"})
    @Story("TC-648: Verify that login fails with invalid username")
    @Severity(SeverityLevel.CRITICAL)
    @Description("Error message should display when invalid username is entered")
    public void TC_648_VerifyLoginFailsWithInvalidUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter invalid username");
        loginPage.enterUsername("nonexistentUser");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify error message and user remains on login page");
        loginPage.verifyInvalidCredentialsError();
        loginPage.verifyUserRemainsOnLoginPage();
    }

    @Test(priority = 6, groups = {"regression"})
    @Story("TC-649: Verify that login fails with empty credentials")
    @Severity(SeverityLevel.CRITICAL)
    @Description("Validation errors should display when both fields are empty")
    public void TC_649_VerifyLoginFailsWithEmptyCredentials() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Leave username and password fields empty");
        // Fields remain empty

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify validation errors display");
        loginPage.verifyUsernameRequiredError();
    }

    @Test(priority = 7, groups = {"regression"})
    @Story("TC-650: Verify that login fails with empty username")
    @Severity(SeverityLevel.NORMAL)
    @Description("Username required error should display")
    public void TC_650_VerifyLoginFailsWithEmptyUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Leave username field empty");
        // Username remains empty

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify username required error displays");
        loginPage.verifyUsernameRequiredError();
    }

    @Test(priority = 8, groups = {"regression"})
    @Story("TC-651: Verify that login fails with empty password")
    @Severity(SeverityLevel.NORMAL)
    @Description("Password required error should display")
    public void TC_651_VerifyLoginFailsWithEmptyPassword() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.enterUsername("admin");

        stepLog("Leave password field empty");
        // Password remains empty

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify password required error displays");
        loginPage.verifyPasswordRequiredError();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Special characters and edge cases
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 9, groups = {"regression"})
    @Story("TC-652: Verify that login works with username containing special characters")
    @Severity(SeverityLevel.NORMAL)
    @Description("System should accept usernames with special characters if valid")
    public void TC_652_VerifyLoginWorksWithSpecialCharactersInUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter username with special characters");
        loginPage.enterUsername("admin@test.com");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify user logged in successfully or error handling appropriate");
        // Behavior depends on app; if special chars allowed in username, login succeeds
        // Otherwise appropriate error
    }

    @Test(priority = 10, groups = {"regression"})
    @Story("TC-653: Verify that login handles maximum length username")
    @Severity(SeverityLevel.MINOR)
    @Description("Login should process maximum length username correctly")
    public void TC_653_VerifyLoginHandlesMaximumLengthUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter maximum length username");
        String maxUsername = "a".repeat(255);
        loginPage.enterUsername(maxUsername);

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button and verify processing");
        loginPage.clickLoginButton();
        // Validation depends on app policy
    }

    @Test(priority = 11, groups = {"regression"})
    @Story("TC-654: Verify that login handles maximum length password")
    @Severity(SeverityLevel.MINOR)
    @Description("Login should process maximum length password correctly")
    public void TC_654_VerifyLoginHandlesMaximumLengthPassword() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.enterUsername("admin");

        stepLog("Enter maximum length password");
        String maxPassword = "P".repeat(255);
        loginPage.enterPassword(maxPassword);

        stepLog("Click login button and verify processing");
        loginPage.clickLoginButton();
        // Validation depends on app policy
    }

    @Test(priority = 12, groups = {"regression"})
    @Story("TC-655: Verify that login fails with SQL injection attempt")
    @Severity(SeverityLevel.BLOCKER)
    @Description("SQL injection should fail safely without exposing database errors")
    public void TC_655_VerifyLoginFailsWithSQLInjection() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter SQL injection string in username");
        loginPage.enterUsername("' OR '1'='1");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify login failed safely and no database error exposed");
        loginPage.verifyInvalidCredentialsError();
        loginPage.verifyUserRemainsOnLoginPage();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Security and password masking
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 13, groups = {"regression"})
    @Story("TC-656: Verify that password field masks input characters")
    @Severity(SeverityLevel.CRITICAL)
    @Description("Password characters should be masked as dots or asterisks")
    public void TC_656_VerifyPasswordFieldMasksInput() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter password in password field");
        loginPage.enterPassword("TestPassword123");

        stepLog("Verify password visibility is masked");
        loginPage.verifyPasswordFieldMasked();

        stepLog("Check page source for password visibility");
        loginPage.verifyPasswordNotVisibleInSource();
    }

    @Test(priority = 14, groups = {"regression"})
    @Story("TC-657: Verify that login implements account lockout after failed attempts")
    @Severity(SeverityLevel.CRITICAL)
    @Description("Account should be locked after exceeding maximum failed login attempts")
    public void TC_657_VerifyAccountLockoutAfterFailedAttempts() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter invalid credentials multiple times");
        for (int i = 0; i < 5; i++) {
            loginPage.enterUsername("admin");
            loginPage.enterPassword("wrongPassword" + i);
            loginPage.clickLoginButton();
            loginPage.navigate(); // Reload login page
        }

        stepLog("Try valid credentials after lockout");
        loginPage.loginWithRole("Admin");

        stepLog("Verify account locked message displayed");
        loginPage.verifyAccountLockedMessage();
    }

    @Test(priority = 15, groups = {"regression"})
    @Story("TC-658: Verify that login works with case sensitive username")
    @Severity(SeverityLevel.NORMAL)
    @Description("Login should succeed when username case matches exactly")
    public void TC_658_VerifyLoginWorksWithCaseSensitiveUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter username with correct case");
        loginPage.enterUsername("admin");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify user logged in successfully");
        loginPage.verifyLoginSuccessful();
    }

    @Test(priority = 16, groups = {"regression"})
    @Story("TC-659: Verify that login fails with incorrect case username")
    @Severity(SeverityLevel.NORMAL)
    @Description("Login should fail when username case does not match")
    public void TC_659_VerifyLoginFailsWithIncorrectCaseUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter username with incorrect case");
        loginPage.enterUsername("ADMIN");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify login failed and error message displayed");
        loginPage.verifyInvalidCredentialsError();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Keyboard navigation and usability
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 17, groups = {"regression"})
    @Story("TC-660: Verify that login form accepts tab navigation")
    @Severity(SeverityLevel.MINOR)
    @Description("User should be able to navigate login form using Tab key")
    public void TC_660_VerifyTabNavigation() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Verify tab navigation between fields");
        loginPage.verifyTabNavigationWorks();
    }

    @Test(priority = 18, groups = {"regression"})
    @Story("TC-661: Verify that login works using Enter key")
    @Severity(SeverityLevel.NORMAL)
    @Description("User should be able to login by pressing Enter key after entering credentials")
    public void TC_661_VerifyLoginWorksUsingEnterKey() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.enterUsername("admin");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Press Enter key");
        loginPage.pressEnterKeyOnPasswordField();

        stepLog("Verify user logged in successfully");
        loginPage.verifyLoginSuccessful();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Password length validation
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 19, groups = {"regression"})
    @Story("TC-671: Verify that login handles minimum length password")
    @Severity(SeverityLevel.NORMAL)
    @Description("Login should process minimum length password according to policy")
    public void TC_671_VerifyLoginHandlesMinimumLengthPassword() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.enterUsername("admin");

        stepLog("Enter minimum length password");
        loginPage.enterPassword("abc"); // Assuming min 3 chars

        stepLog("Click login button and verify processing");
        loginPage.clickLoginButton();
        // Validation depends on app password policy
    }

    @Test(priority = 20, groups = {"regression"})
    @Story("TC-672: Verify that login fails with password below minimum length")
    @Severity(SeverityLevel.NORMAL)
    @Description("Validation error should display for password below minimum length")
    public void TC_672_VerifyLoginFailsWithPasswordBelowMinimumLength() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username");
        loginPage.enterUsername("admin");

        stepLog("Enter password below minimum length");
        loginPage.enterPassword("ab");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify password length error message");
        loginPage.verifyPasswordLengthError();
    }

    @Test(priority = 21, groups = {"regression"})
    @Story("TC-673: Verify that login form clears password field after failed attempt")
    @Severity(SeverityLevel.NORMAL)
    @Description("Password field should be cleared after failed login")
    public void TC_673_VerifyPasswordFieldClearedAfterFailedLogin() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid username and invalid password");
        loginPage.enterUsername("admin");
        loginPage.enterPassword("wrongPassword");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify login failed");
        loginPage.verifyInvalidCredentialsError();

        stepLog("Verify password field is cleared");
        loginPage.verifyPasswordFieldCleared();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Security: HTTPS and session
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 22, groups = {"regression"})
    @Story("TC-674: Verify that login implements HTTPS encryption")
    @Severity(SeverityLevel.BLOCKER)
    @Description("Login page should use HTTPS protocol and encrypt data transmission")
    public void TC_674_VerifyLoginImplementsHTTPS() {
        stepLog("Open login page");
        loginPage.navigate();

        stepLog("Verify URL uses HTTPS protocol");
        loginPage.verifyHttpsProtocol();

        stepLog("Enter credentials and submit form");
        loginPage.loginWithRole("Admin");

        stepLog("Verify data transmission encrypted (HTTPS remains)");
        loginPage.verifyHttpsProtocol();
    }

    @Test(priority = 23, groups = {"regression"})
    @Story("TC-670: Verify that login session expires after inactivity")
    @Severity(SeverityLevel.CRITICAL)
    @Description("User should be redirected to login after session timeout")
    public void TC_670_VerifySessionExpiresAfterInactivity() {
        stepLog("Login with valid credentials");
        loginPage.navigate();
        loginPage.loginWithRole("Admin");
        loginPage.verifyLoginSuccessful();

        stepLog("Remain inactive for session timeout period");
        // Simulate inactivity (app-specific timeout, typically 15-30 min)
        // For test purposes, may need to manipulate session or wait
        // This is a placeholder for session expiry test

        stepLog("Attempt to access protected resource");
        // Navigate to protected page or trigger session check

        stepLog("Verify session expired message and redirect to login");
        loginPage.verifySessionExpiredMessage();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Redirect and account status
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 24, groups = {"regression"})
    @Story("TC-669: Verify that login redirects to intended page after successful authentication")
    @Severity(SeverityLevel.NORMAL)
    @Description("User should reach the originally requested protected page after login")
    public void TC_669_VerifyLoginRedirectsToIntendedPage() {
        stepLog("Navigate to protected page while logged out");
        String protectedUrl = loginPage.getConfigProperty("app.url") + "/dashboard";
        loginPage.open(protectedUrl);

        stepLog("Should redirect to login");
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter valid credentials on login page");
        loginPage.loginWithRole("Admin");

        stepLog("Verify redirect to original intended page");
        loginPage.verifyRedirectToIntendedPage("/dashboard");
    }

    @Test(priority = 25, groups = {"regression"})
    @Story("TC-668: Verify that login fails with deactivated user account")
    @Severity(SeverityLevel.CRITICAL)
    @Description("Login should fail with appropriate error for deactivated accounts")
    public void TC_668_VerifyLoginFailsWithDeactivatedAccount() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter credentials for deactivated account");
        // Assuming a deactivated account exists in test data
        loginPage.enterUsername("deactivatedUser");
        loginPage.enterPassword("deactivatedPass");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify account deactivated message");
        loginPage.verifyAccountLockedMessage();
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Unicode and whitespace handling
    // ══════════════════════════════════════════════════════════════════════════

    @Test(priority = 26, groups = {"regression"})
    @Story("TC-665: Verify that login handles whitespace in username")
    @Severity(SeverityLevel.MINOR)
    @Description("System should handle leading/trailing whitespace appropriately")
    public void TC_665_VerifyLoginHandlesWhitespaceInUsername() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter username with leading/trailing spaces");
        loginPage.enterUsername("  admin  ");

        stepLog("Enter valid password");
        loginPage.enterPassword("admin123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify system handles whitespace appropriately");
        // App may trim whitespace or reject it
    }

    @Test(priority = 27, groups = {"regression"})
    @Story("TC-666: Verify that login handles unicode characters in credentials")
    @Severity(SeverityLevel.MINOR)
    @Description("System should process unicode characters correctly")
    public void TC_666_VerifyLoginHandlesUnicodeCharacters() {
        stepLog("Open login page");
        loginPage.navigate();
        loginPage.verifyLoginPageDisplayed();

        stepLog("Enter username with unicode characters");
        loginPage.enterUsername("用户名");

        stepLog("Enter password with unicode characters");
        loginPage.enterPassword("密码123");

        stepLog("Click login button");
        loginPage.clickLoginButton();

        stepLog("Verify system processes unicode correctly");
        // Validation depends on app support for unicode
    }
}
