import pytest
import allure
from pages.loginPage import LoginPage


@allure.feature('Login')
@allure.suite('Authentication')
class TestLogin:
    """
    Login Test Suite - AG-Helix Application
    Generated by Qentrix ScriptGenerationAgent
    Framework: Selenium + Python + Hybrid
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        """Setup before each test."""
        self.login_page = LoginPage(driver)
        yield

    # ══════════════════════════════════════════════════════════════════════════
    # TC-560: Verify that login works with valid credentials
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-560: Verify that login works with valid credentials")
    @allure.description("Send POST request to /login endpoint with valid username and password, verify 200 status and token")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_login_with_valid_credentials(self):
        """TC-560: Verify that login works with valid credentials @smoke @regression"""
        
        with allure.step("Navigate to login page"):
            self.login_page.navigate_to_login()
        
        with allure.step("Verify login page is displayed with all elements"):
            self.login_page.verify_login_page_displayed()
        
        with allure.step("Enter valid username"):
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_email(creds['username'])
        
        with allure.step("Enter valid password"):
            self.login_page.enter_password(creds['password'])
        
        with allure.step("Click login button"):
            self.login_page.click_login_button()
        
        with allure.step("Verify user logged in successfully"):
            assert self.login_page.verify_login_successful(), "Login should succeed with valid credentials"

    # ══════════════════════════════════════════════════════════════════════════
    # TC-21: Verify that login works with valid credentials (UI Variant)
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-21: Verify that login works with valid credentials (UI Flow)")
    @allure.description("Open login page, enter valid credentials, verify successful login")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_login_valid_credentials_ui_flow(self):
        """TC-21: Verify that login works with valid credentials @smoke @regression"""
        
        with allure.step("Navigate to 192.168.10.124:4001"):
            self.login_page.navigate_to_login()
        
        with allure.step("Verify login page displays Email, Password fields, Login button and Register hyperlink"):
            assert self.login_page.verify_email_field_visible(), "Email field should be visible"
            assert self.login_page.verify_password_field_visible(), "Password field should be visible"
            assert self.login_page.verify_login_button_visible(), "Login button should be visible"
            assert self.login_page.verify_register_link_visible(), "Register link should be visible"
        
        with allure.step("Enter valid username and password"):
            self.login_page.login_as_role('Admin')
        
        with allure.step("Verify successful login"):
            assert self.login_page.verify_login_successful(), "User should be logged in successfully"

    # ══════════════════════════════════════════════════════════════════════════
    # TC-561: Verify that login fails with invalid username
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-561: Verify that login fails with invalid username")
    @allure.description("Send POST request to /login with invalid username, verify 401 status and error message")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_invalid_username(self):
        """TC-561: Verify that login fails with invalid username @regression"""
        
        with allure.step("Navigate to login page"):
            self.login_page.navigate_to_login()
        
        with allure.step("Enter invalid username"):
            self.login_page.enter_email("invalid_user@example.com")
        
        with allure.step("Enter valid password"):
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_password(creds['password'])
        
        with allure.step("Click login button"):
            self.login_page.click_login_button()
        
        with allure.step("Verify login fails with error message indicating invalid credentials"):
            assert self.login_page.verify_login_failed(), "Login should fail with invalid username"
            assert self.login_page.verify_error_message_displayed(), "Error message should be displayed"

    # ══════════════════════════════════════════════════════════════════════════
    # TC-562: Verify that login fails with invalid password
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-562: Verify that login fails with invalid password")
    @allure.description("Send POST request to /login with valid username and invalid password, verify 401 status and error message")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_invalid_password(self):
        """TC-562: Verify that login fails with invalid password @regression"""
        
        with allure.step("Navigate to login page"):
            self.login_page.navigate_to_login()
        
        with allure.step("Enter valid username"):
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_email(creds['username'])
        
        with allure.step("Enter invalid password"):
            self.login_page.enter_password("WrongPassword123!")
        
        with allure.step("Click login button"):
            self.login_page.click_login_button()
        
        with allure.step("Verify login fails with error message indicating invalid credentials"):
            assert self.login_page.verify_login_failed(), "Login should fail with invalid password"
            assert self.login_page.verify_error_message_displayed(), "Error message should be displayed"

    # ══════════════════════════════════════════════════════════════════════════
    # TC-563: Verify that login fails with empty username
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-563: Verify that login fails with empty username")
    @allure.description("Send POST request to /login with empty username field, verify 400 status and error message")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_empty_username(self):
        """TC-563: Verify that login fails with empty username @regression"""
        
        with allure.step("Navigate to login page"):
            self.login_page.navigate_to_login()
        
        with allure.step("Leave username field empty"):
            self.login_page.enter_email("")
        
        with allure.step("Enter valid password"):
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_password(creds['password'])
        
        with allure.step("Click login button"):
            self.login_page.click_login_button()
        
        with allure.step("Verify validation message indicates missing username"):
            assert self.login_page.verify_validation_message_displayed(), "Validation message should indicate missing username"

    # ══════════════════════════════════════════════════════════════════════════
    # TC-564: Verify that login fails with empty password
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-564: Verify that login fails with empty password")
    @allure.description("Send POST request to /login with valid username and empty password field, verify 400 status and error message")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_empty_password(self):
        """TC-564: Verify that login fails with empty password @regression"""
        
        with allure.step("Navigate to login page"):
            self.login_page.navigate_to_login()
        
        with allure.step("Enter valid username"):
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_email(creds['username'])
        
        with allure.step("Leave password field empty"):
            self.login_page.enter_password("")
        
        with allure.step("Click login button"):
            self.login_page.click_login_button()
        
        with allure.step("Verify validation message indicates missing password"):
            assert self.login_page.verify_validation_message_displayed(), "Validation message should indicate missing password"

    # ══════════════════════════════════════════════════════════════════════════
    # TC-22, TC-23, TC-24: Login with Invalid Data (consolidated)
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title("TC-22/23/24: To Test Login Form with Invalid Data")
    @allure.description("Navigate to login page, verify form elements, attempt login with invalid data")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_form_with_invalid_data(self):
        """TC-22/23/24: To Test Login Form with Invalid Data @regression"""
        
        with allure.step("Navigate to 192.168.10.124:4001"):
            self.login_page.navigate_to_login()
        
        with allure.step("Verify system displays Login Page with Email, Password fields, Login button and Register hyperlink"):
            assert self.login_page.verify_email_field_visible(), "Email field should be visible"
            assert self.login_page.verify_password_field_visible(), "Password field should be visible"
            assert self.login_page.verify_login_button_visible(), "Login button should be visible"
            assert self.login_page.verify_register_link_visible(), "Register link should be visible"
        
        with allure.step("Enter invalid username and password"):
            self.login_page.enter_email("invalid_user")
            self.login_page.enter_password("wrongpass")
        
        with allure.step("Click login button"):
            self.login_page.click_login_button()
        
        with allure.step("Verify login fails"):
            assert self.login_page.verify_login_failed(), "Login should fail with invalid credentials"
