# features/login.feature
# ─────────────────────────────────────────────────────────────────────────────
# Login Feature — BDD Scenarios
# Generated by: ScriptGenerationAgent | Framework: WebdriverIO-Cucumber-BDD
# Test Cases: TC-560, TC-561, TC-562, TC-563, TC-564, TC-21, TC-22, TC-23, TC-24, TC-25
# ─────────────────────────────────────────────────────────────────────────────

Feature: Login Authentication

  As a user of the application
  I want to authenticate using login credentials
  So that I can access the application features

  Background:
    Given the user navigates to the login page

  @smoke @regression @TC-560
  Scenario: TC-560 - Verify that login works with valid credentials
    When the user enters valid username
    And the user enters valid password
    And the user submits authentication request
    Then the response should return 200 status code
    And the response should contain authentication token
    And token should be present in response

  @regression @TC-561
  Scenario: TC-561 - Verify that login fails with invalid username
    When the user enters invalid username
    And the user enters valid password
    And the user submits authentication request
    Then the response should return 401 status code
    And the error message should indicate invalid credentials

  @regression @TC-562
  Scenario: TC-562 - Verify that login fails with invalid password
    When the user enters valid username
    And the user enters invalid password
    And the user submits authentication request
    Then the response should return 401 status code
    And the error message should indicate invalid credentials

  @regression @TC-563
  Scenario: TC-563 - Verify that login fails with empty username
    When the user leaves the username field empty
    And the user enters valid password
    And the user submits authentication request
    Then the response should return 400 status code
    And the error message should indicate missing username
    And appropriate error message should be returned

  @regression @TC-564
  Scenario: TC-564 - Verify that login fails with empty password
    When the user enters valid username
    And the user leaves the password field empty
    And the user submits authentication request
    Then the response should return 400 status code
    And the error message should indicate missing password
    And appropriate error message should be returned

  @smoke @regression @TC-21
  Scenario: TC-21 - Verify that login works with valid credentials
    Then the login page should display Email field
    And the login page should display Password field
    And the login page should display Login button
    And the login page should display Register hyperlink
    When the user enters valid username
    And the user enters valid password
    And the user clicks the login button
    Then the user should login successfully

  @regression @TC-22 @TC-23 @TC-24
  Scenario: TC-22/23/24 - Test Login Form with Invalid Data
    Then the login page should be displayed
    When the user enters username "invalidUser"
    And the user enters password "wrongPassword"
    And the user clicks the login button
    Then the user should see an authentication error

  @smoke @TC-25
  Scenario: TC-25 - Test import 01
    Then the login page should be displayed
    When the user enters valid username
    And the user enters valid password
    And the user submits the login form
    Then the username should be accepted
    And the password should be accepted
