package tests;

import org.testng.annotations.Test;
import org.testng.Assert;
import pageObjects.LoginPage;
import pageObjects.PIMPage;

/**
 * Test Case ID: 2297
 * Title: Verify that system prevents XSS attack through employee name fields
 * Description: Generated by Qentrix
 * Priority: Critical
 * QENTRIX_REQUIREMENT_SIGNATURE: c93d8a60f77ea392b25a8f93a93e67faf3c2c9e836133f8c43bdd9f121274639
 */
public class EmployeeXSSSecurityTest extends BaseTest {

    @Test(priority = 1, description = "[2297] Verify that system prevents XSS attack through employee name fields")
    public void testXSSPreventionInEmployeeNameFields() {
        // Step 1: Navigate to url "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
        // Expected: Configured application URL should open
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
        
        // Step 2: Enter username "Admin" and password "admin123"
        // Expected: Configured credentials should be entered successfully
        LoginPage loginPage = new LoginPage(driver);
        loginPage.login("Admin", "admin123");
        
        // Wait for dashboard to load
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        
        // Step 3: Enter script tag payload in First Name field and valid Last Name
        // Expected: XSS payload should be entered
        PIMPage pimPage = new PIMPage(driver);
        pimPage.navigateToPIM();
        pimPage.clickAddEmployee();
        
        String xssPayload = "<script>alert('XSS')</script>";
        pimPage.enterFirstName(xssPayload);
        pimPage.enterLastName("SecurityTest");
        
        // Verify payload is entered
        String enteredValue = pimPage.getFirstNameValue();
        Assert.assertNotNull(enteredValue, "XSS payload should be entered in First Name field");
        
        // Step 4: Click Save and verify employee list display
        // Expected: System should encode or sanitize script tags without executing JavaScript
        pimPage.clickSaveButton();
        
        // Wait for processing
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        
        // Verify that no JavaScript alert was triggered (XSS not executed)
        boolean scriptExecuted = pimPage.isScriptExecuted();
        Assert.assertFalse(scriptExecuted, 
            "System should prevent XSS execution - no JavaScript alert should be triggered");
        
        // Verify that either validation error appears or employee details page loads
        // (both scenarios indicate the script was not executed)
        boolean isErrorDisplayed = pimPage.isRequiredFieldErrorDisplayed();
        boolean isEmployeePageDisplayed = pimPage.isEmployeeListOrDetailsDisplayed();
        
        Assert.assertTrue(isErrorDisplayed || isEmployeePageDisplayed, 
            "System should handle XSS payload safely - either show validation or encode the input");
    }
}