package pageObjects;

/**
 * AccountActivityPage.java
 * Locator constants only — no logic, no methods
 * Generated by: ScriptGenerationAgent | Framework: selenium-java-hybrid
 */
public class AccountActivityPage {

    // ── Page identification ──────────────────────────────────────────────────
    public static final String PAGE_HEADING = "//h1[contains(text(),'Activity')]";
    public static final String ACTIVITY_CONTAINER = "//div[@id='account-activity']";

    // ── Activity table ────────────────────────────────────────────────────────
    public static final String ACTIVITY_TABLE = "//table[@id='activity-table']";
    public static final String ACTIVITY_ROW = "//table[@id='activity-table']//tr";
    public static final String LOGIN_HISTORY = "//div[@class='login-history']";
    public static final String ACTIVITY_TIMESTAMP = "//td[@class='timestamp']";
    public static final String ACTIVITY_DETAILS = "//td[@class='details']";

    // ── Filters ───────────────────────────────────────────────────────────────
    public static final String DATE_FILTER = "//input[@name='dateFilter']";
    public static final String ACTIVITY_TYPE_FILTER = "//select[@name='activityType']";
}
