package com.qentrix.tests;

import com.qentrix.pages.LoginPage;
import com.qentrix.pages.LeavePage;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class LeaveTests extends BaseTest {
    private LoginPage loginPage;
    private LeavePage leavePage;

    @BeforeMethod
    public void setupTest() {
        navigateToApplication();
        loginPage = new LoginPage(driver);
        leavePage = new LeavePage(driver);
    }

    /**
     * Test Case ID: 1000
     * Title: Verify that user can apply for sick leave with half day option
     * Description: Generated by Qentrix
     * QENTRIX_REQUIREMENT_SIGNATURE:c73c8e29ed1a2696a71f477ca21570669e610bbc9e4fe5b9c8a0785684717c74
     * Type: Test Case
     * Priority: High
     */
    @Test(priority = 1, description = "Verify that user can apply for sick leave with half day option")
    public void testApplySickLeaveWithHalfDayOption() {
        // Step 1: Navigate to url - Configured application URL should open
        Assert.assertNotNull(driver.getCurrentUrl(), "Application URL should be loaded");

        // Step 2: Enter username and password - Configured credentials should be entered successfully
        loginPage.login(username, password);
        Assert.assertTrue(loginPage.isDashboardDisplayed(), "User should be logged in successfully");

        // Step 3: Select leave type as Sick Leave, select half day option, enter date and click Submit
        // Half day leave application should be submitted successfully
        leavePage.navigateToLeaveModule();
        leavePage.clickApplyLeave();
        
        LocalDate tomorrow = LocalDate.now().plusDays(1);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String leaveDate = tomorrow.format(formatter);
        
        leavePage.selectLeaveType("CAN - Sick");
        leavePage.enterFromDate(leaveDate);
        leavePage.selectDuration("Half Day");
        leavePage.clickSubmit();
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Step 4: Verify leave request shows 0.5 days in My Leave list
        // Leave request should display 0.5 days deduction
        leavePage.navigateToMyLeave();
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        
        Assert.assertTrue(leavePage.isLeaveRequestDisplayed("0.5") || leavePage.isLeaveRequestDisplayed("0.50"),
            "Leave request should display 0.5 days");
    }

    /**
     * Test Case ID: 1009
     * Title: Verify that user cannot apply leave with to date before from date
     * Description: Generated by Qentrix
     * QENTRIX_REQUIREMENT_SIGNATURE:c73c8e29ed1a2696a71f477ca21570669e610bbc9e4fe5b9c8a0785684717c74
     * Type: Test Case
     * Priority: High
     */
    @Test(priority = 2, description = "Verify that user cannot apply leave with to date before from date")
    public void testCannotApplyLeaveWithInvalidDateRange() {
        // Step 1: Navigate to url - Configured application URL should open
        Assert.assertNotNull(driver.getCurrentUrl(), "Application URL should be loaded");

        // Step 2: Enter username and password - Configured credentials should be entered successfully
        loginPage.login(username, password);
        Assert.assertTrue(loginPage.isDashboardDisplayed(), "User should be logged in successfully");

        // Step 3: Select leave type, enter to date earlier than from date and click Submit
        // Validation error should be displayed
        leavePage.navigateToLeaveModule();
        leavePage.clickApplyLeave();
        
        LocalDate futureDate = LocalDate.now().plusDays(5);
        LocalDate pastDate = LocalDate.now().plusDays(2);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        leavePage.selectLeaveType("CAN - Sick");
        leavePage.enterFromDate(futureDate.format(formatter));
        leavePage.enterToDate(pastDate.format(formatter));
        leavePage.clickSubmit();
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Step 4: Verify form is not submitted - Error message about invalid date range should persist
        Assert.assertTrue(leavePage.isValidationErrorDisplayed() || 
            driver.getCurrentUrl().contains("apply"),
            "Validation error should be displayed and form should not be submitted");
    }

    /**
     * Test Case ID: 1005
     * Title: Verify that user can view leave calendar
     * Description: Generated by Qentrix
     * QENTRIX_REQUIREMENT_SIGNATURE:c73c8e29ed1a2696a71f477ca21570669e610bbc9e4fe5b9c8a0785684717c74
     * Type: Test Case
     * Priority: Medium
     */
    @Test(priority = 3, description = "Verify that user can view leave calendar")
    public void testViewLeaveCalendar() {
        // Step 1: Navigate to url - Configured application URL should open
        Assert.assertNotNull(driver.getCurrentUrl(), "Application URL should be loaded");

        // Step 2: Enter username and password - Configured credentials should be entered successfully
        loginPage.login(username, password);
        Assert.assertTrue(loginPage.isDashboardDisplayed(), "User should be logged in successfully");

        // Step 3: Verify calendar shows all team members leave dates
        // Calendar should display leave dates with color coding
        leavePage.navigateToLeaveModule();
        leavePage.viewLeaveCalendar();
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        
        Assert.assertTrue(leavePage.isCalendarDisplayed(),
            "Calendar should be displayed with leave dates");

        // Step 4: Click on specific date to view leave details
        // Leave details for that date should be displayed
        Assert.assertTrue(leavePage.isLeaveDetailsDisplayed() || leavePage.isCalendarDisplayed(),
            "Leave details or calendar view should be accessible");
    }
}