package base;

import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.*;
import java.time.Duration;

/**
 * BasePage — shared action methods for all page classes.
 * All page classes extend this. Never instantiate directly.
 * Generated by: StaticFrameworks v2.0
 */
public class BasePage {

    protected WebDriver driver;
    protected WebDriverWait wait;
    protected JavascriptExecutor js;
    private static final int DEFAULT_TIMEOUT = 20;

    public BasePage(WebDriver driver) {
        this.driver = driver;
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        this.js = (JavascriptExecutor) driver;
    }

    // ── Navigation ────────────────────────────────────────────────────────────
    public void open(String url) { driver.get(url); }
    public String getUrl() { return driver.getCurrentUrl(); }
    public String getTitle() { return driver.getTitle(); }
    public void refresh() { driver.navigate().refresh(); }

    // ── Element interaction ───────────────────────────────────────────────────
    public void click(By locator) {
        waitForVisible(locator).click();
    }

    public void fill(By locator, String text) {
        WebElement el = waitForVisible(locator);
        el.clear();
        el.sendKeys(text);
    }

    public void clear(By locator) { waitForVisible(locator).clear(); }

    public String getText(By locator) { return waitForVisible(locator).getText().trim(); }

    public String getValue(By locator) {
        return waitForVisible(locator).getAttribute("value");
    }

    public void selectByVisibleText(By locator, String text) {
        new Select(waitForVisible(locator)).selectByVisibleText(text);
    }

    // ── Waits ─────────────────────────────────────────────────────────────────
    public WebElement waitForVisible(By locator) {
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }

    public WebElement waitForClickable(By locator) {
        return wait.until(ExpectedConditions.elementToBeClickable(locator));
    }

    public void waitForUrl(String fragment) {
        wait.until(ExpectedConditions.urlContains(fragment));
    }

    public void waitForPageLoad() {
        wait.until(d -> js.executeScript("return document.readyState").equals("complete"));
    }

    // ── Assertions ────────────────────────────────────────────────────────────
    public boolean isVisible(By locator) {
        try { return driver.findElement(locator).isDisplayed(); }
        catch (NoSuchElementException e) { return false; }
    }

    public boolean isEnabled(By locator) {
        try { return driver.findElement(locator).isEnabled(); }
        catch (NoSuchElementException e) { return false; }
    }

    public int getCount(By locator) {
        return driver.findElements(locator).size();
    }

    // ── JavaScript helpers ────────────────────────────────────────────────────
    public void scrollIntoView(By locator) {
        js.executeScript("arguments[0].scrollIntoView(true);", driver.findElement(locator));
    }

    public void jsClick(By locator) {
        js.executeScript("arguments[0].click();", driver.findElement(locator));
    }
}
