# features/login.feature
# Generated by Qentrix ScriptGenerationAgent
# Framework: Selenium + Python + Behave
# Feature: Login Authentication

Feature: Login Authentication
  As a user
  I want to authenticate with the system
  So that I can access the application

  Background:
    Given the user is on the login page

  @smoke @regression @TC-21
  Scenario: TC-21 Verify that login works with valid credentials
    When the user enters valid username
    And the user enters valid password
    And the user clicks the login button
    Then the user should login successfully

  @smoke @regression @TC-560
  Scenario: TC-560 Verify that login works with valid credentials (API)
    When a POST request is sent to the login endpoint
    And the request includes valid username
    And the request includes valid password
    And the authentication request is submitted
    Then the response should return 200 status code
    And the response should contain authentication token

  @regression @TC-561
  Scenario: TC-561 Verify that login fails with invalid username
    When a POST request is sent to the login endpoint
    And the request includes invalid username
    And the request includes valid password
    And the authentication request is submitted
    Then the response should return 401 status code
    And the error message should indicate invalid credentials

  @regression @TC-562
  Scenario: TC-562 Verify that login fails with invalid password
    When a POST request is sent to the login endpoint
    And the request includes valid username
    And the request includes invalid password
    And the authentication request is submitted
    Then the response should return 401 status code
    And the error message should indicate invalid credentials

  @regression @TC-563
  Scenario: TC-563 Verify that login fails with empty username
    When a POST request is sent to the login endpoint
    And the request includes empty username field
    And the request includes valid password
    And the authentication request is submitted
    Then the response should return 400 status code
    And the error message should indicate missing username

  @regression @TC-564
  Scenario: TC-564 Verify that login fails with empty password
    When a POST request is sent to the login endpoint
    And the request includes valid username
    And the request includes empty password field
    And the authentication request is submitted
    Then the response should return 400 status code
    And the error message should indicate missing password

  @smoke @regression @TC-22
  Scenario: TC-22 To Test Login Form with Invalid Data
    When the user enters username and password
    Then the system should accept the username and password

  @regression @TC-23
  Scenario: TC-23 To Test Login Form with Invalid Data
    # Test case has no steps defined - placeholder scenario

  @regression @TC-24
  Scenario: TC-24 To Test Login Form with Invalid Data
    # Test case has no steps defined - placeholder scenario

  @regression @TC-25
  Scenario: TC-25 test import 01
    # Test case has no steps defined - placeholder scenario
