/**
 * Test Case ID: 1781
 * Title: Verify that API prevents duplicate Employee ID creation
 * Description: Generated by Qentrix
 * Type: Test Case
 * QENTRIX_REQUIREMENT_SIGNATURE: c93d8a60f77ea392b25a8f93a93e67faf3c2c9e836133f8c43bdd9f121274639
 */

const { test, expect } = require('@playwright/test');
const { getConfig } = require('../../config/test-config');
const { getCredentials } = require('../../helpers/credentials-helper');

test.describe('API Employee Duplicate Prevention - TC-1781', () => {
  let apiContext;
  let authToken;
  const config = getConfig();
  const credentials = getCredentials();

  test.beforeAll(async ({ playwright }) => {
    // Create API context
    apiContext = await playwright.request.newContext({
      baseURL: config.BASE_URL,
      extraHTTPHeaders: {
        'Content-Type': 'application/json'
      }
    });
  });

  test.afterAll(async () => {
    await apiContext.dispose();
  });

  test('[1781] Verify that API prevents duplicate Employee ID creation', async ({ page }) => {
    // Step 1: Navigate to url and login
    await test.step('Navigate to application URL', async () => {
      await page.goto(config.BASE_URL + '/web/index.php/auth/login');
      await expect(page).toHaveURL(/.*login/);
    });

    // Step 2: Enter username and password
    await test.step('Enter credentials', async () => {
      await page.fill('input[name="username"]', credentials.username || 'adminhrqa');
      await page.fill('input[name="password"]', credentials.password || 'Adminhrqa@321');
      await page.click('button[type="submit"]');
      await page.waitForLoadState('networkidle');
    });

    // Extract authentication token from session/cookies
    await test.step('Extract authentication token', async () => {
      const cookies = await page.context().cookies();
      const sessionCookie = cookies.find(c => c.name.toLowerCase().includes('session') || c.name.toLowerCase().includes('token'));
      if (sessionCookie) {
        authToken = sessionCookie.value;
      }
      
      // Update API context with auth token
      apiContext = await page.request.newContext({
        baseURL: config.BASE_URL,
        extraHTTPHeaders: {
          'Content-Type': 'application/json',
          'Cookie': cookies.map(c => `${c.name}=${c.value}`).join('; ')
        }
      });
    });

    // Step 3: Send POST request to create first employee with employeeId "EMP011"
    let firstEmployeeResponse;
    await test.step('Create first employee record with Employee ID EMP011', async () => {
      firstEmployeeResponse = await apiContext.post('/web/index.php/api/v2/pim/employees', {
        data: {
          firstName: 'Lisa',
          lastName: 'Anderson',
          employeeId: 'EMP011'
        }
      });
      
      expect(firstEmployeeResponse.ok() || firstEmployeeResponse.status() === 201).toBeTruthy();
      const responseBody = await firstEmployeeResponse.json();
      expect(responseBody).toBeDefined();
    });

    // Step 4: Send another POST request with same employeeId "EMP011"
    let duplicateEmployeeResponse;
    await test.step('Send duplicate Employee ID request', async () => {
      duplicateEmployeeResponse = await apiContext.post('/web/index.php/api/v2/pim/employees', {
        data: {
          firstName: 'Mark',
          lastName: 'Taylor',
          employeeId: 'EMP011'
        }
      });
    });

    // Step 5: Verify API response status code is 409 and contains conflict error message
    await test.step('Verify API rejects duplicate Employee ID with 409 status', async () => {
      expect(duplicateEmployeeResponse.status()).toBe(409);
      
      const responseBody = await duplicateEmployeeResponse.json();
      const responseText = JSON.stringify(responseBody).toLowerCase();
      
      // Verify response contains conflict/duplicate error message
      const hasConflictMessage = responseText.includes('conflict') || 
                                  responseText.includes('duplicate') || 
                                  responseText.includes('already exists') ||
                                  responseText.includes('employee id');
      
      expect(hasConflictMessage).toBeTruthy();
    });
  });
});

