package tests;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import base.BaseTest;
import io.qameta.allure.Description;
import io.qameta.allure.Step;
import pages.LoginPage;

import java.util.Map;

/**
 * LoginTest - Automated test cases for Login functionality
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java POM
 * Test cases: TC-560, TC-561, TC-562, TC-563, TC-564, TC-21, TC-22, TC-23, TC-24, TC-25
 */
@Execution(ExecutionMode.CONCURRENT)
@DisplayName("Login Functionality Tests")
public class LoginTest extends BaseTest {

    private LoginPage loginPage;

    @Override
    public void setUp() {
        super.setUp();
        loginPage = new LoginPage(driver);
    }

    // ── @smoke — Critical path tests ──────────────────────────────────────

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-560")
    @DisplayName("TC-560: Verify that login works with valid credentials @smoke @regression")
    @Description("Send POST request to /login endpoint with valid username and password. Expected: 200 status code and authentication token.")
    public void tc560_verifyLoginWithValidCredentials() {
        navigateToLoginPage();
        
        Map<String, String> credentials = getValidCredentials();
        String username = credentials.get("username");
        String password = credentials.get("password");
        
        enterUsername(username);
        verifyUsernameProcessed();
        
        enterPassword(password);
        verifyPasswordProcessed();
        
        submitAuthenticationRequest();
        
        verifyHttpStatus200();
        verifyAuthTokenPresent();
    }

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-21")
    @DisplayName("TC-21: Verify that login works with valid credentials @smoke @regression")
    @Description("Open login page, enter valid username and password, click login button. Expected: User should login successfully.")
    public void tc21_verifyLoginWithValidCredentials() {
        openLoginPage();
        verifyLoginPageDisplayed();
        
        Map<String, String> credentials = getValidCredentials();
        String username = credentials.get("username");
        String password = credentials.get("password");
        
        enterValidUsername(username);
        verifyUsernameAccepted();
        
        enterValidPassword(password);
        verifyPasswordAccepted();
        
        clickLoginButton();
        verifyLoginSuccessful();
    }

    @Test
    @Tag("smoke")
    @Tag("regression")
    @Tag("TC-22")
    @DisplayName("TC-22: To Test Login Form with Invalid Data @smoke @regression")
    @Description("Navigate to 192.168.10.124:4001, verify Login Page displays with Email, Password fields, Login button and Register Hyperlink. Enter username and password.")
    public void tc22_testLoginFormWithInvalidData() {
        navigateToApplication();
        verifyLoginPageWithAllElements();
        
        Map<String, String> credentials = getInvalidCredentials();
        String username = credentials.get("username");
        String password = credentials.get("password");
        
        enterUsernameAndPassword(username, password);
        verifySystemAcceptsInput();
    }

    // ── @regression — Negative tests ──────────────────────────────────────

    @Test
    @Tag("regression")
    @Tag("TC-561")
    @DisplayName("TC-561: Verify that login fails with invalid username @regression")
    @Description("Send POST request to /login endpoint with invalid username and valid password. Expected: 401 status code and error message.")
    public void tc561_verifyLoginFailsWithInvalidUsername() {
        navigateToLoginPage();
        
        String invalidUsername = "invalid_user_" + System.currentTimeMillis();
        Map<String, String> credentials = getValidCredentials();
        String password = credentials.get("password");
        
        enterUsername(invalidUsername);
        verifyUsernameProcessed();
        
        enterPassword(password);
        verifyPasswordProcessed();
        
        submitAuthenticationRequest();
        
        verifyHttpStatus401();
        verifyInvalidCredentialsError();
    }

    @Test
    @Tag("regression")
    @Tag("TC-562")
    @DisplayName("TC-562: Verify that login fails with invalid password @regression")
    @Description("Send POST request to /login endpoint with valid username and invalid password. Expected: 401 status code and error message.")
    public void tc562_verifyLoginFailsWithInvalidPassword() {
        navigateToLoginPage();
        
        Map<String, String> credentials = getValidCredentials();
        String username = credentials.get("username");
        String invalidPassword = "wrongPassword123!";
        
        enterUsername(username);
        verifyUsernameProcessed();
        
        enterPassword(invalidPassword);
        verifyPasswordProcessed();
        
        submitAuthenticationRequest();
        
        verifyHttpStatus401();
        verifyInvalidCredentialsError();
    }

    @Test
    @Tag("regression")
    @Tag("TC-563")
    @DisplayName("TC-563: Verify that login fails with empty username @regression")
    @Description("Send POST request to /login endpoint with empty username and valid password. Expected: 400 status code and missing username error.")
    public void tc563_verifyLoginFailsWithEmptyUsername() {
        navigateToLoginPage();
        
        Map<String, String> credentials = getValidCredentials();
        String password = credentials.get("password");
        
        enterUsername("");
        verifyEmptyUsernameProcessed();
        
        enterPassword(password);
        verifyPasswordProcessed();
        
        submitAuthenticationRequest();
        
        verifyHttpStatus400();
        verifyMissingUsernameError();
    }

    @Test
    @Tag("regression")
    @Tag("TC-564")
    @DisplayName("TC-564: Verify that login fails with empty password @regression")
    @Description("Send POST request to /login endpoint with valid username and empty password. Expected: 400 status code and missing password error.")
    public void tc564_verifyLoginFailsWithEmptyPassword() {
        navigateToLoginPage();
        
        Map<String, String> credentials = getValidCredentials();
        String username = credentials.get("username");
        
        enterUsername(username);
        verifyUsernameProcessed();
        
        enterPassword("");
        verifyEmptyPasswordProcessed();
        
        submitAuthenticationRequest();
        
        verifyHttpStatus400();
        verifyMissingPasswordError();
    }

    @Test
    @Tag("regression")
    @Tag("TC-23")
    @DisplayName("TC-23: To Test Login Form with Invalid Data @regression")
    @Description("Test login form with invalid data combinations.")
    public void tc23_testLoginFormWithInvalidData() {
        navigateToApplication();
        verifyLoginPageDisplayed();
        
        Map<String, String> credentials = getInvalidCredentials();
        String username = credentials.get("username");
        String password = credentials.get("password");
        
        enterUsernameAndPassword(username, password);
        submitAuthenticationRequest();
        
        verifyLoginFails();
    }

    @Test
    @Tag("regression")
    @Tag("TC-24")
    @DisplayName("TC-24: To Test Login Form with Invalid Data @regression")
    @Description("Additional test for login form with invalid data.")
    public void tc24_testLoginFormWithInvalidData() {
        navigateToApplication();
        verifyLoginPageDisplayed();
        
        Map<String, String> credentials = getInvalidCredentials();
        enterUsernameAndPassword(credentials.get("username"), credentials.get("password"));
        submitAuthenticationRequest();
        
        verifyLoginFails();
    }

    @Test
    @Tag("regression")
    @Tag("TC-25")
    @DisplayName("TC-25: test import 01 @regression")
    @Description("Test import functionality 01.")
    public void tc25_testImport01() {
        navigateToApplication();
        verifyLoginPageDisplayed();
    }

    // ── Test Steps ────────────────────────────────────────────────────────

    @Step("Navigate to login page")
    private void navigateToLoginPage() {
        loginPage.navigate();
    }

    @Step("Open login page")
    private void openLoginPage() {
        loginPage.navigate();
    }

    @Step("Navigate to application")
    private void navigateToApplication() {
        loginPage.navigate();
    }

    @Step("Verify login page is displayed")
    private void verifyLoginPageDisplayed() {
        loginPage.verifyLoginPageDisplayed();
    }

    @Step("Verify Login Page displays with Email, Password fields, Login button and Register Hyperlink")
    private void verifyLoginPageWithAllElements() {
        loginPage.verifyLoginPageDisplayed();
        loginPage.verifyEmailFieldPresent();
        loginPage.verifyPasswordFieldPresent();
        loginPage.verifyLoginButtonPresent();
        loginPage.verifyRegisterLinkPresent();
    }

    @Step("Enter username: {0}")
    private void enterUsername(String username) {
        loginPage.enterUsername(username);
    }

    @Step("Enter valid username: {0}")
    private void enterValidUsername(String username) {
        loginPage.enterUsername(username);
    }

    @Step("Enter password")
    private void enterPassword(String password) {
        loginPage.enterPassword(password);
    }

    @Step("Enter valid password")
    private void enterValidPassword(String password) {
        loginPage.enterPassword(password);
    }

    @Step("Enter username and password")
    private void enterUsernameAndPassword(String username, String password) {
        loginPage.enterUsername(username);
        loginPage.enterPassword(password);
    }

    @Step("Verify username is processed")
    private void verifyUsernameProcessed() {
        loginPage.verifyUsernameAccepted();
    }

    @Step("Verify password is processed")
    private void verifyPasswordProcessed() {
        loginPage.verifyPasswordAccepted();
    }

    @Step("Verify empty username is processed")
    private void verifyEmptyUsernameProcessed() {
        // Empty username processing verification
    }

    @Step("Verify empty password is processed")
    private void verifyEmptyPasswordProcessed() {
        // Empty password processing verification
    }

    @Step("Verify username is accepted")
    private void verifyUsernameAccepted() {
        loginPage.verifyUsernameAccepted();
    }

    @Step("Verify password is accepted")
    private void verifyPasswordAccepted() {
        loginPage.verifyPasswordAccepted();
    }

    @Step("Verify system accepts username and password")
    private void verifySystemAcceptsInput() {
        loginPage.verifyUsernameAccepted();
        loginPage.verifyPasswordAccepted();
    }

    @Step("Click login button")
    private void clickLoginButton() {
        loginPage.clickLoginButton();
    }

    @Step("Submit authentication request")
    private void submitAuthenticationRequest() {
        loginPage.clickLoginButton();
    }

    @Step("Verify user should login successfully")
    private void verifyLoginSuccessful() {
        loginPage.verifyLoginSuccessful();
    }

    @Step("Verify login fails")
    private void verifyLoginFails() {
        loginPage.verifyHttpStatus401();
    }

    @Step("Verify response returns 200 status code")
    private void verifyHttpStatus200() {
        loginPage.verifyHttpStatus200();
    }

    @Step("Verify response returns 401 status code")
    private void verifyHttpStatus401() {
        loginPage.verifyHttpStatus401();
    }

    @Step("Verify response returns 400 status code")
    private void verifyHttpStatus400() {
        loginPage.verifyHttpStatus400();
    }

    @Step("Verify authentication token is present in response")
    private void verifyAuthTokenPresent() {
        loginPage.verifyAuthTokenPresent();
    }

    @Step("Verify error message indicates invalid credentials")
    private void verifyInvalidCredentialsError() {
        loginPage.verifyInvalidCredentialsError();
    }

    @Step("Verify error message indicates missing username")
    private void verifyMissingUsernameError() {
        loginPage.verifyMissingUsernameError();
    }

    @Step("Verify error message indicates missing password")
    private void verifyMissingPasswordError() {
        loginPage.verifyMissingPasswordError();
    }

    // ── Test Data Helpers ─────────────────────────────────────────────────

    private Map<String, String> getValidCredentials() {
        return loginPage.getCredentialsByRole("Admin");
    }

    private Map<String, String> getInvalidCredentials() {
        return Map.of(
            "username", "invalid_user",
            "password", "invalid_pass"
        );
    }
}