package pageobjects;

/**
 * LoginPage - Locators for Login functionality
 * Generated by Qentrix ScriptGenerationAgent
 * RULES: No imports | No logic | No methods | Constants only
 */
public class LoginPage {

    // ── Page URL ──────────────────────────────────────────────────────────────
    public static final String LOGIN_URL = "/login";

    // ── Form inputs ───────────────────────────────────────────────────────────
    public static final String EMAIL_INPUT = "input[name='email']";
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String PASSWORD_INPUT = "input[type='password']";

    // ── Buttons ───────────────────────────────────────────────────────────────
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String REGISTER_LINK = "a:has-text('Register')";

    // ── Validation messages ───────────────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String INVALID_CREDENTIALS_MSG = "text='Invalid credentials'";
    public static final String MISSING_USERNAME_MSG = "text='Username is required'";
    public static final String MISSING_PASSWORD_MSG = "text='Password is required'";

    // ── Post-login verification ───────────────────────────────────────────────
    public static final String DASHBOARD_INDICATOR = "h1";
    public static final String SUCCESS_TOKEN_ELEMENT = "[data-testid='auth-token']";

    // TODO: verify selectors against live app at 192.168.10.124:4001
}
