package pageObjects;

/**
 * LoginPage — Locator constants for Login module
 * Generated by: Qentrix ScriptGenerationAgent
 * Framework: Playwright Java (Hybrid)
 * Rules: No logic, no methods, only locator strings
 */
public class LoginPage {

    // ── Page elements ────────────────────────────────────────────────────────
    public static final String emailInput = "input[name='email'], input[type='email'], input[placeholder*='Email' i], //input[contains(@placeholder, 'Email')], //label[contains(., 'Email')]/following::input[1]";
    public static final String passwordInput = "input[name='password'], input[type='password'], input[placeholder*='Password' i], //input[@type='password'], //label[contains(., 'Password')]/following::input[1]";
    public static final String loginButton = "button[type='submit'], button:has-text('Login'), //button[contains(., 'Login')], //button[@type='submit']";
    public static final String registerLink = "a:has-text('Register'), //a[contains(., 'Register')]";
    public static final String errorMessage = "[role='alert'], .error-message, .alert-danger, //div[contains(@class, 'error')], //*[contains(text(), 'Invalid') or contains(text(), 'invalid')]";
    public static final String successMessage = ".success-message, .alert-success, [role='status'], //div[contains(@class, 'success')]";
    public static final String requiredFieldError = "span:has-text('Required'), .field-error, //span[contains(., 'required') or contains(., 'Required')]";
    public static final String pageHeading = "h1, h2, .page-title";

    // TODO: verify selector against live app — exploration context not provided
}
