// pageObjects/loginPage.js
// ─────────────────────────────────────────────────────────────────────────────
// Generated by: ScriptGenerationAgent | Framework: Cypress JS
// RULES: Named exports ONLY | Zero logic | Zero imports | Zero methods
// ─────────────────────────────────────────────────────────────────────────────

// ── Login page elements ───────────────────────────────────────────────────────
export const emailInput         = 'input[type="email"]';
export const passwordInput      = 'input[type="password"]';
export const loginButton        = 'button:contains("Login")';
export const registerLink       = 'a:contains("Register")';

// ── Validation messages ───────────────────────────────────────────────────────
export const errorMessage       = '[role="alert"]';
export const invalidCredsMsg    = 'text=Invalid credentials';
export const missingUsernameMsg = 'text=Username is required';
export const missingPasswordMsg = 'text=Password is required';

// ── Post-login indicators ─────────────────────────────────────────────────────
export const dashboardHeading   = 'h1';
export const authToken          = 'localStorage.getItem("authToken")';

// ── API endpoint ──────────────────────────────────────────────────────────────
export const loginEndpoint      = '/login';

