package pageObjects;

/**
 * LoginPage - Page Object for Login functionality
 * Contains locators only. No logic, no imports beyond annotations.
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java POM
 */
public class LoginPage {

    // ── Form inputs ───────────────────────────────────────────────────────
    public static final String EMAIL_INPUT = "input[name='email']";
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String PASSWORD_INPUT = "input[type='password']";
    
    // ── Buttons ───────────────────────────────────────────────────────────
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String SUBMIT_BUTTON = "//button[contains(., 'Login')]";
    
    // ── Navigation ────────────────────────────────────────────────────────
    public static final String REGISTER_LINK = "a:has-text('Register')";
    
    // ── Validation / Messages ─────────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String VALIDATION_ERROR = ".error-message";
    public static final String AUTH_ERROR = "//*[contains(text(), 'invalid credentials')]";
    public static final String MISSING_USERNAME_ERROR = "//*[contains(text(), 'missing username')]";
    public static final String MISSING_PASSWORD_ERROR = "//*[contains(text(), 'missing password')]";
    
    // ── Page verification ─────────────────────────────────────────────────
    public static final String LOGIN_PAGE_HEADING = "h1";
    public static final String LOGIN_FORM = "form";
    
    // ── Post-login verification ───────────────────────────────────────────
    public static final String AUTH_TOKEN_ELEMENT = "//*[@data-auth-token]";
    public static final String DASHBOARD_INDICATOR = "//*[contains(@class, 'dashboard')]";
    
    // TODO: verify selectors against live app at 192.168.10.124:4001
}