// cypress/pageObjects/LoginPage.ts
// ─────────────────────────────────────────────────────────────────────────────
// Generated by Qentrix ScriptGenerationAgent
// Feature: Login
// RULES: Named exports ONLY | Zero logic | Zero imports | Zero methods
// ─────────────────────────────────────────────────────────────────────────────

// ── Page elements ─────────────────────────────────────────────────────────────
export const loginPageUrl = '192.168.10.124:4001';
export const emailInput = 'input[name="email"], input[type="email"], input[placeholder*="Email" i], #email';
export const passwordInput = 'input[name="password"], input[type="password"], input[placeholder*="Password" i], #password';
export const loginButton = 'button[type="submit"], button:contains("Login"), button:contains("Sign In")';
export const registerLink = 'a:contains("Register"), a[href*="register"]';

// ── Validation messages ───────────────────────────────────────────────────────
export const errorMessage = '[role="alert"], .error-message, .alert-danger, .invalid-feedback';
export const successMessage = '.success-message, .alert-success';
export const invalidCredentialsError = 'text=/invalid credentials|authentication failed|incorrect/i';

// ── Post-login verification ───────────────────────────────────────────────────
export const dashboardHeading = 'h1, h2, [data-testid="dashboard-title"]';
export const userProfileIcon = '[data-testid="user-profile"], .user-icon, button[aria-label*="profile" i]';

// TODO: verify selectors against live app at 192.168.10.124:4001