// cypress/pageObjects/loginPage.ts
// ─────────────────────────────────────────────────────────────────────────────
// Login Page Object - Locators Only
// Generated by: Qentrix ScriptGenerationAgent | Framework: Cypress TypeScript
// ─────────────────────────────────────────────────────────────────────────────

// ── Page structure ────────────────────────────────────────────────────────────
export const loginPageHeading = 'h1';
export const loginPageSubHeading = 'h2';

// ── Form inputs ───────────────────────────────────────────────────────────────
export const emailInput = 'input[type="email"]';
export const usernameInput = 'input[name="username"]';
export const passwordInput = 'input[type="password"]';

// ── Buttons ───────────────────────────────────────────────────────────────────
export const loginButton = 'button[type="submit"]';
export const registerLink = 'a:contains("Register")';

// ── Validation / error messages ───────────────────────────────────────────────
export const errorMessage = '[role="alert"]';
export const validationMessage = '.validation-message';
export const authErrorMessage = '.auth-error';

// ── Success indicators ────────────────────────────────────────────────────────
export const dashboardIndicator = '[data-testid="dashboard"]';
export const userProfileIcon = '[data-testid="user-profile"]';

// ── UNVERIFIED — update after exploration ─────────────────────────────────────
// These selectors are inferred from test steps and common patterns.
// Verify against live app at 192.168.10.124:4001
// export const specificElement = 'TODO';
