// pageObjects/loginPage.js
// ─────────────────────────────────────────────────────────────────────────────
// Login Page Object — Locator constants only
// Generated by: ScriptGenerationAgent | Framework: WebdriverIO-Cucumber-BDD
// ─────────────────────────────────────────────────────────────────────────────

// ── Page identification ───────────────────────────────────────────────────────
export const loginPageHeading = 'h1';
export const loginForm = 'form#login-form';

// ── Form inputs ───────────────────────────────────────────────────────────────
export const emailInput = 'input[type="email"]';
export const usernameInput = 'input[name="username"]';
export const passwordInput = 'input[type="password"]';

// ── Buttons ───────────────────────────────────────────────────────────────────
export const loginButton = 'button[type="submit"]';
export const registerLink = 'a[href*="register"]';

// ── Validation / error messages ───────────────────────────────────────────────
export const errorMessage = '[role="alert"]';
export const fieldError = '.field-error';
export const invalidCredentialsMessage = '.error-message';
export const emptyUsernameError = 'span:has-text("username")';
export const emptyPasswordError = 'span:has-text("password")';

// ── Post-login verification ───────────────────────────────────────────────────
export const dashboardHeading = 'h1:has-text("Dashboard")';
export const userProfileIcon = '[data-testid="user-profile"]';

