// cypress/e2e/step_definitions/loginSteps.js
// Auto-generated by Qentrix ScriptGenerationAgent
// Project: AG-Helix | Framework: Cypress + BDD Cucumber
// Purpose: Step definitions for Login feature
// ─────────────────────────────────────────────────────────────────────────────

import { Given, When, Then } from '@badeball/cypress-cucumber-preprocessor';
import LoginPage from '../../support/pages/LoginPage.js';

let apiResponse;

// ── Background ────────────────────────────────────────────────────────────────

Given('the user navigates to the login page', () => {
  LoginPage.navigate();
});

// ── UI Steps ──────────────────────────────────────────────────────────────────

Given('the login page displays Email, Password fields, Login button and Register Hyperlink', () => {
  LoginPage.verifyLoginPageLoaded();
});

When('the user enters valid username', () => {
  const username = Cypress.env('TEST_USERNAME') || 'admin';
  LoginPage.enterUsername(username);
});

When('the user enters valid password', () => {
  const password = Cypress.env('TEST_PASSWORD') || 'admin123';
  LoginPage.enterPassword(password);
});

When('the user enters invalid username', () => {
  LoginPage.enterUsername('invalid@example.com');
});

When('the user enters invalid password', () => {
  LoginPage.enterPassword('WrongPassword123');
});

When('the user enters invalid credentials', () => {
  LoginPage.enterInvalidCredentials();
});

When('the user provides incorrect login credentials', () => {
  LoginPage.enterInvalidCredentials();
});

When('the user clicks the login button', () => {
  LoginPage.clickLoginButton();
});

When('the user submits the login form', () => {
  LoginPage.submitLoginForm();
});

When('the user attempts to login', () => {
  LoginPage.clickLoginButton();
});

When('the user attempts authentication', () => {
  LoginPage.enterValidCredentials();
  LoginPage.clickLoginButton();
});

Then('the user should be logged in successfully', () => {
  LoginPage.verifySuccessfulLogin();
});

Then('the user should see the dashboard or home page', () => {
  cy.url().should('match', /\/(dashboard|home)/);
});

Then('the system should display an authentication error message', () => {
  LoginPage.verifyAuthenticationError();
});

Then('the user should remain on the login page', () => {
  LoginPage.verifyRemainsOnLoginPage();
});

Then('the system should reject the authentication', () => {
  LoginPage.verifyAuthenticationError();
  LoginPage.verifyRemainsOnLoginPage();
});

Then('the login should fail with appropriate error', () => {
  LoginPage.verifyAuthenticationError();
});

Then('the system should validate credentials appropriately', () => {
  cy.url().then((url) => {
    if (url.includes('/dashboard') || url.includes('/home')) {
      cy.log('Login succeeded');
    } else {
      LoginPage.verifyAuthenticationError();
    }
  });
});

// ── API Steps ─────────────────────────────────────────────────────────────────

When('a POST request is sent to {string} endpoint with valid username', (endpoint) => {
  const username = Cypress.env('TEST_USERNAME') || 'admin';
  apiResponse = LoginPage.sendLoginRequest({ username, password: '' });
});

When('the request includes valid password in body', () => {
  const username = Cypress.env('TEST_USERNAME') || 'admin';
  const password = Cypress.env('TEST_PASSWORD') || 'admin123';
  apiResponse = LoginPage.sendLoginRequest({ username, password });
});

When('a POST request is sent to {string} endpoint with invalid username', (endpoint) => {
  apiResponse = LoginPage.sendLoginRequest({ username: 'invalid@user.com', password: '' });
});

When('the request includes invalid password in body', () => {
  const username = Cypress.env('TEST_USERNAME') || 'admin';
  apiResponse = LoginPage.sendLoginRequest({ username, password: 'WrongPassword123' });
});

When('a POST request is sent to {string} endpoint with empty username field', (endpoint) => {
  const password = Cypress.env('TEST_PASSWORD') || 'admin123';
  apiResponse = LoginPage.sendLoginRequest({ username: '', password });
});

When('the request includes empty password field in body', () => {
  const username = Cypress.env('TEST_USERNAME') || 'admin';
  apiResponse = LoginPage.sendLoginRequest({ username, password: '' });
});

When('the authentication request is submitted', () => {
  // Request already sent in previous steps, this step confirms submission
  cy.wrap(apiResponse).should('exist');
});

Then('the response should return {int} status code', (statusCode) => {
  cy.wrap(apiResponse).then((response) => {
    LoginPage.verifyResponseStatus(response, statusCode);
  });
});

Then('the response should contain authentication token', () => {
  cy.wrap(apiResponse).then((response) => {
    LoginPage.verifyAuthTokenPresent(response);
  });
});

Then('the error message should indicate invalid credentials', () => {
  cy.wrap(apiResponse).then((response) => {
    LoginPage.verifyErrorMessage(response, 'invalid');
  });
});

Then('the error message should indicate missing username', () => {
  cy.wrap(apiResponse).then((response) => {
    LoginPage.verifyErrorMessage(response, 'username');
  });
});

Then('the error message should indicate missing password', () => {
  cy.wrap(apiResponse).then((response) => {
    LoginPage.verifyErrorMessage(response, 'password');
  });
});

