# page_objects/login_page.py
# ─────────────────────────────────────────────────────────────────────────────
# Login Page Object - Locator constants only
# Generated by: Qentrix ScriptGenerationAgent | Framework: Selenium Python PyTest
# ─────────────────────────────────────────────────────────────────────────────

# ── Login form elements ───────────────────────────────────────────────────────
EMAIL_INPUT = "input[name='email']"
USERNAME_INPUT = "input[name='username']"
PASSWORD_INPUT = "input[type='password']"
LOGIN_BUTTON = "button[type='submit']"
REGISTER_LINK = "a:has-text('Register')"

# ── Page elements ─────────────────────────────────────────────────────────────
PAGE_HEADING = "h1"
LOGIN_FORM = "form"

# ── Validation messages ───────────────────────────────────────────────────────
ERROR_MESSAGE = "[role='alert']"
INVALID_CREDENTIALS_MSG = "text=/invalid credentials/i"
MISSING_USERNAME_MSG = "text=/username.*required/i"
MISSING_PASSWORD_MSG = "text=/password.*required/i"

# ── Post-login elements ───────────────────────────────────────────────────────
DASHBOARD_INDICATOR = "text=/dashboard/i"
WELCOME_MESSAGE = "text=/welcome/i"
LOGOUT_BUTTON = "button:has-text('Logout')"
