// Login Page Class
// Generated by Qentrix

import BasePage from './basePage.js';
import { expect } from '@playwright/test';
import {
    emailInput,
    usernameInput,
    passwordInput,
    loginButton,
    registerLink,
    errorMessage,
    invalidCredentialsMessage,
    missingUsernameMessage,
    missingPasswordMessage,
    dashboardHeading,
    logoutButton
} from '../pageObjects/loginPage.js';

class LoginPage extends BasePage {
    constructor(page) {
        super(page);
    }

    async navigateToLoginPage() {
        await this.open('http://192.168.10.124:4001');
        await this.waitForPageLoad();
    }

    async verifyLoginPageDisplayed() {
        await this.wait();
        const isUsernameVisible = await this.isElementVisible(usernameInput) || await this.isElementVisible(emailInput);
        const isPasswordVisible = await this.isElementVisible(passwordInput);
        const isLoginButtonVisible = await this.isElementVisible(loginButton);
        expect(isUsernameVisible).toBeTruthy();
        expect(isPasswordVisible).toBeTruthy();
        expect(isLoginButtonVisible).toBeTruthy();
    }

    async enterUsername(username) {
        const usernameField = await this.isElementVisible(usernameInput) ? usernameInput : emailInput;
        await this.waitAndFill(usernameField, username);
    }

    async enterPassword(password) {
        await this.waitAndFill(passwordInput, password);
    }

    async clickLoginButton() {
        await this.waitAndClick(loginButton);
        await this.waitforNetworkIdle();
    }

    async login(username, password) {
        await this.enterUsername(username);
        await this.enterPassword(password);
        await this.clickLoginButton();
    }

    async loginWithValidCredentials(roleName = 'Admin') {
        const credentials = this.getLoginDataByRole(roleName);
        await this.login(credentials.username, credentials.password);
    }

    async loginWithInvalidUsername(invalidUsername, validPassword) {
        await this.login(invalidUsername, validPassword);
    }

    async loginWithInvalidPassword(validUsername, invalidPassword) {
        await this.login(validUsername, invalidPassword);
    }

    async loginWithEmptyUsername(password) {
        await this.enterPassword(password);
        await this.clickLoginButton();
    }

    async loginWithEmptyPassword(username) {
        await this.enterUsername(username);
        await this.clickLoginButton();
    }

    async verifyLoginSuccessful() {
        await this.wait();
        const currentUrl = await this.getUrl();
        const isDashboardVisible = await this.isElementVisible(dashboardHeading);
        const isLogoutVisible = await this.isElementVisible(logoutButton);
        expect(currentUrl).not.toContain('login');
        expect(isDashboardVisible || isLogoutVisible).toBeTruthy();
    }

    async verifyInvalidCredentialsError() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(errorMessage);
        expect(isErrorVisible).toBeTruthy();
        const errorText = await this.page.locator(errorMessage).first().textContent();
        expect(errorText.toLowerCase()).toMatch(/invalid|incorrect|credentials|authentication/);
    }

    async verifyMissingUsernameError() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(errorMessage);
        expect(isErrorVisible).toBeTruthy();
        const errorText = await this.page.locator(errorMessage).first().textContent();
        expect(errorText.toLowerCase()).toMatch(/username.*required|username.*missing|required.*username/);
    }

    async verifyMissingPasswordError() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(errorMessage);
        expect(isErrorVisible).toBeTruthy();
        const errorText = await this.page.locator(errorMessage).first().textContent();
        expect(errorText.toLowerCase()).toMatch(/password.*required|password.*missing|required.*password/);
    }

    async verifyRegisterLinkDisplayed() {
        await this.wait();
        const isLinkVisible = await this.isElementVisible(registerLink);
        expect(isLinkVisible).toBeTruthy();
    }
}

export default LoginPage;

