// Profile Page - Actions and Assertions
// Generated by Qentrix for AG-Helix

import BasePage from './basePage.js';
import { expect } from '@playwright/test';
import * as profilePageObjects from '../pageObjects/profilePage.js';

class ProfilePage extends BasePage {
    constructor(page) {
        super(page);
    }

    // Navigation
    async navigateToProfilePage() {
        await this.open((process.env.BASE_URL || '') + '/profile');
        return await this.waitForPageLoad();
    }

    async navigateToProfileSettings() {
        await this.open((process.env.BASE_URL || '') + '/profile/settings');
        return await this.waitForPageLoad();
    }

    async navigateToAccountInfo() {
        await this.open((process.env.BASE_URL || '') + '/account');
        return await this.waitForPageLoad();
    }

    async navigateToAccountActivity() {
        await this.open((process.env.BASE_URL || '') + '/account/activity');
        return await this.waitForPageLoad();
    }

    // Profile Update Actions
    async updateFirstName(firstName) {
        await this.waitAndFill(profilePageObjects.firstNameInput, firstName);
    }

    async updateLastName(lastName) {
        await this.waitAndFill(profilePageObjects.lastNameInput, lastName);
    }

    async updateEmail(email) {
        await this.waitAndFill(profilePageObjects.emailInput, email);
    }

    async clickSaveChanges() {
        await this.waitAndClick(profilePageObjects.saveChangesButton);
        await this.waitforNetworkIdle();
    }

    async updateProfileInformation(firstName, lastName, email) {
        if (firstName) await this.updateFirstName(firstName);
        if (lastName) await this.updateLastName(lastName);
        if (email) await this.updateEmail(email);
        await this.clickSaveChanges();
    }

    // Password Change Actions
    async clickChangePassword() {
        await this.waitAndClick(profilePageObjects.changePasswordLink);
    }

    async enterCurrentPassword(password) {
        await this.waitAndFill(profilePageObjects.currentPasswordInput, password);
    }

    async enterNewPassword(password) {
        await this.waitAndFill(profilePageObjects.newPasswordInput, password);
    }

    async confirmNewPassword(password) {
        await this.waitAndFill(profilePageObjects.confirmPasswordInput, password);
    }

    async clickSavePassword() {
        await this.waitAndClick(profilePageObjects.savePasswordButton);
        await this.waitforNetworkIdle();
    }

    async changePassword(currentPassword, newPassword) {
        await this.clickChangePassword();
        await this.enterCurrentPassword(currentPassword);
        await this.enterNewPassword(newPassword);
        await this.confirmNewPassword(newPassword);
        await this.clickSavePassword();
    }

    // Assertions
    async verifyProfilePageDisplays() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.profileContainer)).toBeVisible();
    }

    async verifySuccessMessage() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.successMessage)).toBeVisible();
    }

    async verifyErrorMessage() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.errorMessage)).toBeVisible();
    }

    async verifyEmailErrorMessage() {
        await this.wait();
        await this.verifyElementContainsText(profilePageObjects.errorMessage, 'email');
    }

    async verifyPasswordChangeFormDisplays() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.currentPasswordInput)).toBeVisible();
    }

    async verifyPasswordErrorMessage() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.passwordErrorMessage)).toBeVisible();
    }

    async verifyPasswordSuccess() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.passwordSuccessMessage)).toBeVisible();
    }

    async verifyUsernameDisplayed(expectedUsername) {
        await this.wait();
        await this.verifyElementContainsText(profilePageObjects.usernameDisplay, expectedUsername);
    }

    async verifyEmailDisplayed(expectedEmail) {
        await this.wait();
        await this.verifyElementContainsText(profilePageObjects.emailDisplay, expectedEmail);
    }

    async verifyAccountCreationDatePresent() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.accountCreationDate)).toBeVisible();
    }

    async verifyLoginHistoryDisplayed() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.loginHistoryList)).toBeVisible();
    }

    async verifyActivityTimestampsAccurate() {
        await this.wait();
        const count = await this.getCount(profilePageObjects.activityTimestamp);
        expect(count).toBeGreaterThan(0);
    }

    async verifyActivityDetailsComplete() {
        await this.wait();
        await expect(this.page.locator(profilePageObjects.activityDetails)).toBeVisible();
    }
}

export default ProfilePage;

