// Registration Page - Actions and Assertions
// Auto-generated by Qentrix

import BasePage from './basePage.js';
import { expect } from '@playwright/test';
import * as registrationPageSelectors from '../pageObjects/registrationPage.js';

class RegistrationPage extends BasePage {
    constructor(page) {
        super(page);
    }

    // Navigation Actions
    async navigateToConfigurationsUrl(url) {
        await this.open(url);
        await this.waitForPageLoad();
    }

    async navigateToApplication() {
        const baseUrl = process.env.BASE_URL || 'http://localhost:3000/configurations';
        await this.open(baseUrl);
        await this.waitForPageLoad();
    }

    // Login Actions
    async enterUsername(username) {
        await this.waitAndFill(registrationPageSelectors.usernameInput, username);
    }

    async enterPassword(password) {
        await this.waitAndFill(registrationPageSelectors.passwordInput, password);
    }

    async enterLoginCredentials(username, password) {
        await this.enterUsername(username);
        await this.enterPassword(password);
    }

    async clickLoginButton() {
        await this.waitAndClick(registrationPageSelectors.loginButton);
        await this.waitforNetworkIdle();
    }

    // Registration Actions
    async enterEmail(email) {
        await this.waitAndFill(registrationPageSelectors.emailInput, email);
    }

    async enterRegisterPassword(password) {
        await this.waitAndFill(registrationPageSelectors.registerPasswordInput, password);
    }

    async clickRegisterButton() {
        await this.waitAndClick(registrationPageSelectors.registerButton);
        await this.waitforNetworkIdle();
    }

    async registerUser(email, password) {
        await this.enterEmail(email);
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    async registerWithEmptyEmail(password) {
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    async registerWithEmptyPassword(email) {
        await this.enterEmail(email);
        await this.clickRegisterButton();
    }

    async registerWithInvalidEmail(invalidEmail, password) {
        await this.enterEmail(invalidEmail);
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    async registerWithSpecialCharactersEmail(email, password) {
        await this.enterEmail(email);
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    async registerWithMaxLengthEmail(email, password) {
        await this.enterEmail(email);
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    async registerWithWeakPassword(email, weakPassword) {
        await this.enterEmail(email);
        await this.enterRegisterPassword(weakPassword);
        await this.clickRegisterButton();
    }

    async registerWithXSSPayload(xssEmail, password) {
        await this.enterEmail(xssEmail);
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    async registerWithSQLInjection(sqlEmail, password) {
        await this.enterEmail(sqlEmail);
        await this.enterRegisterPassword(password);
        await this.clickRegisterButton();
    }

    // Assertion Methods
    async verifyApplicationUrlOpened() {
        await this.wait();
        const currentUrl = await this.getUrl();
        expect(currentUrl).toContain('localhost:3000');
    }

    async verifyCredentialsEntered() {
        await this.wait();
        const isUsernameVisible = await this.isElementVisible(registrationPageSelectors.usernameInput);
        const isPasswordVisible = await this.isElementVisible(registrationPageSelectors.passwordInput);
        expect(isUsernameVisible).toBeTruthy();
        expect(isPasswordVisible).toBeTruthy();
    }

    async verifyValidationErrorDisplayed() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifyEmailRequiredErrorDisplayed() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifyPasswordRequiredErrorDisplayed() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifyEmailInvalidErrorDisplayed() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifyEmailExistsErrorDisplayed() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifyPasswordLengthErrorDisplayed() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifyRegistrationSuccessful() {
        await this.wait();
        const isSuccessVisible = await this.isElementVisible(registrationPageSelectors.successMessage);
        expect(isSuccessVisible).toBeTruthy();
    }

    async verifyConfirmationMessageDisplayed() {
        await this.wait();
        const isConfirmationVisible = await this.isElementVisible(registrationPageSelectors.confirmationMessage);
        expect(isConfirmationVisible).toBeTruthy();
    }

    async verifyInputSanitized() {
        await this.wait();
        const isErrorVisible = await this.isElementVisible(registrationPageSelectors.validationError);
        expect(isErrorVisible).toBeTruthy();
    }

    async verifySystemValidatesInput() {
        await this.wait();
        const currentUrl = await this.getUrl();
        expect(currentUrl).toBeDefined();
    }
}

export default RegistrationPage;

