// pages/saucedemoPage.js
// ─────────────────────────────────────────────────────────────────────────────
// Saucedemo Page Class — Actions and Assertions
// Generated by: ScriptGenerationAgent | Framework: StaticFrameworks
// ─────────────────────────────────────────────────────────────────────────────
import BasePage from './basePage.js';
import { expect } from '@playwright/test';
import {
    usernameInput,
    passwordInput,
    loginButton,
    loginErrorMessage,
    inventoryContainer,
    inventoryItem,
    inventoryItemName,
    inventoryItemDescription,
    inventoryItemPrice,
    inventoryItemImage,
    addToCartButton,
    removeFromCartButton,
    shoppingCartBadge,
    shoppingCartLink,
    productSortDropdown,
    productDetailContainer,
    productDetailName,
    productDetailDescription,
    productDetailPrice,
    productDetailImage,
    backToProductsButton,
    addToCartButtonDetail,
    removeFromCartButtonDetail,
    cartItem,
    cartItemName,
    cartItemPrice,
    continueShoppingButton,
    checkoutButton,
    firstNameInput,
    lastNameInput,
    postalCodeInput,
    continueButton,
    cancelButton,
    checkoutErrorMessage,
    checkoutSummaryContainer,
    summaryItemName,
    finishButton,
    checkoutCompleteContainer,
    completeHeader,
    completeText,
    backHomeButton,
    hamburgerMenuButton,
    menuSidebar,
    logoutLink,
} from '../pageObjects/saucedemoPage.js';

class SaucedemoPage extends BasePage {
    constructor(page) {
        super(page);
    }

    // ── Navigation ────────────────────────────────────────────────────────────
    async navigate() {
        const url = process.env.BASE_URL || this.testData.baseUrl || 'https://www.saucedemo.com/';
        await this.open(url);
        return await super.waitForPageLoad();
    }

    // ── Login Actions ─────────────────────────────────────────────────────────
    async login(username, password) {
        await this.waitAndFill(usernameInput, username);
        await this.waitAndFill(passwordInput, password);
        await this.waitAndClick(loginButton);
        return await super.waitForPageLoad();
    }

    async loginWithStandardUser() {
        await this.login('standard_user', 'secret_sauce');
    }

    async loginWithLockedUser() {
        await this.login('locked_out_user', 'secret_sauce');
    }

    async loginWithInvalidCredentials() {
        await this.login('invalid_user', 'wrong_password');
    }

    async loginWithSQLInjection() {
        await this.login("' OR '1'='1", "' OR '1'='1");
    }

    async clickLoginWithoutCredentials() {
        await this.waitAndClick(loginButton);
        return await super.waitForPageLoad();
    }

    // ── Logout Actions ────────────────────────────────────────────────────────
    async logout() {
        await this.waitAndClick(hamburgerMenuButton);
        await this.wait();
        await this.waitAndClick(logoutLink);
        return await super.waitForPageLoad();
    }

    // ── Product Actions ───────────────────────────────────────────────────────
    async clickFirstProduct() {
        await this.waitAndClick(`${inventoryItemName}:first-of-type`);
        return await super.waitForPageLoad();
    }

    async addFirstProductToCart() {
        await this.waitAndClick(`${addToCartButton}:first-of-type`);
        await this.wait();
    }

    async removeFirstProductFromCart() {
        await this.waitAndClick(`${removeFromCartButton}:first-of-type`);
        await this.wait();
    }

    async clickBackToProducts() {
        await this.waitAndClick(backToProductsButton);
        return await super.waitForPageLoad();
    }

    async sortProductsByPriceLowToHigh() {
        await this.selectDropdownOption(productSortDropdown, 'lohi');
        await this.wait();
    }

    // ── Cart Actions ──────────────────────────────────────────────────────────
    async openCart() {
        await this.waitAndClick(shoppingCartLink);
        return await super.waitForPageLoad();
    }

    async proceedToCheckout() {
        await this.waitAndClick(checkoutButton);
        return await super.waitForPageLoad();
    }

    // ── Checkout Actions ──────────────────────────────────────────────────────
    async fillCheckoutInformation(firstName, lastName, postalCode) {
        if (firstName) await this.waitAndFill(firstNameInput, firstName);
        if (lastName) await this.waitAndFill(lastNameInput, lastName);
        if (postalCode) await this.waitAndFill(postalCodeInput, postalCode);
    }

    async fillCheckoutWithXSSPayload() {
        await this.fillCheckoutInformation(
            '<script>alert("XSS")</script>',
            '<script>alert("XSS")</script>',
            '<script>alert("XSS")</script>'
        );
    }

    async clickContinueCheckout() {
        await this.waitAndClick(continueButton);
        return await super.waitForPageLoad();
    }

    async clickFinishCheckout() {
        await this.waitAndClick(finishButton);
        return await super.waitForPageLoad();
    }

    async completeCheckoutWithValidInfo() {
        await this.fillCheckoutInformation('John', 'Doe', '12345');
        await this.clickContinueCheckout();
        await this.clickFinishCheckout();
    }

    // ── Assertions ────────────────────────────────────────────────────────────
    async verifyLoginPageDisplayed() {
        await this.wait();
        await this.isElementVisible(usernameInput, this.testData.notVisibleText);
        await this.isElementVisible(passwordInput, this.testData.notVisibleText);
        await this.isElementVisible(loginButton, this.testData.notVisibleText);
    }

    async verifyProductsPageDisplayed() {
        await this.wait();
        await this.isElementVisible(inventoryContainer, this.testData.notVisibleText);
        const url = await this.getUrl();
        expect(url).toContain('/inventory.html');
    }

    async verifyLoginErrorDisplayed() {
        await this.wait();
        await this.isElementVisible(loginErrorMessage, this.testData.notVisibleText);
    }

    async verifyLockedOutErrorDisplayed() {
        await this.wait();
        await this.verifyElementContainsText(loginErrorMessage, 'locked out');
    }

    async verifyProductDetailPageDisplayed() {
        await this.wait();
        await this.isElementVisible(productDetailContainer, this.testData.notVisibleText);
        await this.isElementVisible(productDetailName, this.testData.notVisibleText);
        await this.isElementVisible(productDetailDescription, this.testData.notVisibleText);
        await this.isElementVisible(productDetailPrice, this.testData.notVisibleText);
        await this.isElementVisible(productDetailImage, this.testData.notVisibleText);
        await this.isElementVisible(backToProductsButton, this.testData.notVisibleText);
    }

    async verifyCartBadgeDisplaysCount(expectedCount) {
        await this.wait();
        if (expectedCount === 0) {
            const isVisible = await this.page.locator(shoppingCartBadge).isVisible().catch(() => false);
            expect(isVisible).toBe(false);
        } else {
            await this.verifyElementText(shoppingCartBadge, expectedCount.toString());
        }
    }

    async verifyRemoveButtonDisplayed() {
        await this.wait();
        await this.isElementVisible(removeFromCartButton, this.testData.notVisibleText);
    }

    async verifyAddToCartButtonDisplayed() {
        await this.wait();
        await this.isElementVisible(addToCartButton, this.testData.notVisibleText);
    }

    async verifyProductsSortedByPriceLowToHigh() {
        await this.wait();
        const prices = await this.page.locator(inventoryItemPrice).allTextContents();
        const numericPrices = prices.map(p => parseFloat(p.replace('$', '')));
        for (let i = 0; i < numericPrices.length - 1; i++) {
            expect(numericPrices[i]).toBeLessThanOrEqual(numericPrices[i + 1]);
        }
    }

    async verifyCheckoutErrorDisplayed() {
        await this.wait();
        await this.isElementVisible(checkoutErrorMessage, this.testData.notVisibleText);
    }

    async verifyFirstNameRequiredError() {
        await this.wait();
        await this.verifyElementContainsText(checkoutErrorMessage, 'First Name is required');
    }

    async verifyOrderConfirmationDisplayed() {
        await this.wait();
        await this.isElementVisible(checkoutCompleteContainer, this.testData.notVisibleText);
        await this.verifyElementContainsText(completeHeader, 'Thank you');
    }

    async verifyRedirectedToLogin() {
        await this.wait();
        const url = await this.getUrl();
        expect(url).toContain('saucedemo.com');
        expect(url).not.toContain('/inventory.html');
        await this.verifyLoginPageDisplayed();
    }

    async verifyPasswordFieldMasked() {
        await this.wait();
        const inputType = await this.page.locator(passwordInput).getAttribute('type');
        expect(inputType).toBe('password');
    }

    async verifyNoSensitiveDataInConsoleOrNetwork() {
        await this.wait();
        // This is a placeholder assertion; actual implementation would require DevTools protocol
        // For now, we verify that login succeeds without exposing plaintext password in DOM
        const passwordValue = await this.page.locator(passwordInput).inputValue();
        expect(passwordValue).toBe('');
    }

    async verifyXSSInputSanitized() {
        await this.wait();
        const firstNameValue = await this.page.locator(firstNameInput).inputValue();
        // Verify script tags are not executed or visible as-is
        expect(firstNameValue).not.toContain('<script>');
    }

    // ── Performance / Load Testing Helpers ────────────────────────────────────
    async measurePageLoadTime() {
        const navigationTiming = await this.page.evaluate(() =>
            JSON.stringify(window.performance.timing)
        );
        const timing = JSON.parse(navigationTiming);
        const loadTime = timing.loadEventEnd - timing.navigationStart;
        return loadTime;
    }

    async verifyPageLoadsWithinThreshold(maxMilliseconds) {
        const loadTime = await this.measurePageLoadTime();
        expect(loadTime).toBeLessThan(maxMilliseconds);
    }

    async verifyProductsPageLoadsWithin2Seconds() {
        await this.verifyPageLoadsWithinThreshold(2000);
    }

    async verifyLoginPageLoadsWithin3Seconds() {
        await this.verifyPageLoadsWithinThreshold(3000);
    }
}

export default SaucedemoPage;

