# tests/test_login.py
# ─────────────────────────────────────────────────────────────────────────────
# Login Feature Test Suite
# Generated by: ScriptGenerationAgent | Framework: Playwright Python
# Test Cases: TC-562, TC-22, TC-24, TC-25, TC-21, TC-23, TC-561, TC-563, TC-560, TC-564
# ─────────────────────────────────────────────────────────────────────────────
import pytest
from pages.login_page import LoginPage


class TestLogin:
    """Login feature test suite covering positive, negative, and edge cases"""

    @pytest.fixture(autouse=True)
    def setup(self, page):
        """Setup login page instance before each test"""
        self.login_page = LoginPage(page)
        yield

    # ── @smoke — Critical path tests ──────────────────────────────────────────

    @pytest.mark.smoke
    @pytest.mark.regression
    def test_tc_21_verify_login_works_with_valid_credentials(self, page):
        """TC-21: Verify that login works with valid credentials @smoke @regression"""
        with page.context.tracing.start():
            # Step 1: Open login page
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()

            # Step 2: Enter valid username
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_username(creds['username'])

            # Step 3: Enter valid password
            self.login_page.enter_password(creds['password'])

            # Step 4: Click login button
            self.login_page.click_login_button()

            # Step 5: Verify user logged in successfully
            self.login_page.verify_login_success()

    @pytest.mark.smoke
    @pytest.mark.regression
    def test_tc_560_verify_api_login_works_with_valid_credentials(self, page):
        """TC-560: Verify that login works with valid credentials (API) @smoke @regression"""
        with page.context.tracing.start():
            # Step 1: Send POST request to /login endpoint
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.navigate()

            # Step 2: Include valid username in request body
            self.login_page.enter_username(creds['username'])

            # Step 3: Include valid password in request body
            self.login_page.enter_password(creds['password'])

            # Step 4: Submit authentication request
            self.login_page.click_login_button()

            # Step 5: Validate response returns 200 status code
            self.login_page.verify_response_status_200()

            # Step 6: Validate response contains authentication token
            self.login_page.verify_authentication_token_present()

    @pytest.mark.smoke
    @pytest.mark.regression
    def test_tc_22_test_login_form_with_invalid_data(self, page):
        """TC-22: To Test Login Form with Invalid Data @smoke @regression"""
        with page.context.tracing.start():
            # Step 1: Navigate to login page
            self.login_page.navigate()

            # Step 2: Verify login page displays with all elements
            self.login_page.verify_login_page_loaded()

            # Step 3: Enter username and password (invalid)
            self.login_page.enter_username('invalid_user')
            self.login_page.enter_password('invalid_pass')

            # Step 4: Submit login
            self.login_page.click_login_button()

            # Step 5: Verify error is shown
            self.login_page.verify_invalid_credentials_error()

    # ── @regression — Negative tests ──────────────────────────────────────────

    @pytest.mark.regression
    def test_tc_561_verify_login_fails_with_invalid_username(self, page):
        """TC-561: Verify that login fails with invalid username @regression"""
        with page.context.tracing.start():
            # Step 1: Send POST request to /login endpoint
            self.login_page.navigate()

            # Step 2: Include invalid username in request body
            self.login_page.enter_username('invalid_username')

            # Step 3: Include valid password in request body
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_password(creds['password'])

            # Step 4: Submit authentication request
            self.login_page.click_login_button()

            # Step 5: Validate response returns 401 status code
            self.login_page.verify_response_status_401()

            # Step 6: Validate error message indicates invalid credentials
            self.login_page.verify_invalid_credentials_error()

    @pytest.mark.regression
    def test_tc_562_verify_login_fails_with_invalid_password(self, page):
        """TC-562: Verify that login fails with invalid password @regression"""
        with page.context.tracing.start():
            # Step 1: Send POST request to /login endpoint
            self.login_page.navigate()

            # Step 2: Include valid username in request body
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_username(creds['username'])

            # Step 3: Include invalid password in request body
            self.login_page.enter_password('invalid_password_123')

            # Step 4: Submit authentication request
            self.login_page.click_login_button()

            # Step 5: Validate response returns 401 status code
            self.login_page.verify_response_status_401()

            # Step 6: Validate error message indicates invalid credentials
            self.login_page.verify_invalid_credentials_error()

    @pytest.mark.regression
    def test_tc_563_verify_login_fails_with_empty_username(self, page):
        """TC-563: Verify that login fails with empty username @regression"""
        with page.context.tracing.start():
            # Step 1: Send POST request to /login endpoint
            self.login_page.navigate()

            # Step 2: Include empty username field in request body
            self.login_page.enter_username('')

            # Step 3: Include valid password in request body
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_password(creds['password'])

            # Step 4: Submit authentication request
            self.login_page.click_login_button()

            # Step 5: Validate response returns 400 status code
            self.login_page.verify_response_status_400()

            # Step 6: Validate error message indicates missing username
            self.login_page.verify_missing_username_error()

    @pytest.mark.regression
    def test_tc_564_verify_login_fails_with_empty_password(self, page):
        """TC-564: TC_Verify that login fails with empty password @regression"""
        with page.context.tracing.start():
            # Step 1: Send POST request to /login endpoint
            self.login_page.navigate()

            # Step 2: Include valid username in request body
            creds = self.login_page.get_login_data_by_role('Admin')
            self.login_page.enter_username(creds['username'])

            # Step 3: Include empty password field in request body
            self.login_page.enter_password('')

            # Step 4: Submit authentication request
            self.login_page.click_login_button()

            # Step 5: Validate response returns 400 status code
            self.login_page.verify_response_status_400()

            # Step 6: Validate error message indicates missing password
            self.login_page.verify_missing_password_error()

    @pytest.mark.regression
    def test_tc_23_test_login_form_with_invalid_data_variant(self, page):
        """TC-23: To Test Login Form with Invalid Data (variant) @regression"""
        with page.context.tracing.start():
            # Navigate and attempt login with invalid data
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()
            self.login_page.enter_username('test_invalid')
            self.login_page.enter_password('wrong_password')
            self.login_page.click_login_button()
            self.login_page.verify_invalid_credentials_error()

    @pytest.mark.regression
    def test_tc_24_test_login_form_with_invalid_data_no_steps(self, page):
        """TC-24: To Test Login Form with Invalid Data (no detailed steps) @regression"""
        with page.context.tracing.start():
            # Basic invalid login flow
            self.login_page.navigate()
            self.login_page.submit_login('bad_user', 'bad_pass')
            self.login_page.verify_invalid_credentials_error()

    @pytest.mark.regression
    def test_tc_25_test_import_01(self, page):
        """TC-25: test import 01 @regression"""
        with page.context.tracing.start():
            # Placeholder test - no steps provided
            # Execute basic login validation
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()
