# tests/test_login.py
# ─────────────────────────────────────────────────────────────────────────────
# Login Feature Test Suite
# Generated by: Qentrix ScriptGenerationAgent | Framework: Selenium Python PyTest
# Test Cases: TC-560, TC-561, TC-562, TC-563, TC-564, TC-21, TC-22, TC-23, TC-24, TC-25
# ─────────────────────────────────────────────────────────────────────────────
import pytest
import allure
from pages.login_page import LoginPage


@allure.feature('Login')
@allure.suite('Authentication')
class TestLogin:
    """Login feature test suite covering positive, negative, and edge cases."""

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        """Setup fixture - initialize login page before each test."""
        self.login_page = LoginPage(driver)
        yield

    # ══════════════════════════════════════════════════════════════════════════
    # @smoke - Critical Path Tests
    # ══════════════════════════════════════════════════════════════════════════

    @allure.story('Valid Login')
    @allure.title('TC-560: Verify that login works with valid credentials')
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_login_with_valid_credentials(self):
        """TC-560: Verify successful login with valid username and password."""
        with allure.step('Send POST request to /login endpoint'):
            self.login_page.navigate()

        with allure.step('Include valid username in request body'):
            # Using role-based credentials from test data
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Include valid password in request body'):
            self.login_page.enter_password(creds['password'])

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Response should return 200 status code'):
            # UI validation - verify successful login
            self.login_page.verify_login_successful()

        with allure.step('Validate response contains authentication token'):
            # For UI automation, verify user reached authenticated state
            assert 'login' not in self.login_page.get_current_url().lower()

    @allure.story('Valid Login - UI Flow')
    @allure.title('TC-21: Verify that login works with valid credentials (UI)')
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_login_ui_flow_valid(self):
        """TC-21: Open login page and verify successful login with valid credentials."""
        with allure.step('Open login page'):
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()

        with allure.step('Enter valid username'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Enter valid password'):
            self.login_page.enter_password(creds['password'])

        with allure.step('Click login button'):
            self.login_page.click_login_button()

        with allure.step('User should login successfully'):
            self.login_page.verify_login_successful()

    # ══════════════════════════════════════════════════════════════════════════
    # @regression - Negative Tests - Invalid Credentials
    # ══════════════════════════════════════════════════════════════════════════

    @allure.story('Invalid Username')
    @allure.title('TC-561: Verify that login fails with invalid username')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_invalid_username(self):
        """TC-561: Verify login fails when invalid username is provided."""
        with allure.step('Send POST request to /login endpoint'):
            self.login_page.navigate()

        with allure.step('Include invalid username in request body'):
            self.login_page.enter_username('invalid_user_12345')

        with allure.step('Include valid password in request body'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_password(creds['password'])

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Response should return 401 status code'):
            self.login_page.verify_login_failed_with_invalid_credentials()

        with allure.step('Validate error message in response'):
            self.login_page.verify_error_message_displayed('invalid')

    @allure.story('Invalid Password')
    @allure.title('TC-562: Verify that login fails with invalid password')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_invalid_password(self):
        """TC-562: Verify login fails when invalid password is provided."""
        with allure.step('Send POST request to /login endpoint'):
            self.login_page.navigate()

        with allure.step('Include valid username in request body'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Include invalid password in request body'):
            self.login_page.enter_password('WrongPassword123!')

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Response should return 401 status code'):
            self.login_page.verify_login_failed_with_invalid_credentials()

        with allure.step('Validate error message indicates invalid credentials'):
            self.login_page.verify_error_message_displayed('invalid')

    @allure.story('Invalid Data - UI')
    @allure.title('TC-22: To Test Login Form with Invalid Data')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_form_invalid_data_22(self):
        """TC-22: Verify login page accepts username and password input."""
        with allure.step('Navigate to 192.168.10.124:4001'):
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()

        with allure.step('Enter username and password'):
            self.login_page.enter_username('test_user')
            self.login_page.enter_password('test_password')
            # System should accept the input without errors during entry

    @allure.title('TC-23: To Test Login Form with Invalid Data')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_form_invalid_data_23(self):
        """TC-23: Test login form with invalid data (no steps provided)."""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()

    @allure.title('TC-24: To Test Login Form with Invalid Data')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_form_invalid_data_24(self):
        """TC-24: Test login form with invalid data (no steps provided)."""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()

    # ══════════════════════════════════════════════════════════════════════════
    # @regression - Negative Tests - Empty Fields
    # ══════════════════════════════════════════════════════════════════════════

    @allure.story('Empty Username')
    @allure.title('TC-563: Verify that login fails with empty username')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_empty_username(self):
        """TC-563: Verify login fails when username field is empty."""
        with allure.step('Send POST request to /login endpoint'):
            self.login_page.navigate()

        with allure.step('Include empty username field in request body'):
            self.login_page.enter_username('')

        with allure.step('Include valid password in request body'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_password(creds['password'])

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Response should return 400 status code'):
            self.login_page.verify_error_message_displayed()

        with allure.step('Validate error message indicates missing username'):
            self.login_page.verify_username_required_error()

    @allure.story('Empty Password')
    @allure.title('TC-564: Verify that login fails with empty password')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_empty_password(self):
        """TC-564: Verify login fails when password field is empty."""
        with allure.step('Send POST request to /login endpoint'):
            self.login_page.navigate()

        with allure.step('Include valid username in request body'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Include empty password field in request body'):
            self.login_page.enter_password('')

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Response should return 400 status code'):
            self.login_page.verify_error_message_displayed()

        with allure.step('Validate error message indicates missing password'):
            self.login_page.verify_password_required_error()

    # ══════════════════════════════════════════════════════════════════════════
    # @regression - Placeholder Test Cases
    # ══════════════════════════════════════════════════════════════════════════

    @allure.title('TC-25: test import 01')
    @allure.severity(allure.severity_level.TRIVIAL)
    @pytest.mark.regression
    def test_import_01(self):
        """TC-25: Test import placeholder (no steps provided)."""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()
            self.login_page.verify_login_page_loaded()
