// pages/loginPage.js
// ─────────────────────────────────────────────────────────────────────────────
// Login Page — Actions and Assertions
// Generated by: ScriptGenerationAgent | Framework: WebdriverIO-Cucumber-BDD
// ─────────────────────────────────────────────────────────────────────────────
import BasePage from './basePage.js';
import { expect } from '@wdio/globals';
import {
    loginPageHeading,
    loginForm,
    emailInput,
    usernameInput,
    passwordInput,
    loginButton,
    registerLink,
    errorMessage,
    invalidCredentialsMessage,
    emptyUsernameError,
    emptyPasswordError,
    dashboardHeading,
    userProfileIcon
} from '../pageObjects/loginPage.js';

class LoginPage extends BasePage {
    constructor() {
        super();
    }

    // ── Navigation ────────────────────────────────────────────────────────────
    async navigate() {
        const url = process.env.BASE_URL || this.testData.baseUrl || 'http://192.168.10.124:4001';
        await browser.url(url);
        await browser.waitUntil(async () => {
            return await $(loginForm).isDisplayed();
        }, {
            timeout: 10000,
            timeoutMsg: 'Login form not displayed'
        });
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    async enterUsername(username) {
        const usernameField = await $(usernameInput);
        await usernameField.waitForDisplayed();
        await usernameField.setValue(username);
    }

    async enterEmail(email) {
        const emailField = await $(emailInput);
        await emailField.waitForDisplayed();
        await emailField.setValue(email);
    }

    async enterPassword(password) {
        const passwordField = await $(passwordInput);
        await passwordField.waitForDisplayed();
        await passwordField.setValue(password);
    }

    async clickLoginButton() {
        const loginBtn = await $(loginButton);
        await loginBtn.waitForDisplayed();
        await loginBtn.click();
    }

    async submitLoginForm() {
        await this.clickLoginButton();
        await browser.pause(1000); // Allow for form submission
    }

    async loginWithCredentials(username, password) {
        await this.enterUsername(username);
        await this.enterPassword(password);
        await this.submitLoginForm();
    }

    async loginAs(roleName) {
        const creds = this.getLoginDataByRole(roleName);
        await this.loginWithCredentials(creds.username, creds.password);
        return creds;
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    async verifyLoginPageDisplayed() {
        const form = await $(loginForm);
        await expect(form).toBeDisplayed();
        
        const emailField = await $(emailInput);
        await expect(emailField).toBeDisplayed();
        
        const passwordField = await $(passwordInput);
        await expect(passwordField).toBeDisplayed();
        
        const loginBtn = await $(loginButton);
        await expect(loginBtn).toBeDisplayed();
        
        const regLink = await $(registerLink);
        await expect(regLink).toBeDisplayed();
    }

    async verifyLoginSuccessful() {
        await browser.waitUntil(async () => {
            const url = await browser.getUrl();
            return url.includes('/dashboard') || url.includes('/home');
        }, {
            timeout: 10000,
            timeoutMsg: 'Did not navigate to dashboard after login'
        });
    }

    async verifyInvalidCredentialsError() {
        const errorMsg = await $(invalidCredentialsMessage);
        await errorMsg.waitForDisplayed({ timeout: 5000 });
        await expect(errorMsg).toBeDisplayed();
        const errorText = await errorMsg.getText();
        expect(errorText.toLowerCase()).toContain('invalid');
    }

    async verifyAuthenticationError() {
        const errorMsg = await $(errorMessage);
        await errorMsg.waitForDisplayed({ timeout: 5000 });
        await expect(errorMsg).toBeDisplayed();
    }

    async verifyEmptyUsernameError() {
        const errorMsg = await $(emptyUsernameError);
        await errorMsg.waitForDisplayed({ timeout: 5000 });
        await expect(errorMsg).toBeDisplayed();
    }

    async verifyEmptyPasswordError() {
        const errorMsg = await $(emptyPasswordError);
        await errorMsg.waitForDisplayed({ timeout: 5000 });
        await expect(errorMsg).toBeDisplayed();
    }

    async verifyUsernameAndPasswordAccepted() {
        // Verifies fields accepted input without immediate error
        const usernameField = await $(usernameInput);
        const passwordField = await $(passwordInput);
        await expect(usernameField).toBeDisplayed();
        await expect(passwordField).toBeDisplayed();
    }
}

export default new LoginPage();

