// cypress/e2e/Login.cy.js
// ─────────────────────────────────────────────────────────────────────────────
// Login Feature — Automated Test Suite
// Generated by: ScriptGenerationAgent | Framework: Cypress + JavaScript
// Test Inventory Source: AG-Helix | Selected Cases: 562, 22, 24, 25, 21, 23, 561, 563, 560, 564
// ─────────────────────────────────────────────────────────────────────────────
import LoginPage from '../support/pages/loginPage.js';

describe('Login Feature', () => {
    let loginPage;

    before(() => {
        loginPage = new LoginPage();
    });

    beforeEach(() => {
        cy.clearCookies();
        cy.clearLocalStorage();
    });

    // ── @smoke — Critical path ────────────────────────────────────────────────

    it('TC-021: Verify that login works with valid credentials @smoke @regression', () => {
        cy.step('Open login page', () => {
            loginPage.navigate();
        });

        cy.step('Verify login page displays', () => {
            loginPage.verifyLoginPageLoaded();
        });

        cy.step('Enter valid username', () => {
            const creds = loginPage.getLoginDataByRole('Admin');
            loginPage.fillUsername(creds.Username);
        });

        cy.step('Enter valid password', () => {
            const creds = loginPage.getLoginDataByRole('Admin');
            loginPage.fillPassword(creds.Password);
        });

        cy.step('Click login button', () => {
            loginPage.clickLogin();
        });

        cy.step('Verify user should login successfully', () => {
            loginPage.verifyLoginSuccess();
        });
    });

    it('TC-560: Verify that login works with valid credentials (API) @smoke @regression', () => {
        const creds = loginPage.getLoginDataByRole('Admin');

        cy.step('Send POST request to /login endpoint', () => {
            loginPage.loginViaAPI(creds.Username, creds.Password).as('loginResponse');
        });

        cy.step('Validate response returns 200 status code', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseStatus(response, 200);
            });
        });

        cy.step('Validate response contains authentication token', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseContainsToken(response);
            });
        });
    });

    // ── @regression — Negative tests ─────────────────────────────────────────

    it('TC-562: Verify that login fails with invalid password @regression', () => {
        const creds = loginPage.getLoginDataByRole('Admin');

        cy.step('Send POST request to /login endpoint with valid username and invalid password', () => {
            loginPage.loginViaAPI(creds.Username, 'InvalidPassword123!').as('loginResponse');
        });

        cy.step('Validate response returns 401 status code', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseStatus(response, 401);
            });
        });

        cy.step('Validate error message indicates invalid credentials', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseContainsError(response, 'Invalid credentials');
            });
        });
    });

    it('TC-561: Verify that login fails with invalid username @regression', () => {
        const creds = loginPage.getLoginDataByRole('Admin');

        cy.step('Send POST request to /login endpoint with invalid username and valid password', () => {
            loginPage.loginViaAPI('InvalidUser999', creds.Password).as('loginResponse');
        });

        cy.step('Validate response returns 401 status code', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseStatus(response, 401);
            });
        });

        cy.step('Validate error message indicates invalid credentials', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseContainsError(response, 'Invalid credentials');
            });
        });
    });

    it('TC-563: Verify that login fails with empty username @regression', () => {
        const creds = loginPage.getLoginDataByRole('Admin');

        cy.step('Send POST request to /login endpoint with empty username field', () => {
            loginPage.loginViaAPI('', creds.Password).as('loginResponse');
        });

        cy.step('Validate response returns 400 status code', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseStatus(response, 400);
            });
        });

        cy.step('Validate error message indicates missing username', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseContainsError(response, 'username');
            });
        });
    });

    it('TC-564: Verify that login fails with empty password @regression', () => {
        const creds = loginPage.getLoginDataByRole('Admin');

        cy.step('Send POST request to /login endpoint with valid username and empty password', () => {
            loginPage.loginViaAPI(creds.Username, '').as('loginResponse');
        });

        cy.step('Validate response returns 400 status code', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseStatus(response, 400);
            });
        });

        cy.step('Validate error message indicates missing password', () => {
            cy.get('@loginResponse').then((response) => {
                loginPage.verifyResponseContainsError(response, 'password');
            });
        });
    });

    it('TC-022: To Test Login Form with Invalid Data @regression', () => {
        cy.step('Navigate to 192.168.10.124:4001', () => {
            loginPage.navigate();
        });

        cy.step('Verify system displays Login Page with Email, Password fields, Login button and Register link', () => {
            loginPage.verifyLoginPageElements();
        });

        cy.step('Enter username and password', () => {
            loginPage.fillUsername('invalidUser');
            loginPage.fillPassword('invalidPass');
        });

        cy.step('Verify system accepts the username and password', () => {
            cy.get('input[name="username"]').should('have.value', 'invalidUser');
            cy.get('input[name="password"]').should('have.value', 'invalidPass');
        });
    });

    // ── Placeholder tests for incomplete test cases ──────────────────────────

    it('TC-024: To Test Login Form with Invalid Data @regression', () => {
        cy.step('Navigate to login page', () => {
            loginPage.navigate();
        });

        cy.step('Test login form with invalid data (steps not provided)', () => {
            cy.log('TODO: Complete test steps for TC-024');
        });
    });

    it('TC-025: test import 01 @regression', () => {
        cy.step('Execute test import 01 (steps not provided)', () => {
            cy.log('TODO: Complete test steps for TC-025');
        });
    });

    it('TC-023: To Test Login Form with Invalid Data @regression', () => {
        cy.step('Navigate to login page', () => {
            loginPage.navigate();
        });

        cy.step('Test login form with invalid data (steps not provided)', () => {
            cy.log('TODO: Complete test steps for TC-023');
        });
    });
});

