package pageObjects;

/**
 * LoginPageObjects.java
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java TestNG
 * Purpose: Locator constants for Login feature
 * Rules: No logic | No imports beyond annotations | Group by UI section
 */
public class LoginPageObjects {

    // ── Login form elements ───────────────────────────────────────────────────
    public static final String EMAIL_INPUT = "input[name='email']";
    public static final String USERNAME_INPUT = "input[name='username']";
    public static final String PASSWORD_INPUT = "input[type='password']";
    public static final String LOGIN_BUTTON = "button[type='submit']";
    public static final String LOGIN_BUTTON_ALT = "//button[contains(text(),'Login')]";
    
    // ── Navigation ────────────────────────────────────────────────────────────
    public static final String REGISTER_LINK = "a[href*='register']";
    public static final String FORGOT_PASSWORD_LINK = "//a[contains(text(),'Forgot')]";
    
    // ── Validation messages ───────────────────────────────────────────────────
    public static final String ERROR_MESSAGE = "[role='alert']";
    public static final String ERROR_MESSAGE_ALT = ".error-message";
    public static final String INVALID_CREDENTIALS_MSG = "//*[contains(text(),'Invalid credentials') or contains(text(),'invalid credentials') or contains(text(),'401')]";
    public static final String MISSING_USERNAME_MSG = "//*[contains(text(),'missing username') or contains(text(),'required') or contains(text(),'400')]";
    public static final String MISSING_PASSWORD_MSG = "//*[contains(text(),'missing password') or contains(text(),'required') or contains(text(),'400')]";
    
    // ── Post-login verification ───────────────────────────────────────────────
    public static final String DASHBOARD_INDICATOR = "//h1[contains(text(),'Dashboard')] | //*[@id='dashboard'] | //nav";
    public static final String AUTH_TOKEN_INDICATOR = "//*[@data-auth-token] | //meta[@name='token']";
    public static final String USER_PROFILE_MENU = "[aria-label='User menu'] | .user-profile";
    
    // TODO: verify selectors against live app at 192.168.10.124:4001
}