package pageObjects;

/**
 * LoginPage — Locators only
 * Generated by Qentrix ScriptGenerationAgent
 * Framework: Selenium + Java + TestNG
 * RULES: Public static final fields ONLY | Zero logic | Zero imports beyond annotations
 */
public class LoginPage {

    // ── Page URL / Navigation ────────────────────────────────────────────────
    public static final String LOGIN_PATH = "/login";

    // ── Form inputs ───────────────────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String EMAIL_INPUT = "input[name='email'], input[type='email'], input[placeholder*='Email' i], //input[contains(@placeholder, 'Email')], //label[contains(., 'Email')]/following::input[1]";
    
    // TODO: verify selector against live app
    public static final String USERNAME_INPUT = "input[name='username'], input[placeholder*='Username' i], //input[contains(@placeholder, 'Username')], //label[contains(., 'Username')]/following::input[1]";
    
    // TODO: verify selector against live app
    public static final String PASSWORD_INPUT = "input[name='password'], input[type='password'], input[placeholder*='Password' i], //input[@type='password'], //label[contains(., 'Password')]/following::input[1]";

    // ── Buttons ───────────────────────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String LOGIN_BUTTON = "button[type='submit'], button:contains('Login'), //button[contains(., 'Login')], //button[contains(@class, 'login')], //*[@id='login']//button";
    
    // TODO: verify selector against live app
    public static final String REGISTER_LINK = "a:contains('Register'), //a[contains(., 'Register')], a[href*='register']";

    // ── Validation / error messages ───────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String ERROR_MESSAGE = "[role='alert'], .error-message, .alert-danger, //div[contains(@class, 'error')], //*[contains(text(), 'Invalid') or contains(text(), 'failed') or contains(text(), 'incorrect')]";
    
    // TODO: verify selector against live app
    public static final String SUCCESS_MESSAGE = "[role='alert'], .success-message, .alert-success, //div[contains(@class, 'success')]";
    
    // TODO: verify selector against live app
    public static final String REQUIRED_FIELD_ERROR = ".field-error, span:contains('Required'), //span[contains(., 'Required')], //*[contains(text(), 'required')]";
    
    // TODO: verify selector against live app
    public static final String INVALID_CREDENTIALS_ERROR = "//*[contains(text(), 'Invalid credentials') or contains(text(), 'Authentication failed') or contains(text(), 'incorrect')]";
    
    // TODO: verify selector against live app
    public static final String EMPTY_USERNAME_ERROR = "//*[contains(text(), 'missing username') or contains(text(), 'Username required') or contains(text(), 'Username is required')]";
    
    // TODO: verify selector against live app
    public static final String EMPTY_PASSWORD_ERROR = "//*[contains(text(), 'missing password') or contains(text(), 'Password required') or contains(text(), 'Password is required')]";

    // ── Post-login verification ───────────────────────────────────────────────
    // TODO: verify selector against live app
    public static final String DASHBOARD_HEADING = "h1, h2, [role='heading'], //h1 | //h2";
    
    // TODO: verify selector against live app
    public static final String AUTH_TOKEN_ELEMENT = "[data-testid='auth-token'], .auth-token, //input[@name='token']";
    
    // TODO: verify selector against live app
    public static final String USER_PROFILE = "[data-testid='user-profile'], .user-profile, //div[contains(@class, 'profile')], //*[contains(@class, 'user')]";

    // ── Page state ────────────────────────────────────────────────────────────
    public static final String LOGIN_PAGE_TITLE = "Login";
    public static final String DASHBOARD_URL_FRAGMENT = "/dashboard";
}
