// pages/loginPage.js
// ─────────────────────────────────────────────────────────────────────────────
// Generated by: ScriptGenerationAgent | Framework: Cypress JS
// Feature: Login | Test Cases: 21, 22, 23, 24, 25, 560-564
// ─────────────────────────────────────────────────────────────────────────────
import {
    emailInput,
    passwordInput,
    loginButton,
    registerLink,
    errorMessage,
    invalidCredsMsg,
    missingUsernameMsg,
    missingPasswordMsg,
    dashboardHeading,
    loginEndpoint
} from '../pageObjects/loginPage.js';

class LoginPage {
    // ── Navigation ────────────────────────────────────────────────────────────
    navigate() {
        const baseUrl = Cypress.env('BASE_URL') || 'http://192.168.10.124:4001';
        cy.visit(baseUrl);
        cy.url().should('include', baseUrl);
    }

    // ── Actions ───────────────────────────────────────────────────────────────
    fillEmail(email) {
        cy.get(emailInput).clear().type(email);
    }

    fillPassword(password) {
        cy.get(passwordInput).clear().type(password);
    }

    fillCredentials(email, password) {
        this.fillEmail(email);
        this.fillPassword(password);
    }

    clickLogin() {
        cy.get(loginButton).click();
    }

    submitLogin(email, password) {
        this.fillCredentials(email, password);
        this.clickLogin();
    }

    // ── API Login Actions ─────────────────────────────────────────────────────
    apiLogin(username, password, expectedStatus = 200) {
        const baseUrl = Cypress.env('BASE_URL') || 'http://192.168.10.124:4001';
        return cy.request({
            method: 'POST',
            url: `${baseUrl}${loginEndpoint}`,
            body: { username, password },
            failOnStatusCode: false
        }).then(response => {
            expect(response.status).to.eq(expectedStatus);
            return response;
        });
    }

    apiLoginWithEmptyUsername(password) {
        const baseUrl = Cypress.env('BASE_URL') || 'http://192.168.10.124:4001';
        return cy.request({
            method: 'POST',
            url: `${baseUrl}${loginEndpoint}`,
            body: { username: '', password },
            failOnStatusCode: false
        }).then(response => {
            expect(response.status).to.eq(400);
            return response;
        });
    }

    apiLoginWithEmptyPassword(username) {
        const baseUrl = Cypress.env('BASE_URL') || 'http://192.168.10.124:4001';
        return cy.request({
            method: 'POST',
            url: `${baseUrl}${loginEndpoint}`,
            body: { username, password: '' },
            failOnStatusCode: false
        }).then(response => {
            expect(response.status).to.eq(400);
            return response;
        });
    }

    // ── Assertions ────────────────────────────────────────────────────────────
    verifyLoginPageLoaded() {
        cy.get(emailInput).should('be.visible');
        cy.get(passwordInput).should('be.visible');
        cy.get(loginButton).should('be.visible');
        cy.get(registerLink).should('be.visible');
    }

    verifyLoginSuccess() {
        cy.url().should('not.include', '/login');
        cy.get(dashboardHeading).should('be.visible');
    }

    verifyErrorMessage(expectedText) {
        cy.get(errorMessage).should('be.visible');
        if (expectedText) {
            cy.get(errorMessage).should('contain.text', expectedText);
        }
    }

    verifyInvalidCredentialsError() {
        cy.contains(invalidCredsMsg).should('be.visible');
    }

    verifyMissingUsernameError() {
        cy.contains(missingUsernameMsg).should('be.visible');
    }

    verifyMissingPasswordError() {
        cy.contains(missingPasswordMsg).should('be.visible');
    }

    verifyApiResponseContainsToken(response) {
        expect(response.body).to.have.property('token');
        expect(response.body.token).to.not.be.empty;
    }

    verifyApiErrorMessage(response, expectedMessage) {
        expect(response.body).to.have.property('error');
        expect(response.body.error).to.include(expectedMessage);
    }
}

export default LoginPage;

