// pages/loginPage.js
// ─────────────────────────────────────────────────────────────────────────────
// Login Page Actions and Assertions
// Generated by: ScriptGenerationAgent | Framework: Playwright BDD Cucumber
// ─────────────────────────────────────────────────────────────────────────────
import BasePage from './basePage.js';
import { expect } from '@playwright/test';
import {
    emailInput,
    usernameInput,
    passwordInput,
    loginButton,
    registerLink,
    pageHeading,
    loginForm,
    errorMessage,
    successMessage,
    dashboardIndicator
} from '../pageObjects/loginPage.js';

class LoginPage extends BasePage {
    constructor(page) {
        super(page);
    }

    // ── Navigation ────────────────────────────────────────────────────────────
    async navigate() {
        const baseUrl = process.env.BASE_URL || this.testData.baseUrl || 'http://192.168.10.124:4001';
        await this.open(baseUrl);
        return await super.waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    /**
     * Fill username/email field
     */
    async fillUsername(username) {
        const selector = await this.isElementVisible(emailInput, '', 2000) ? emailInput : usernameInput;
        await this.waitAndFill(selector, username);
    }

    /**
     * Fill password field
     */
    async fillPassword(password) {
        await this.waitAndFill(passwordInput, password);
    }

    /**
     * Click login button
     */
    async clickLogin() {
        await this.waitAndClick(loginButton);
        return await super.waitForPageLoad();
    }

    /**
     * Perform complete login flow
     */
    async login(username, password) {
        await this.fillUsername(username);
        await this.fillPassword(password);
        await this.clickLogin();
    }

    /**
     * Login using role-based credentials from CSV
     */
    async loginAs(roleName) {
        const creds = this.getLoginDataByRole(roleName);
        await this.login(creds.Username, creds.Password);
    }

    /**
     * Send POST request to /login endpoint (API-based login)
     */
    async sendLoginRequest(username, password) {
        const baseUrl = process.env.BASE_URL || this.testData.baseUrl || 'http://192.168.10.124:4001';
        const apiContext = await this.page.context().request;
        const response = await apiContext.post(`${baseUrl}/login`, {
            data: {
                username: username,
                password: password
            },
            headers: {
                'Content-Type': 'application/json'
            }
        });
        return response;
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    /**
     * Verify login page is displayed
     */
    async verifyLoginPageDisplayed() {
        await this.wait();
        await this.isElementVisible(loginForm, this.testData.notVisibleText);
        await this.isElementVisible(emailInput, this.testData.notVisibleText);
        await this.isElementVisible(passwordInput, this.testData.notVisibleText);
        await this.isElementVisible(loginButton, this.testData.notVisibleText);
    }

    /**
     * Verify register link is visible
     */
    async verifyRegisterLinkDisplayed() {
        await this.wait();
        await this.isElementVisible(registerLink, this.testData.notVisibleText);
    }

    /**
     * Verify login was successful (redirected to dashboard or home)
     */
    async verifyLoginSuccess() {
        await this.wait();
        const url = await this.getUrl();
        const isDashboard = url.includes('/dashboard') || url.includes('/home') || url.includes('/app');
        expect(isDashboard).toBeTruthy();
    }

    /**
     * Verify error message is displayed
     */
    async verifyErrorMessage(expectedText = null) {
        await this.wait();
        await this.isElementVisible(errorMessage, this.testData.notVisibleText);
        if (expectedText) {
            await this.verifyElementContainsText(errorMessage, expectedText);
        }
    }

    /**
     * Verify invalid credentials error
     */
    async verifyInvalidCredentialsError() {
        await this.verifyErrorMessage(this.testData.invalidCredentialsMsg || 'Invalid credentials');
    }

    /**
     * Verify API response status code
     */
    async verifyResponseStatus(response, expectedStatus) {
        expect(response.status()).toBe(expectedStatus);
    }

    /**
     * Verify API response contains authentication token
     */
    async verifyAuthTokenPresent(response) {
        const body = await response.json();
        expect(body.token || body.authToken || body.accessToken).toBeDefined();
    }

    /**
     * Verify API response contains error message
     */
    async verifyApiErrorMessage(response, expectedMessage = null) {
        const body = await response.json();
        expect(body.error || body.message).toBeDefined();
        if (expectedMessage) {
            const errorText = body.error || body.message;
            expect(errorText.toLowerCase()).toContain(expectedMessage.toLowerCase());
        }
    }
}

export default LoginPage;

