package pageObjects;

/**
 * LeaveManagementPageObjects.java
 * Locator constants for Leave Management module
 * Generated by: ScriptGenerationAgent | Framework: Selenium Java Hybrid
 * RULES: Constants only | No methods | No logic
 */
public class LeaveManagementPageObjects {

    // ── Login / Authentication ───────────────────────────────────────────────
    public static final String LOGIN_URL = "http://localhost:3000/configurations";
    public static final String USERNAME_INPUT = "//input[@name='username' or @id='username' or @placeholder='Username']";
    public static final String PASSWORD_INPUT = "//input[@name='password' or @id='password' or @type='password']";
    public static final String LOGIN_BUTTON = "//button[contains(text(),'Login') or @type='submit']";

    // ── Leave Application Form ───────────────────────────────────────────────
    public static final String LEAVE_TYPE_DROPDOWN = "//select[@name='leaveType' or @id='leaveType']";
    public static final String START_DATE_INPUT = "//input[@name='startDate' or @id='startDate' or @placeholder='Start Date']";
    public static final String END_DATE_INPUT = "//input[@name='endDate' or @id='endDate' or @placeholder='End Date']";
    public static final String REASON_TEXTAREA = "//textarea[@name='reason' or @id='reason' or @placeholder='Reason']";
    public static final String SUBMIT_BUTTON = "//button[contains(text(),'Submit') or @type='submit']";
    public static final String CANCEL_BUTTON = "//button[contains(text(),'Cancel')]";

    // ── Leave Balance Section ────────────────────────────────────────────────
    public static final String LEAVE_BALANCE_SECTION = "//*[contains(@class,'leave-balance') or contains(text(),'Leave Balance')]";
    public static final String LEAVE_BALANCE_WIDGET = "//*[@id='leaveBalance' or contains(@class,'balance-widget')]";
    public static final String AVAILABLE_DAYS_TEXT = "//*[contains(@class,'available-days') or contains(text(),'Available')]";

    // ── Leave History / List ─────────────────────────────────────────────────
    public static final String LEAVE_HISTORY_TABLE = "//table[contains(@class,'leave-history')]";
    public static final String LEAVE_HISTORY_ROWS = "//table[contains(@class,'leave-history')]//tbody//tr";
    public static final String LEAVE_STATUS_COLUMN = "//td[contains(@class,'status')]";
    public static final String PENDING_LEAVE_ROW = "//tr[contains(.,'Pending')]";
    public static final String CANCEL_LEAVE_BUTTON = "//button[contains(text(),'Cancel')]";

    // ── Date Filter ──────────────────────────────────────────────────────────
    public static final String DATE_FILTER_INPUT = "//input[@name='dateFilter' or @id='dateFilter' or @placeholder='Filter by Date']";
    public static final String APPLY_FILTER_BUTTON = "//button[contains(text(),'Apply') or contains(text(),'Filter')]";

    // ── Validation / Error Messages ──────────────────────────────────────────
    public static final String SUCCESS_MESSAGE = "//*[@role='alert' or contains(@class,'success') or contains(@class,'alert-success')]";
    public static final String ERROR_MESSAGE = "//*[@role='alert' or contains(@class,'error') or contains(@class,'alert-danger')]";
    public static final String VALIDATION_ERROR = "//*[contains(@class,'field-error') or contains(@class,'invalid-feedback')]";
    public static final String REQUIRED_ERROR = "//*[contains(text(),'Required') or contains(text(),'required')]";
    public static final String INVALID_DATE_ERROR = "//*[contains(text(),'invalid date range') or contains(text(),'Invalid date')]";
    public static final String LEAVE_TYPE_REQUIRED_ERROR = "//*[contains(text(),'leave type is required')]";

    // ── Confirmation Dialog / Modal ──────────────────────────────────────────
    public static final String CONFIRMATION_DIALOG = "//*[@role='dialog' or contains(@class,'modal')]";
    public static final String CONFIRM_BUTTON = "//*[@role='dialog']//button[contains(text(),'Confirm') or contains(text(),'Yes')]";
    public static final String MODAL_CLOSE_BUTTON = "//*[@role='dialog']//button[contains(text(),'Close') or contains(@class,'close')]";

    // ── Character Counter ────────────────────────────────────────────────────
    public static final String CHARACTER_COUNT = "//*[contains(@class,'char-count') or contains(text(),'characters')]";

    // ── Leave Types List ─────────────────────────────────────────────────────
    public static final String LEAVE_TYPE_OPTION = "//option";

    // TODO: verify selectors against live app when exploration data is available
}
