BASE_URL=
BROWSER=chromium
HEADLESS=true
ENVIRONMENT=qa

# Qentrix generated test inventory
PROJECT_NAME=AG-Helix
WORK_ITEM_IDS=4
TEST_CASE_IDS=562,22,24,25,21,23,561,563,560,564
TEST_DATA_FILE=test-data/testdata.json
CREDENTIALS_FILE=test-data/credentials.csv
FRAMEWORK_ENGINE=Playwright
FRAMEWORK_TYPE=Hybrid
BUILD_TOOL=npm
BASE_URL=http://192.168.10.124:4001
