# tests/test_login.py
# ─────────────────────────────────────────────────────────────────────────────
# Login feature test cases
# Generated by: Qentrix ScriptGenerationAgent | Framework: Selenium Python POM
# Project: AG-Helix
# ─────────────────────────────────────────────────────────────────────────────
import pytest
import allure
from pages.login_page import LoginPage


@allure.feature('Login')
@allure.story('Authentication')
class TestLogin:
    """Login functionality test suite for AG-Helix"""

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        """Setup login page for each test"""
        self.login_page = LoginPage(driver)
        yield

    # ── @smoke — Valid Credentials ────────────────────────────────────────────

    @allure.title('[21] TC-021: Verify that login works with valid credentials')
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_login_with_valid_credentials_tc021(self):
        """[21] Verify successful login with valid username and password"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Verify login page displays with all required elements'):
            self.login_page.verify_login_page_loaded()

        with allure.step('Enter valid username'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Enter valid password'):
            self.login_page.enter_password(creds['password'])

        with allure.step('Click login button'):
            self.login_page.click_login_button()

        with allure.step('Verify user logged in successfully'):
            self.login_page.verify_login_successful()

    @allure.title('[560] TC-560: Verify that login works with valid credentials (API)')
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_login_api_valid_credentials_tc560(self):
        """[560] Verify successful authentication via POST /login with valid credentials"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Submit valid credentials via login form'):
            self.login_page.login_as_role('Admin')

        with allure.step('Verify response indicates successful authentication (200 status)'):
            self.login_page.verify_login_successful()

    # ── @regression — Invalid Credentials ─────────────────────────────────────

    @allure.title('[22] TC-022: To Test Login Form with Invalid Data')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_with_invalid_data_tc022(self):
        """[22] Verify login fails with invalid username and password"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Verify login page displays'):
            self.login_page.verify_login_page_loaded()

        with allure.step('Enter invalid username and password'):
            self.login_page.enter_username('invalid@test.com')
            self.login_page.enter_password('WrongPass123')

        with allure.step('Submit login form'):
            self.login_page.click_login_button()

        with allure.step('Verify error message displays'):
            self.login_page.verify_login_failed_with_invalid_credentials()

    @allure.title('[561] TC-561: Verify that login fails with invalid username')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_invalid_username_tc561(self):
        """[561] Verify authentication failure with invalid username"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Enter invalid username'):
            self.login_page.enter_username('invaliduser@test.com')

        with allure.step('Enter valid password'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_password(creds['password'])

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Verify 401 status / authentication error message'):
            self.login_page.verify_401_status_error()

    @allure.title('[562] TC-562: Verify that login fails with invalid password')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_invalid_password_tc562(self):
        """[562] Verify authentication failure with invalid password"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Enter valid username'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Enter invalid password'):
            self.login_page.enter_password('InvalidPass123')

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Verify 401 status / invalid credentials error'):
            self.login_page.verify_401_status_error()

    # ── @regression — Empty Fields ────────────────────────────────────────────

    @allure.title('[563] TC-563: Verify that login fails with empty username')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_empty_username_tc563(self):
        """[563] Verify validation error when username field is empty"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Leave username field empty'):
            pass  # No action, field remains empty

        with allure.step('Enter valid password'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_password(creds['password'])

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Verify 400 status / missing username error message'):
            self.login_page.verify_400_status_error()
            self.login_page.verify_required_field_error()

    @allure.title('[564] TC-564: Verify that login fails with empty password')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_empty_password_tc564(self):
        """[564] Verify validation error when password field is empty"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Enter valid username'):
            creds = self.login_page.get_credentials_by_role('Admin')
            self.login_page.enter_username(creds['username'])

        with allure.step('Leave password field empty'):
            pass  # No action, field remains empty

        with allure.step('Submit authentication request'):
            self.login_page.click_login_button()

        with allure.step('Verify 400 status / missing password error message'):
            self.login_page.verify_400_status_error()
            self.login_page.verify_required_field_error()

    # ── Additional Test Cases ─────────────────────────────────────────────────

    @allure.title('[23] TC-023: To Test Login Form with Invalid Data')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_invalid_data_tc023(self):
        """[23] Additional invalid data test case"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Enter invalid credentials'):
            self.login_page.enter_username('test@invalid.com')
            self.login_page.enter_password('Invalid123')

        with allure.step('Submit form'):
            self.login_page.click_login_button()

        with allure.step('Verify authentication failure'):
            self.login_page.verify_login_failed_with_invalid_credentials()

    @allure.title('[24] TC-024: To Test Login Form with Invalid Data')
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.regression
    def test_login_invalid_data_tc024(self):
        """[24] Additional invalid data test case"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Enter invalid credentials'):
            self.login_page.enter_username('wronguser@test.com')
            self.login_page.enter_password('WrongPassword')

        with allure.step('Submit form'):
            self.login_page.click_login_button()

        with allure.step('Verify error displayed'):
            self.login_page.verify_login_failed_with_invalid_credentials()

    @allure.title('[25] TC-025: Test import 01')
    @allure.severity(allure.severity_level.TRIVIAL)
    @pytest.mark.regression
    def test_import_01_tc025(self):
        """[25] Import test case placeholder"""
        with allure.step('Navigate to login page'):
            self.login_page.navigate()

        with allure.step('Verify login page loaded'):
            self.login_page.verify_login_page_loaded()
