# pages/login_page.py
# ─────────────────────────────────────────────────────────────────────────────
# Login Page - Actions and Assertions
# Generated by: Qentrix ScriptGenerationAgent | Framework: Selenium Python PyTest
# ─────────────────────────────────────────────────────────────────────────────
from pages.base_page import BasePage
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import page_objects.login_page as LoginPageLocators


class LoginPage(BasePage):
    """Login page actions and assertions."""

    def __init__(self, driver):
        super().__init__(driver)
        self.url = "http://192.168.10.124:4001"  # From test case context

    # ── Navigation ────────────────────────────────────────────────────────────

    def navigate(self):
        """Navigate to login page."""
        self.driver.get(self.url)
        self.wait_for_page_load()

    # ── Actions ───────────────────────────────────────────────────────────────

    def enter_username(self, username):
        """Enter username in the username/email field."""
        # Try email input first, fallback to username input
        try:
            self.fill_input(LoginPageLocators.EMAIL_INPUT, username)
        except:
            self.fill_input(LoginPageLocators.USERNAME_INPUT, username)

    def enter_password(self, password):
        """Enter password in the password field."""
        self.fill_input(LoginPageLocators.PASSWORD_INPUT, password)

    def click_login_button(self):
        """Click the login/submit button."""
        self.click_element(LoginPageLocators.LOGIN_BUTTON)

    def click_register_link(self):
        """Click the register hyperlink."""
        self.click_element(LoginPageLocators.REGISTER_LINK)

    def login_with_credentials(self, username, password):
        """Complete login flow with provided credentials."""
        self.enter_username(username)
        self.enter_password(password)
        self.click_login_button()
        self.wait_for_page_load()

    def login_as_role(self, role_name):
        """Login using credentials from test data for the given role."""
        creds = self.get_credentials_by_role(role_name)
        self.login_with_credentials(creds['username'], creds['password'])

    # ── Assertions ────────────────────────────────────────────────────────────

    def verify_login_page_loaded(self):
        """Verify login page displays with all required elements."""
        self.wait_for_element_visible(LoginPageLocators.LOGIN_FORM)
        assert self.is_element_visible(LoginPageLocators.EMAIL_INPUT) or \
               self.is_element_visible(LoginPageLocators.USERNAME_INPUT), \
               "Username/Email field not visible"
        assert self.is_element_visible(LoginPageLocators.PASSWORD_INPUT), \
               "Password field not visible"
        assert self.is_element_visible(LoginPageLocators.LOGIN_BUTTON), \
               "Login button not visible"
        assert self.is_element_visible(LoginPageLocators.REGISTER_LINK), \
               "Register link not visible"

    def verify_login_successful(self):
        """Verify user successfully logged in (dashboard or welcome message visible)."""
        self.wait_for_page_load()
        try:
            self.wait_for_element_visible(LoginPageLocators.DASHBOARD_INDICATOR, timeout=10)
        except:
            self.wait_for_element_visible(LoginPageLocators.WELCOME_MESSAGE, timeout=10)

    def verify_login_failed_with_invalid_credentials(self):
        """Verify login fails and appropriate error message is shown."""
        self.wait_for_element_visible(LoginPageLocators.ERROR_MESSAGE)
        error_text = self.get_element_text(LoginPageLocators.ERROR_MESSAGE).lower()
        assert 'invalid' in error_text or 'credentials' in error_text or \
               'incorrect' in error_text or 'unauthorized' in error_text or \
               '401' in error_text, \
               f"Expected invalid credentials error, got: {error_text}"

    def verify_error_message_displayed(self, expected_message_fragment=None):
        """Verify error message is displayed, optionally checking for specific text."""
        self.wait_for_element_visible(LoginPageLocators.ERROR_MESSAGE)
        if expected_message_fragment:
            error_text = self.get_element_text(LoginPageLocators.ERROR_MESSAGE).lower()
            assert expected_message_fragment.lower() in error_text, \
                   f"Expected '{expected_message_fragment}' in error, got: {error_text}"

    def verify_username_required_error(self):
        """Verify missing username error is shown."""
        self.verify_error_message_displayed('username')

    def verify_password_required_error(self):
        """Verify missing password error is shown."""
        self.verify_error_message_displayed('password')

    def verify_status_code(self, expected_code):
        """Verify HTTP response status code (for API-based validation in test cases)."""
        # This is a placeholder for API validation context from test cases 560-564
        # Actual implementation would use requests library or browser DevTools
        # For UI automation, this assertion is conceptual
        pass
