// tests/Login.spec.js
// ─────────────────────────────────────────────────────────────────────────────
// Generated by: ScriptGenerationAgent | Framework: Cypress JS
// Feature: Login | Test Cases: 21-25, 560-564
// ─────────────────────────────────────────────────────────────────────────────
import LoginPage from '../pages/loginPage.js';

describe('Login Feature', () => {
    let loginPage;

    beforeEach(() => {
        loginPage = new LoginPage();
    });

    // ── @smoke — Critical path ────────────────────────────────────────────────

    it('TC-21: Verify that login works with valid credentials @smoke @regression', () => {
        cy.step('Open login page', () => {
            loginPage.navigate();
        });

        cy.step('Verify login page displays', () => {
            loginPage.verifyLoginPageLoaded();
        });

        cy.step('Enter valid username', () => {
            loginPage.fillEmail('admin');
        });

        cy.step('Enter valid password', () => {
            loginPage.fillPassword('admin123');
        });

        cy.step('Click login button', () => {
            loginPage.clickLogin();
        });

        cy.step('Verify user should login successfully', () => {
            loginPage.verifyLoginSuccess();
        });
    });

    it('TC-560: Verify that login works with valid credentials via API @smoke @regression', () => {
        cy.step('Send POST request to /login endpoint', () => {
            return loginPage.apiLogin('admin', 'admin123', 200);
        }).then(response => {
            cy.step('Validate response contains authentication token', () => {
                loginPage.verifyApiResponseContainsToken(response);
            });
        });
    });

    // ── @regression — Negative tests ─────────────────────────────────────────

    it('TC-22: To Test Login Form with Invalid Data @regression', () => {
        cy.step('Navigate to login page', () => {
            loginPage.navigate();
        });

        cy.step('Verify login page displays with Email, Password fields, Login button and Register Hyperlink', () => {
            loginPage.verifyLoginPageLoaded();
        });

        cy.step('Enter invalid username and password', () => {
            loginPage.fillCredentials('invaliduser', 'invalidpass');
        });

        cy.step('Verify system accepts the username and password', () => {
            cy.get('input[type="email"]').should('have.value', 'invaliduser');
            cy.get('input[type="password"]').should('have.value', 'invalidpass');
        });
    });

    it('TC-23: To Test Login Form with Invalid Data @regression', () => {
        cy.step('Navigate to login page', () => {
            loginPage.navigate();
        });

        cy.step('Attempt login with invalid credentials', () => {
            loginPage.submitLogin('wronguser', 'wrongpass');
        });

        cy.step('Verify error message is displayed', () => {
            loginPage.verifyErrorMessage();
        });
    });

    it('TC-24: To Test Login Form with Invalid Data @regression', () => {
        cy.step('Navigate to login page', () => {
            loginPage.navigate();
        });

        cy.step('Attempt login with invalid data', () => {
            loginPage.submitLogin('test@invalid', '12345');
        });

        cy.step('Verify validation error appears', () => {
            loginPage.verifyErrorMessage();
        });
    });

    it('TC-25: test import 01 @regression', () => {
        cy.step('Navigate to login page', () => {
            loginPage.navigate();
        });

        cy.step('Verify login page elements are present', () => {
            loginPage.verifyLoginPageLoaded();
        });
    });

    it('TC-561: Verify that login fails with invalid username via API @regression', () => {
        cy.step('Send POST request to /login endpoint with invalid username', () => {
            return loginPage.apiLogin('invaliduser', 'admin123', 401);
        }).then(response => {
            cy.step('Validate error message indicates invalid credentials', () => {
                loginPage.verifyApiErrorMessage(response, 'invalid credentials');
            });
        });
    });

    it('TC-562: Verify that login fails with invalid password via API @regression', () => {
        cy.step('Send POST request to /login endpoint with invalid password', () => {
            return loginPage.apiLogin('admin', 'wrongpassword', 401);
        }).then(response => {
            cy.step('Validate error message indicates invalid credentials', () => {
                loginPage.verifyApiErrorMessage(response, 'invalid credentials');
            });
        });
    });

    it('TC-563: Verify that login fails with empty username via API @regression', () => {
        cy.step('Send POST request to /login endpoint with empty username', () => {
            return loginPage.apiLoginWithEmptyUsername('admin123');
        }).then(response => {
            cy.step('Validate error message indicates missing username', () => {
                loginPage.verifyApiErrorMessage(response, 'username');
            });
        });
    });

    it('TC-564: Verify that login fails with empty password via API @regression', () => {
        cy.step('Send POST request to /login endpoint with empty password', () => {
            return loginPage.apiLoginWithEmptyPassword('admin');
        }).then(response => {
            cy.step('Validate error message indicates missing password', () => {
                loginPage.verifyApiErrorMessage(response, 'password');
            });
        });
    });
});

