// tests/Login.test.js
// ─────────────────────────────────────────────────────────────────────────────
// Login feature test suite
// Generated by: ScriptGenerationAgent | Framework: StaticFrameworks
// ─────────────────────────────────────────────────────────────────────────────
import { expect } from '@playwright/test';
import test from '../testFixtures/fixture.js';

// ─────────────────────────────────────────────────────────────────────────────
// Fixture used: loginPage (registered in testFixtures/fixture.js)
// Page class: pages/loginPage.js
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Login Feature', () => {

    test.describe.configure({ mode: 'parallel' });

    // ── @smoke — Critical path ────────────────────────────────────────────────

    test('TC-560: Verify that login works with valid credentials @smoke @regression', async ({ loginPage }) => {
        await test.step('Send POST request to /login endpoint', async () => {
            const response = await loginPage.sendLoginRequest('admin', 'admin123');
            await test.step('Request should be accepted', async () => {
                expect(response).toBeTruthy();
            });
            await test.step('Response should return 200 status code', async () => {
                await loginPage.verifyResponseStatus(response, 200);
            });
            await test.step('Validate response contains authentication token', async () => {
                await loginPage.verifyAuthTokenPresent(response);
            });
        });
    });

    test('TC-21: Verify that login works with valid credentials (UI) @smoke @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigate();
        });
        await test.step('Login page should display', async () => {
            await loginPage.verifyLoginPageLoaded();
        });
        await test.step('Enter valid username', async () => {
            await loginPage.fillUsername('admin');
        });
        await test.step('Enter valid password', async () => {
            await loginPage.fillPassword('admin123');
        });
        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });
        await test.step('User should login successfully', async () => {
            await loginPage.verifyLoginSuccess();
        });
    });

    test('TC-22: To Test Login Form with Invalid Data @smoke @regression', async ({ loginPage }) => {
        await test.step('Navigate to 192.168.10.124:4001', async () => {
            await loginPage.navigate();
        });
        await test.step('System should display a Login Page with the Email, Password fields, Login button and Register Hyperlink', async () => {
            await loginPage.verifyLoginPageLoaded();
        });
        await test.step('Enter username and password', async () => {
            await loginPage.fillUsername('invalid_user');
            await loginPage.fillPassword('invalid_pass');
        });
        await test.step('System should accept the username and password', async () => {
            await loginPage.clickLoginButton();
        });
    });

    // ── @regression — Negative tests ─────────────────────────────────────────

    test('TC-561: Verify that login fails with invalid username @regression', async ({ loginPage }) => {
        await test.step('Send POST request to /login endpoint', async () => {
            const response = await loginPage.sendLoginRequest('invalid_user', 'admin123');
            await test.step('Request should be accepted', async () => {
                expect(response).toBeTruthy();
            });
            await test.step('Response should return 401 status code', async () => {
                await loginPage.verifyResponseStatus(response, 401);
            });
            await test.step('Validate error message in response', async () => {
                const body = await response.json();
                expect(body).toHaveProperty('error');
                expect(body.error).toContain('Invalid credentials');
            });
        });
    });

    test('TC-562: Verify that login fails with invalid password @regression', async ({ loginPage }) => {
        await test.step('Send POST request to /login endpoint', async () => {
            const response = await loginPage.sendLoginRequest('admin', 'wrong_password');
            await test.step('Request should be accepted', async () => {
                expect(response).toBeTruthy();
            });
            await test.step('Response should return 401 status code', async () => {
                await loginPage.verifyResponseStatus(response, 401);
            });
            await test.step('Validate error message in response', async () => {
                const body = await response.json();
                expect(body).toHaveProperty('error');
                expect(body.error).toContain('Invalid credentials');
            });
        });
    });

    test('TC-563: Verify that login fails with empty username @regression', async ({ loginPage }) => {
        await test.step('Send POST request to /login endpoint', async () => {
            const response = await loginPage.sendLoginRequest('', 'admin123');
            await test.step('Request should be accepted', async () => {
                expect(response).toBeTruthy();
            });
            await test.step('Response should return 400 status code', async () => {
                await loginPage.verifyResponseStatus(response, 400);
            });
            await test.step('Validate error message indicates missing username', async () => {
                const body = await response.json();
                expect(body).toHaveProperty('error');
                expect(body.error).toContain('missing username');
            });
        });
    });

    test('TC-564: Verify that login fails with empty password @regression', async ({ loginPage }) => {
        await test.step('Send POST request to /login endpoint', async () => {
            const response = await loginPage.sendLoginRequest('admin', '');
            await test.step('Request should be accepted', async () => {
                expect(response).toBeTruthy();
            });
            await test.step('Response should return 400 status code', async () => {
                await loginPage.verifyResponseStatus(response, 400);
            });
            await test.step('Validate error message indicates missing password', async () => {
                const body = await response.json();
                expect(body).toHaveProperty('error');
                expect(body.error).toContain('missing password');
            });
        });
    });

    test('TC-23: To Test Login Form with Invalid Data (UI) @regression', async ({ loginPage }) => {
        await test.step('Navigate to login page', async () => {
            await loginPage.navigate();
        });
        await test.step('Verify login page loaded', async () => {
            await loginPage.verifyLoginPageLoaded();
        });
        await test.step('Enter invalid credentials', async () => {
            await loginPage.fillUsername('invalid_user');
            await loginPage.fillPassword('invalid_pass');
        });
        await test.step('Submit login form', async () => {
            await loginPage.clickLoginButton();
        });
        await test.step('Verify invalid credentials error', async () => {
            await loginPage.verifyInvalidCredentialsError();
        });
    });

    test('TC-24: To Test Login Form with Invalid Data (Alternate) @regression', async ({ loginPage }) => {
        await test.step('Navigate to login page', async () => {
            await loginPage.navigate();
        });
        await test.step('Verify login page loaded', async () => {
            await loginPage.verifyLoginPageLoaded();
        });
        await test.step('Enter invalid credentials', async () => {
            await loginPage.fillUsername('test_user');
            await loginPage.fillPassword('test_pass');
        });
        await test.step('Submit login form', async () => {
            await loginPage.clickLoginButton();
        });
        await test.step('Verify error message displayed', async () => {
            await loginPage.verifyInvalidCredentialsError();
        });
    });

    // ── @regression — Edge cases ──────────────────────────────────────────────

    test('TC-25: Test import 01 @regression', async ({ loginPage }) => {
        await test.step('Navigate to login page', async () => {
            await loginPage.navigate();
        });
        await test.step('Verify login page loaded', async () => {
            await loginPage.verifyLoginPageLoaded();
        });
    });

});

