// Login Test Suite
// Generated by Qentrix for AG-Helix

import test from '../testFixtures/fixture.js';

test.describe.parallel('Login Test Suite', () => {

    test('[TC-640] Verify that login shows appropriate error for disabled account @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter disabled account username', async () => {
            await loginPage.enterUsername('disabled.user@test.com');
        });

        await test.step('Enter correct password for disabled account', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify account disabled message displays', async () => {
            await loginPage.verifyAccountDisabledError();
        });
    });

    test('[TC-638] Verify that login handles unicode characters in credentials @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter username with unicode characters', async () => {
            await loginPage.enterUsernameWithUnicodeCharacters();
        });

        await test.step('Enter password with unicode characters', async () => {
            await loginPage.enterPasswordWithUnicodeCharacters();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify unicode characters are handled correctly', async () => {
            // System should process unicode input without errors
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-621] Verify that login handles special characters in username @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter username with special characters', async () => {
            await loginPage.enterUsernameWithSpecialCharacters();
        });

        await test.step('Enter valid password', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify system handles special characters correctly', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-628] Verify that tab navigation works between form fields @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Click on username field', async () => {
            await loginPage.focusUsernameField();
        });

        await test.step('Press tab key to move to password field', async () => {
            await loginPage.pressTabKey();
        });

        await test.step('Press tab key again to move to login button', async () => {
            await loginPage.pressTabKey();
        });

        await test.step('Press enter key to trigger login attempt', async () => {
            await loginPage.pressEnterKey();
        });
    });

    test('[TC-635] Verify that login prevents multiple rapid submissions @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid credentials', async () => {
            await loginPage.enterValidCredentials();
        });

        await test.step('Click login button rapidly multiple times', async () => {
            await loginPage.clickLoginButtonRapidly();
        });

        await test.step('Verify only one login request is processed', async () => {
            // Button should be disabled temporarily or only one request sent
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-637] Verify that login page uses HTTPS protocol @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
        });

        await test.step('Verify URL uses HTTPS protocol', async () => {
            await loginPage.verifyHTTPSProtocol();
        });
    });

    test('[TC-624] Verify that login fails with empty username field @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Leave username field empty', async () => {
            await loginPage.leaveUsernameEmpty();
        });

        await test.step('Enter valid password', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify username required error displays', async () => {
            await loginPage.verifyUsernameRequiredError();
        });

        await test.step('Verify user remains on login page', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-641] Verify that login response time is acceptable @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid credentials', async () => {
            await loginPage.enterValidCredentials();
        });

        await test.step('Click login button and measure response time', async () => {
            await loginPage.verifyLoginResponseTime(2000);
        });
    });

    test('[TC-630] Verify that login shows error for SQL injection attempts @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter SQL injection string in username', async () => {
            await loginPage.enterSQLInjectionUsername();
        });

        await test.step('Enter valid password', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify error handling for malicious input', async () => {
            await loginPage.verifyErrorMessageDisplayed();
        });
    });

    test('[TC-626] Verify that login handles maximum length username @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter maximum allowed length username', async () => {
            await loginPage.enterMaximumLengthUsername();
        });

        await test.step('Enter valid password', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify system processes request', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-21] Verify that login works with valid credentials @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid username', async () => {
            await loginPage.enterValidCredentials();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify user logs in successfully', async () => {
            await loginPage.verifySuccessfulLogin();
        });
    });

    test('[TC-639] Verify that login form maintains state during session @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter username', async () => {
            await loginPage.enterUsername('testuser@test.com');
        });

        await test.step('Navigate away from page', async () => {
            await loginPage.navigateAway();
        });

        await test.step('Return to login page', async () => {
            await loginPage.navigateBackToLogin();
        });

        await test.step('Verify username field is cleared for security', async () => {
            await loginPage.verifyLoginPageDisplayed();
        });
    });

    test('[TC-636] Verify that login form fields have proper placeholder text @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Verify username field placeholder', async () => {
            await loginPage.verifyUsernamePlaceholder();
        });

        await test.step('Verify password field placeholder', async () => {
            await loginPage.verifyPasswordPlaceholder();
        });
    });

    test('[TC-644] Verify that login implements rate limiting for failed attempts @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Attempt login multiple times with invalid credentials', async () => {
            for (let i = 0; i < 5; i++) {
                await loginPage.enterCredentials('invalid@test.com', 'wrongpassword');
                await loginPage.clickLoginButton();
                await loginPage.page.waitForTimeout(500);
            }
        });

        await test.step('Verify rate limiting is enforced', async () => {
            await loginPage.verifyRateLimitingMessage();
        });
    });

    test('[TC-631] Verify that login button is clickable and responsive @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Hover over login button', async () => {
            await loginPage.verifyLoginButtonHoverState();
        });

        await test.step('Verify button is clickable', async () => {
            await loginPage.verifyLoginButtonClickable();
        });
    });

    test('[TC-646] Verify that login sends correct API request format @regression', async ({ loginPage }) => {
        await test.step('Open login page with network monitoring', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid credentials', async () => {
            await loginPage.enterValidCredentials();
        });

        await test.step('Monitor API request and verify format', async () => {
            const requestPromise = loginPage.monitorAPIRequest();
            await loginPage.clickLoginButton();
            const request = await requestPromise;
            // Verify request contains username and password
        });
    });

    test('[TC-633] Verify that login page loads within acceptable time @regression', async ({ loginPage }) => {
        await test.step('Clear browser cache', async () => {
            await loginPage.clearBrowserCache();
        });

        await test.step('Navigate to login page and measure load time', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyPageLoadTime(3000);
        });
    });

    test('[TC-27] To Test Login Form with Invalid Data @smoke', async ({ loginPage }) => {
        await test.step('Navigate to login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter invalid username and password', async () => {
            await loginPage.enterCredentials('invalid@test.com', 'wrongpassword');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify error message displays', async () => {
            await loginPage.verifyErrorMessageDisplayed();
        });
    });

    test('[TC-634] Verify that login form accepts keyboard input properly @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Navigate to username field using keyboard', async () => {
            await loginPage.focusUsernameField();
        });

        await test.step('Type username using keyboard', async () => {
            await loginPage.enterUsername('testuser@test.com');
        });

        await test.step('Navigate to password field using keyboard', async () => {
            await loginPage.pressTabKey();
        });

        await test.step('Type password using keyboard', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });
    });

    test('[TC-622] Verify that password field masks input characters @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Click on password field', async () => {
            await loginPage.focusPasswordField();
        });

        await test.step('Type password and verify masking', async () => {
            await loginPage.enterPassword('TestPassword123!');
            await loginPage.verifyPasswordFieldMasked();
        });
    });

    test('[TC-625] Verify that login fails with empty password field @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid username', async () => {
            await loginPage.enterUsername('testuser@test.com');
        });

        await test.step('Leave password field empty', async () => {
            await loginPage.leavePasswordEmpty();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify password required error displays', async () => {
            await loginPage.verifyPasswordRequiredError();
        });

        await test.step('Verify user remains on login page', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-643] Verify that login handles case sensitivity correctly @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter username in different case', async () => {
            await loginPage.enterUsername('TESTUSER@TEST.COM');
        });

        await test.step('Enter valid password', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify system handles case according to requirements', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-619] Verify that login fails with invalid username @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter invalid username', async () => {
            await loginPage.enterUsername('invaliduser@test.com');
        });

        await test.step('Enter valid password', async () => {
            await loginPage.enterPassword('ValidPassword123!');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify error message displays', async () => {
            await loginPage.verifyErrorMessageDisplayed();
        });

        await test.step('Verify user remains on login page', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-627] Verify that login handles maximum length password @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid username', async () => {
            await loginPage.enterUsername('testuser@test.com');
        });

        await test.step('Enter maximum allowed length password', async () => {
            await loginPage.enterMaximumLengthPassword();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify system processes request', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-642] Verify that login page is responsive on different screen sizes @regression', async ({ loginPage }) => {
        await test.step('Open login page on desktop', async () => {
            await loginPage.verifyResponsiveDesign(1920, 1080);
            await loginPage.navigateToLoginPage();
        });

        await test.step('Resize to tablet size', async () => {
            await loginPage.verifyResponsiveDesign(768, 1024);
        });

        await test.step('Resize to mobile size', async () => {
            await loginPage.verifyResponsiveDesign(375, 667);
        });

        await test.step('Test form functionality on mobile', async () => {
            await loginPage.verifyLoginPageDisplayed();
        });
    });

    test('[TC-620] Verify that login fails with empty credentials @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Leave username field empty', async () => {
            await loginPage.leaveUsernameEmpty();
        });

        await test.step('Leave password field empty', async () => {
            await loginPage.leavePasswordEmpty();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify validation error displays', async () => {
            await loginPage.verifyErrorMessageDisplayed();
        });

        await test.step('Verify user remains on login page', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-623] Verify that login page displays all required elements @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
        });

        await test.step('Verify all required elements are present', async () => {
            await loginPage.verifyAllLoginPageElements();
        });
    });

    test('[TC-645] Verify that login form has proper field validation styling @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter invalid data and verify validation styling', async () => {
            await loginPage.verifyFieldValidationStyling();
        });
    });

    test('[TC-618] Verify that login fails with invalid password @smoke', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid username', async () => {
            await loginPage.enterUsername('testuser@test.com');
        });

        await test.step('Enter invalid password', async () => {
            await loginPage.enterPassword('wrongpassword');
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify error validation displays', async () => {
            await loginPage.verifyErrorMessageDisplayed();
        });

        await test.step('Verify user remains on login page', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

    test('[TC-26] To Test Login Form with Valid Data @smoke', async ({ loginPage }) => {
        await test.step('Navigate to login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter valid username and password', async () => {
            await loginPage.enterValidCredentials();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify successful login', async () => {
            await loginPage.verifySuccessfulLogin();
        });
    });

    test('[TC-632] Verify that login handles whitespace in credentials @regression', async ({ loginPage }) => {
        await test.step('Open login page', async () => {
            await loginPage.navigateToLoginPage();
            await loginPage.verifyLoginPageDisplayed();
        });

        await test.step('Enter credentials with leading/trailing spaces', async () => {
            await loginPage.enterCredentialsWithWhitespace();
        });

        await test.step('Click login button', async () => {
            await loginPage.clickLoginButton();
        });

        await test.step('Verify system handles whitespace appropriately', async () => {
            await loginPage.verifyUserRemainsOnLoginPage();
        });
    });

});

