// savedProducts.spec.js - Test Inventory Cases for Saved Products
// Generated by Qentrix Agent
// QENTRIX_REQUIREMENT_SIGNATURE:1e2930ccea9b365995f8e7d5b6df4b1978712f5436571fc06891157cf51e04e0

import { test, expect } from '@playwright/test';
import * as SavedProductsPage from '../pageObjects/SavedProductsPage.js';
import * as LoginPage from '../pageObjects/LoginPage.js';
import * as CommonActions from '../actions/CommonActions.js';
import * as SavedProductsActions from '../actions/SavedProductsActions.js';
import { testData } from '../config/testData.js';

test.describe('Saved Products Functionality', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto(testData.baseUrl);
  });

  // [678] Verify that registered customer can save a product to favorites
  test('[678] Verify that registered customer can save a product to favorites', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await CommonActions.navigateTo(page, SavedProductsPage.productCatalog);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productCard);
    
    await SavedProductsActions.selectProduct(page, testData.products.standard.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await SavedProductsActions.saveProduct(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.standard.name);
  });

  // [679] Verify that registered customer can save multiple products
  test('[679] Verify that registered customer can save multiple products', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await CommonActions.navigateTo(page, SavedProductsPage.productCatalog);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productCard);
    
    await SavedProductsActions.saveProductByName(page, testData.products.product1.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.saveProductByName(page, testData.products.product2.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.product1.name);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.product2.name);
  });

  // [680] Verify that saved product displays correct product information
  test('[680] Verify that saved product displays correct product information', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.saveProductByName(page, testData.products.standard.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    
    await SavedProductsActions.viewSavedProductDetails(page, testData.products.standard.name);
    await SavedProductsActions.verifyProductName(page, testData.products.standard.name);
    await SavedProductsActions.verifyProductPrice(page, testData.products.standard.price);
    await SavedProductsActions.verifyProductImage(page);
  });

  // [681] Verify that customer can remove product from saved list
  test('[681] Verify that customer can remove product from saved list', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    
    const productToRemove = testData.products.toRemove.name;
    await SavedProductsActions.selectSavedProduct(page, productToRemove);
    
    await SavedProductsActions.clickRemoveButton(page, productToRemove);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.confirmRemovalButton);
    
    await SavedProductsActions.confirmRemoval(page);
    await SavedProductsActions.verifyProductNotInSavedList(page, productToRemove);
  });

  // [682] Verify that saved products persist across login sessions
  test('[682] Verify that saved products persist across login sessions', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.saveProductByName(page, testData.products.persistent.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await CommonActions.logout(page);
    await CommonActions.verifyLogoutSuccess(page);
    
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.persistent.name);
  });

  // [683] Verify that unregistered user cannot save products
  test('[683] Verify that unregistered user cannot save products', async ({ page }) => {
    await CommonActions.navigateTo(page, SavedProductsPage.productCatalog);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productCard);
    
    await SavedProductsActions.selectProduct(page, testData.products.standard.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await CommonActions.clickElement(page, SavedProductsPage.saveButton);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.loginPrompt);
    
    await SavedProductsActions.verifySaveBlocked(page);
    await SavedProductsActions.verifyProductNotSaved(page, testData.products.standard.name);
  });

  // [684] Verify that customer cannot save same product twice
  test('[684] Verify that customer cannot save same product twice', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.saveProductByName(page, testData.products.duplicate.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateBackToProduct(page, testData.products.duplicate.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await CommonActions.clickElement(page, SavedProductsPage.saveButton);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.duplicateWarning);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifySingleOccurrence(page, testData.products.duplicate.name);
  });

  // [685] Verify that customer cannot save out of stock products
  test('[685] Verify that customer cannot save out of stock products', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.outOfStock.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await SavedProductsActions.verifySaveButtonDisabled(page);
    await SavedProductsActions.verifySaveActionBlocked(page);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductNotInSavedList(page, testData.products.outOfStock.name);
  });

  // [686] Verify that expired session prevents saving products
  test('[686] Verify that expired session prevents saving products', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await CommonActions.waitForSessionExpiry(page, testData.sessionTimeout);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.standard.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await CommonActions.clickElement(page, SavedProductsPage.saveButton);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.sessionExpiredMessage);
    
    await SavedProductsActions.verifySaveBlocked(page);
    await SavedProductsActions.verifyProductNotSaved(page, testData.products.standard.name);
  });

  // [687] Verify that customer can save maximum allowed number of products
  test('[687] Verify that customer can save maximum allowed number of products', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.saveProductsUpToLimit(page, testData.maxSavedProducts);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.attemptToSaveAdditionalProduct(page, testData.products.overflow.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.maxLimitWarning);
    
    await SavedProductsActions.verifySaveBlocked(page);
    await SavedProductsActions.verifyProductNotSaved(page, testData.products.overflow.name);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifySavedProductsCount(page, testData.maxSavedProducts);
  });

  // [688] Verify that saving products works with special characters in product name
  test('[688] Verify that saving products works with special characters in product name', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.specialChars.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await SavedProductsActions.saveProduct(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.specialChars.name);
    await SavedProductsActions.verifySpecialCharactersPreserved(page, testData.products.specialChars.name);
  });

  // [689] Verify that saving products works with very long product names
  test('[689] Verify that saving products works with very long product names', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.longName.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await SavedProductsActions.saveProduct(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.longName.name);
    await SavedProductsActions.verifyLongNameHandling(page, testData.products.longName.name);
  });

  // [690] Verify that customer can save products from different categories
  test('[690] Verify that customer can save products from different categories', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.saveProductByName(page, testData.products.electronics.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.saveProductByName(page, testData.products.clothing.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.saveProductByName(page, testData.products.books.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.electronics.name);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.clothing.name);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.books.name);
  });

  // [695] Verify that saving product completes within acceptable time
  test('[695] Verify that saving product completes within acceptable time', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.standard.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    const startTime = Date.now();
    await CommonActions.clickElement(page, SavedProductsPage.saveButton);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    const endTime = Date.now();
    
    const duration = (endTime - startTime) / 1000;
    expect(duration).toBeLessThanOrEqual(testData.performance.saveTimeout);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.standard.name);
  });

  // [696] Verify that saved products list loads within acceptable time
  test('[696] Verify that saved products list loads within acceptable time', async ({ page }) => {
    await CommonActions.login(page, testData.customerWithManySavedProducts.username, testData.customerWithManySavedProducts.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    const startTime = Date.now();
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    const endTime = Date.now();
    
    const duration = (endTime - startTime) / 1000;
    expect(duration).toBeLessThanOrEqual(testData.performance.pageLoadTimeout);
    
    await SavedProductsActions.verifyAllProductsDisplay(page);
    await SavedProductsActions.verifyPageResponsive(page);
  });

  // [697] Verify that bulk save operations perform adequately
  test('[697] Verify that bulk save operations perform adequately', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    const startTime = Date.now();
    await SavedProductsActions.bulkSaveProducts(page, testData.products.bulkSaveList);
    const endTime = Date.now();
    
    const duration = (endTime - startTime) / 1000;
    expect(duration).toBeLessThanOrEqual(testData.performance.bulkSaveTimeout);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyAllBulkProductsSaved(page, testData.products.bulkSaveList);
  });

  // [702] Verify that customer can save products from search results
  test('[702] Verify that customer can save products from search results', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.searchForProduct(page, testData.products.searchable.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.searchResults);
    
    await SavedProductsActions.selectProductFromSearchResults(page, testData.products.searchable.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await SavedProductsActions.saveProduct(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.searchable.name);
  });

  // [703] Verify that saved products show current pricing information
  test('[703] Verify that saved products show current pricing information', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    const originalPrice = testData.products.priceUpdate.originalPrice;
    await SavedProductsActions.saveProductByName(page, testData.products.priceUpdate.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    // Simulate admin updating price
    await SavedProductsActions.simulatePriceUpdate(page, testData.products.priceUpdate.name, testData.products.priceUpdate.newPrice);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    
    await SavedProductsActions.verifyProductPrice(page, testData.products.priceUpdate.newPrice);
    await SavedProductsActions.verifyPriceNotEqual(page, originalPrice);
  });

  // [704] Verify that customer cannot save discontinued products
  test('[704] Verify that customer cannot save discontinued products', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.discontinued.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await SavedProductsActions.verifySaveButtonDisabled(page);
    await SavedProductsActions.verifySaveActionBlocked(page);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductNotInSavedList(page, testData.products.discontinued.name);
  });

  // [705] Verify that saving products works during high traffic periods
  test('[705] Verify that saving products works during high traffic periods', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.popular.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await CommonActions.clickElement(page, SavedProductsPage.saveButton);
    await SavedProductsActions.waitForSaveConfirmation(page);
    
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await SavedProductsActions.verifyProductInSavedList(page, testData.products.popular.name);
  });

  // [706] Verify that customer can organize saved products into categories
  test('[706] Verify that customer can organize saved products into categories', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.saveProductByName(page, testData.products.product1.name);
    await SavedProductsActions.saveProductByName(page, testData.products.product2.name);
    
    await SavedProductsActions.navigateToSavedProducts(page);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.savedProductsList);
    
    await SavedProductsActions.createCustomCategory(page, testData.customCategory.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.successMessage);
    
    await SavedProductsActions.organizeProductsIntoCategory(page, testData.customCategory.name, [
      testData.products.product1.name,
      testData.products.product2.name
    ]);
    
    await SavedProductsActions.verifyProductsCategorized(page, testData.customCategory.name);
  });

  // [707] Verify that customer receives notification when saving products
  test('[707] Verify that customer receives notification when saving products', async ({ page }) => {
    await CommonActions.login(page, testData.registeredCustomer.username, testData.registeredCustomer.password);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.myAccountMenu);
    
    await SavedProductsActions.navigateToProduct(page, testData.products.standard.name);
    await CommonActions.verifyElementVisible(page, SavedProductsPage.productDetailPage);
    
    await CommonActions.clickElement(page, SavedProductsPage.saveButton);
    
    await CommonActions.verifyElementVisible(page, SavedProductsPage.notificationToast);
    await SavedProductsActions.verifyNotificationMessage(page, 'saved successfully');
  });
});

