package pages;

import base.BasePage;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import static org.assertj.core.api.Assertions.assertThat;
import static pageObjects.LoginPage.*;

/**
 * LoginPage - Page actions and assertions
 * Generated by Qentrix ScriptGenerationAgent
 * Framework: Selenium Java JUnit
 */
public class LoginPage extends BasePage {

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String baseUrl = System.getenv("BASE_URL") != null ? System.getenv("BASE_URL") : "http://192.168.10.124:4001";
        driver.get(baseUrl);
        waitForPageLoad();
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterUsername(String username) {
        try {
            waitAndType(By.cssSelector(USERNAME_INPUT), username);
        } catch (Exception e) {
            waitAndType(By.cssSelector(EMAIL_INPUT), username);
        }
    }

    public void enterPassword(String password) {
        waitAndType(By.cssSelector(PASSWORD_INPUT), password);
    }

    public void clickLoginButton() {
        try {
            waitAndClick(By.cssSelector(LOGIN_BUTTON));
        } catch (Exception e) {
            waitAndClick(By.xpath(LOGIN_BUTTON_TEXT));
        }
        waitForPageLoad();
    }

    public void loginWithCredentials(String username, String password) {
        enterUsername(username);
        enterPassword(password);
        clickLoginButton();
    }

    public void clearUsername() {
        try {
            driver.findElement(By.cssSelector(USERNAME_INPUT)).clear();
        } catch (Exception e) {
            driver.findElement(By.cssSelector(EMAIL_INPUT)).clear();
        }
    }

    public void clearPassword() {
        driver.findElement(By.cssSelector(PASSWORD_INPUT)).clear();
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyLoginPageLoaded() {
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(PAGE_HEADING)));
        assertThat(driver.getCurrentUrl()).contains("192.168.10.124:4001");
    }

    public void verifyLoginPageElements() {
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(PAGE_HEADING)));
        assertThat(isElementVisible(By.cssSelector(EMAIL_INPUT)) || isElementVisible(By.cssSelector(USERNAME_INPUT)))
            .as("Email/Username field should be visible")
            .isTrue();
        assertThat(isElementVisible(By.cssSelector(PASSWORD_INPUT)))
            .as("Password field should be visible")
            .isTrue();
        assertThat(isElementVisible(By.cssSelector(LOGIN_BUTTON)) || isElementVisible(By.xpath(LOGIN_BUTTON_TEXT)))
            .as("Login button should be visible")
            .isTrue();
        assertThat(isElementVisible(By.xpath(REGISTER_LINK)))
            .as("Register link should be visible")
            .isTrue();
    }

    public void verifyLoginSuccessful() {
        wait.until(ExpectedConditions.or(
            ExpectedConditions.urlContains("/dashboard"),
            ExpectedConditions.urlContains("/home"),
            ExpectedConditions.visibilityOfElementLocated(By.xpath(DASHBOARD_INDICATOR))
        ));
        String currentUrl = driver.getCurrentUrl();
        assertThat(currentUrl)
            .as("Should redirect away from login page after successful login")
            .doesNotContain("/login");
    }

    public void verifyErrorMessageDisplayed() {
        wait.until(ExpectedConditions.or(
            ExpectedConditions.visibilityOfElementLocated(By.cssSelector(ERROR_MESSAGE)),
            ExpectedConditions.visibilityOfElementLocated(By.xpath(ERROR_MESSAGE_TEXT))
        ));
        assertThat(isElementVisible(By.cssSelector(ERROR_MESSAGE)) || isElementVisible(By.xpath(ERROR_MESSAGE_TEXT)))
            .as("Error message should be visible")
            .isTrue();
    }

    public void verifyInvalidCredentialsError() {
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(INVALID_CREDENTIALS_ERROR)));
        String errorText = getElementText(By.xpath(INVALID_CREDENTIALS_ERROR));
        assertThat(errorText.toLowerCase())
            .as("Error message should indicate invalid credentials")
            .containsAnyOf("invalid", "credentials", "incorrect", "wrong");
    }

    public void verifyRequiredFieldError() {
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(FIELD_REQUIRED_ERROR)));
        assertThat(isElementVisible(By.xpath(FIELD_REQUIRED_ERROR)))
            .as("Required field error should be visible")
            .isTrue();
    }

    public void verifyStatusCode(int expectedCode) {
        // For UI automation, status code validation is typically done via API or network monitoring
        // This is a placeholder for future API integration
        // Actual HTTP status validation would require network interception or API testing
    }

    public void verifyAuthenticationToken() {
        // Token validation would typically be done via:
        // 1. localStorage/sessionStorage check
        // 2. Cookie inspection
        // 3. API response validation
        // Placeholder for future implementation
        waitForPageLoad();
        String currentUrl = driver.getCurrentUrl();
        assertThat(currentUrl)
            .as("Should be on authenticated page after successful login")
            .doesNotContain("/login");
    }
}
