package pages;

import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.LoadState;
import base.BasePage;
import static org.assertj.core.api.Assertions.assertThat;
import static pageObjects.LoginPage.*;

/**
 * LoginPage — Page actions and assertions for Login module
 * Generated by: Qentrix ScriptGenerationAgent
 * Framework: Playwright Java (Hybrid)
 * Extends: BasePage (inherits WebActions helpers)
 */
public class LoginPage extends BasePage {

    public LoginPage(Page page) {
        super(page);
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void navigate() {
        String url = System.getenv("BASE_URL");
        if (url == null || url.isEmpty()) {
            url = testData.getOrDefault("baseUrl", "http://192.168.10.124:4001").toString();
        }
        page.navigate(url);
        page.waitForLoadState(LoadState.DOMCONTENTLOADED);
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterEmail(String email) {
        page.locator(emailInput).first().fill(email);
    }

    public void enterPassword(String password) {
        page.locator(passwordInput).first().fill(password);
    }

    public void clickLoginButton() {
        page.locator(loginButton).first().click();
        page.waitForLoadState(LoadState.DOMCONTENTLOADED);
    }

    public void clickRegisterLink() {
        page.locator(registerLink).first().click();
        page.waitForLoadState(LoadState.DOMCONTENTLOADED);
    }

    public void login(String email, String password) {
        enterEmail(email);
        enterPassword(password);
        clickLoginButton();
    }

    /**
     * Login using credentials from test-data by role name.
     * @param roleName must match RoleName column in credentials.csv
     */
    public void loginAs(String roleName) {
        var creds = getLoginDataByRole(roleName);
        login(creds.get("Username").toString(), creds.get("Password").toString());
    }

    // ── Assertions ────────────────────────────────────────────────────────────

    public void verifyLoginPageLoaded() {
        page.waitForTimeout(500);
        assertThat(page.locator(emailInput).first().isVisible())
            .as("Email input should be visible")
            .isTrue();
        assertThat(page.locator(passwordInput).first().isVisible())
            .as("Password input should be visible")
            .isTrue();
        assertThat(page.locator(loginButton).first().isVisible())
            .as("Login button should be visible")
            .isTrue();
        assertThat(page.locator(registerLink).first().isVisible())
            .as("Register link should be visible")
            .isTrue();
    }

    public void verifyErrorMessageDisplayed() {
        page.waitForTimeout(500);
        assertThat(page.locator(errorMessage).first().isVisible())
            .as("Error message should be visible after invalid login")
            .isTrue();
    }

    public void verifyErrorMessageContains(String expectedText) {
        page.waitForTimeout(500);
        assertThat(page.locator(errorMessage).first().isVisible())
            .as("Error message should be visible")
            .isTrue();
        String actualText = page.locator(errorMessage).first().textContent();
        assertThat(actualText)
            .as("Error message should contain expected text")
            .containsIgnoringCase(expectedText);
    }

    public void verifyRequiredFieldError() {
        page.waitForTimeout(500);
        assertThat(page.locator(requiredFieldError).first().isVisible())
            .as("Required field error should be visible")
            .isTrue();
    }

    public void verifyLoginSuccessful() {
        page.waitForTimeout(500);
        String currentUrl = page.url();
        assertThat(currentUrl)
            .as("User should be redirected away from login page after successful login")
            .doesNotContain("/login")
            .doesNotEndWith(":4001")
            .doesNotEndWith(":4001/");
    }

    public void verifyStatusCode(int expectedStatusCode) {
        // Note: Playwright doesn't expose HTTP status code from page.navigate() by default.
        // For API login validation, use page.request() or separate API test.
        // This method is a placeholder for test case requirements that mention status codes.
        // Implement via network interception or API request if needed.
        page.waitForTimeout(500);
    }

    public void verifyAuthTokenPresent() {
        // Note: Token validation requires network interception or storage access.
        // Placeholder for test case requirement. Implement via:
        // - page.context().cookies() for cookie-based tokens
        // - page.evaluate(() => localStorage.getItem('token')) for localStorage
        // - Network response inspection for response body tokens
        page.waitForTimeout(500);
    }
}
